<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/context_aware_cache.md:206
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\HttpFoundation\Response;

/** @var Response $response */
$response->setVary('X-User-Preference-Hash');

// If you _also_ need to vary on [[= product_name =]] permissions, instead use:
//$response->setVary(['X-User-Context-Hash', 'X-User-Preference-Hash']);
