<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/context_aware_cache.md:95
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\HttpFoundation\Response;

// Inside a custom controller action, or even a Content View controller
/** @var Response $response */
$response->setVary('Cookie');
