<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/context_aware_cache.md:146
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\EventDispatcher\EventSubscriberInterface;
use Symfony\Component\HttpKernel\Event\ResponseEvent;

final class MyEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            ResponseEvent::class => 'addPreferenceHash',
        ];
    }

    public function addPreferenceHash(ResponseEvent $event): void
    {
        $response = $event->getResponse();
        if ($response->headers->get('Content-Type') !== 'application/vnd.fos.user-context-hash') {
            return;
        }

        $response->headers->set('X-User-Preference-Hash', '<your-hash>');
    }
}
