<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_logicaland_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\Payment\PaymentQuery;
use Ibexa\Contracts\Payment\Payment\Query\Criterion\CreatedAt;
use Ibexa\Contracts\Payment\Payment\Query\Criterion\Currency;
use Ibexa\Contracts\Payment\Payment\Query\Criterion\LogicalAnd;

$query = new PaymentQuery();
$query->setQuery(new LogicalAnd(
    new CreatedAt(new DateTime('2023-03-01')),
    new Currency('USD'),
));
