<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationfield.md:64
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Relation FieldType example settings

use Ibexa\Core\FieldType\Relation\Type;

$settings = [
    'selectionMethod' => 1,
    'selectionRoot' => null,
    'selectionContentTypes' => [],
];
