<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationfield.md:29
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example

/** @var \Ibexa\Core\FieldType\Relation\Value $relation */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
$relation->destinationContentId = $contentInfo->id;
