<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationfield.md:41
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Relation as Relation;

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
// Instantiates a Relation Value object
$relationValue = new Relation\Value($contentInfo->id);
