app.rest:
    resource: routes_rest.yaml
    prefix: '%ezpublish_rest.path_prefix%'

app.rest.options:
    resource: routes_rest.yaml
    prefix: '%ezpublish_rest.path_prefix%'
    type: rest_options
