parameters:
    app.rest.output.visitor.xml.regexps: ['(^application/app\.api\.[A-Za-z]+\+xml$)']
    app.rest.output.visitor.json.regexps: ['(^application/app\.api\.[A-Za-z]+\+json$)']

services:

    app.rest.output.visitor.xml:
        class: Ibexa\Contracts\Rest\Output\Visitor
        arguments:
            $generator: '@Ibexa\Rest\Output\Generator\Xml'
            $normalizer: '@ibexa.rest.serializer'
            $encoder: '@ibexa.rest.serializer.encoder.xml'
            $valueObjectVisitorResolver: '@App\Rest\Output\ValueObjectVisitorResolver'
            $format: 'xml'
        tags:
            - { name: ibexa.rest.output.visitor, regexps: app.rest.output.visitor.xml.regexps, priority: 20 }

    app.rest.output.visitor.json:
        class: Ibexa\Contracts\Rest\Output\Visitor
        arguments:
            $generator: '@Ibexa\Rest\Output\Generator\Json'
            $normalizer: '@ibexa.rest.serializer'
            $encoder: '@ibexa.rest.serializer.encoder.json'
            $valueObjectVisitorResolver: '@App\Rest\Output\ValueObjectVisitorResolver'
            $format: 'json'
        tags:
            - { name: ibexa.rest.output.visitor, regexps: app.rest.output.visitor.json.regexps, priority: 20 }

    App\Rest\Output\ValueObjectVisitorResolver:
        arguments:
            $visitors: !tagged_iterator { tag: 'app.rest.output.value_object.visitor', index_by: 'type' }
            $resolver: '@Ibexa\Contracts\Rest\Output\ValueObjectVisitorResolver'

    App\Rest\ValueObjectVisitor\RestLocation:
        class: App\Rest\ValueObjectVisitor\RestLocation
        parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
        arguments:
            $urlAliasService: '@ibexa.api.service.url_alias'
        tags:
            - { name: app.rest.output.value_object.visitor, type: Ibexa\Rest\Server\Values\RestLocation }

    App\Rest\Controller\:
        resource: '../src/Rest/Controller/'
        parent: Ibexa\Rest\Server\Controller
        autowire: true
        autoconfigure: true
        tags: [ 'controller.service_arguments' ]

    App\Rest\ValueObjectVisitor\Greeting:
        parent: Ibexa\Contracts\Rest\Output\ValueObjectVisitor
        tags:
            - { name: ibexa.rest.output.value_object.visitor, type: App\Rest\Values\Greeting }

    App\Rest\InputParser\GreetingInput:
        parent: Ibexa\Rest\Server\Common\Parser
        tags:
            - { name: ibexa.rest.input.parser, mediaType: application/vnd.ibexa.api.GreetingInput }
