<?php

declare(strict_types=1);
// Source: docs/search/activity_log_search_reference/user_criterion.md:12
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ActivityLog\Values\ActivityLog as ActivityLog;

$query = new ActivityLog\Query([
    new ActivityLog\Criterion\UserCriterion([10, 14]),
]);
