ezplatform:
    system:
        admin_group:
            calendar:
                event_types:
                    future_publication:
                        color: '#47BEDB'
                        reschedule:
                            action_name:
                                icon: '/bundles/ibexaplatformicons/img/all-icons.svg#notice'
