<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_method_type_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\PaymentMethod\PaymentMethodQuery;

/** @var \Ibexa\Contracts\Payment\PaymentMethod\Type\TypeRegistryInterface $paymentMethodTypeRegistry */
$paymentMethodType = $paymentMethodTypeRegistry->getPaymentMethodType('offline');

$query = new PaymentMethodQuery(
    new \Ibexa\Contracts\Payment\PaymentMethod\Query\Criterion\Type($paymentMethodType)
);
