<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/price_customergroup_criterion.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\ProductCatalog\Values\Price\PriceQuery;

/** @var \Ibexa\Contracts\ProductCatalog\CustomerGroupServiceInterface $customerGroupService */
$customerGroup = $customerGroupService->getCustomerGroup(123);

$query = new PriceQuery(
    new \Ibexa\Contracts\ProductCatalog\Values\Price\Query\Criterion\CustomerGroup($customerGroup)
);
