<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/countryfield.md:53
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Content $content */
$content->fields['countries'] = ['JP', 'NO'];
