<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/countryfield.md:41
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Country FieldType example settings
$settings = [
    'isMultiple' => true,
];
