<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/countryfield.md:71
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example
/** @var \Ibexa\Core\FieldType\Country\Value $value */
$value->countries = [
    'JP' => [
        'Name' => 'Japan',
        'Alpha2' => 'JP',
        'Alpha3' => 'JPN',
        'IDC' => 81,
    ],
];
