<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/countryfield.md:89
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Country as Country;

// Instantiates a Country Value object
$countryValue = new Country\Value(
    [
        'JP' => [
            'Name' => 'Japan',
            'Alpha2' => 'JP',
            'Alpha3' => 'JPN',
            'IDC' => 81,
        ],
    ]
);
