<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/productpricerange_aggregation.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\ProductPriceRangeAggregation;

$query = new ProductQuery();
$query->setAggregations([
    new ProductPriceRangeAggregation('price', 'PLN', [
        Range::ofInt(0, 10000),
        Range::ofInt(10000, null),
    ]),
]);
