<?php

declare(strict_types=1);
// Source: docs/search/url_search_reference/logicalor_url_criterion.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\URL\Query\Criterion;
use Ibexa\Contracts\Core\Repository\Values\URL\URLQuery;

$query = new URLQuery();
$query->filter = new Criterion\LogicalOr(
    [
        new Criterion\SectionIdentifier(['sports', 'news']),
        new Criterion\Pattern('ibexa.co'),
    ]
);
