services:
    App\Calendar\Holidays\EventType:
        arguments:
            $actions: [ ]
        tags:
            - { name: ezplatform.calendar.event_type }
            
    App\Calendar\Holidays\EventSourceFactory:
        arguments:
            $eventType: '@App\Calendar\Holidays\EventType'

    App\Calendar\Holidays\EventSource:
        class: Ibexa\Tests\Calendar\Calendar\EventSource
        factory: [ '@App\Calendar\Holidays\EventSourceFactory','createEventSource' ]
        tags:
            - { name: ezplatform.calendar.event_source }
