<?php

declare(strict_types=1);
// Source: docs/tutorials/beginner_tutorial/5_display_a_list_of_content_items.md:61
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\QueryType;

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Core\QueryType\QueryType;

class RideQueryType implements QueryType
{
    public static function getName(): string
    {
        return 'Ride';
    }

    /** @param array<string, mixed> $parameters */
    public function getQuery(array $parameters = []): \Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery
    {
        return new LocationQuery([
            'filter' => new Criterion\LogicalAnd(
                [
                    new Criterion\Visibility(Criterion\Visibility::VISIBLE),
                    new Criterion\ContentTypeIdentifier(['ride']),
                ]
            ),
        ]);
    }

    public function getSupportedParameters(): array
    {
        return [];
    }
}
