services:
    App\Query\Aggregation\Solr\PriorityAggregationVisitor:
        class: EzSystems\EzPlatformSolrSearchEngine\Query\Common\AggregationVisitor\RangeAggregationVisitor
        factory: ['@Ibexa\Solr\Query\Common\AggregationVisitor\Factory\ContentFieldAggregationVisitorFactory', 'createRangeAggregationVisitor']
        arguments:
            $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
            $searchIndexFieldName: 'priority_i'
        tags:
            - { name: ibexa.solr.query.content.aggregation_visitor }
            - { name: ibexa.solr.query.location.aggregation_visitor }
            
    App\Query\Aggregation\Solr\PriorityAggregationResultExtractor:
        class: Ibexa\Solr\ResultExtractor\AggregationResultExtractor\RangeAggregationResultExtractor
        arguments:
            $aggregationClass: 'App\Query\Aggregation\PriorityRangeAggregation'
        tags:
            - { name: ibexa.solr.query.location.aggregation_result_extractor }
            
    App\Query\Aggregation\PriorityAggregationVisitor:
        tags:
            - { name: 'ibexa.solr.query.location.aggregation_visitor' }
    App\Query\Aggregation\PriorityAggregationResultExtractor:
        tags:
            - { name: 'ibexa.solr.query.location.aggregation_result_extractor' }

    App\Search\Mapper\WebinarEventTitleFulltextFieldMapper:
        arguments:
            - '@Ibexa\Contracts\Core\Persistence\Content\Handler'
            - '@Ibexa\Contracts\Core\Persistence\Content\Location\Handler'
        tags:
            - {name: ibexa.solr.field_mapper.content}

    App\Query\Criterion\CameraManufacturerVisitor:            
        tags:
            - { name: ibexa.search.solr.query.content.criterion.visitor }
            - { name: ibexa.search.solr.query.location.criterion.visitor }

    App\Query\SortClause\Score:
        tags:
            - { name: ibexa.search.solr.query.content.sort_clause.visitor }
            - { name: ibexa.search.solr.query.location.sort_clause.visitor }
