ibexa:
    system:
        admin_group:
            admin_ui_forms:
                content_edit:
                    form_templates:
                        - { template: '@ibexadesign/content/form_fields_ai.html.twig', priority: -10000000 } }
