<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/createdat_sort_clause.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;

$productQuery = new ProductQuery(
    null,
    null,
    [
        new \Ibexa\Contracts\ProductCatalog\Values\Product\Query\SortClause\CreatedAt(
            \Ibexa\Contracts\ProductCatalog\Values\Product\Query\SortClause\CreatedAt::SORT_ASC
        ),
    ]
);
