<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_validation.md:21
// (auto-generated by tools/extract-inline-php.php — do not edit)

[
    'stringLength' => [
        'minStringLength' => [
            'type' => 'int',
            'default' => 0,
        ],
        'maxStringLength' => [
            'type' => 'int',
            'default' => null,
        ],
    ],
];
