<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/datemodified_sort_clause.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\SortClause;

$query = new LocationQuery();
$query->sortClauses = [new SortClause\DateModified()];
