<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/productstockrange_aggregation.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\ProductStockRangeAggregation;

$productQuery = new ProductQuery();
$productQuery->setAggregations([
    new ProductStockRangeAggregation('stock', [
        Range::ofInt(null, 10),
        Range::ofInt(10, 100),
        Range::ofInt(100, null),
    ]),
]);
