<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/parentlocationid_criterion.md:53
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$locationId = 12345;

$query = new LocationQuery();
$query->query = new Criterion\LogicalAnd([
    new Criterion\Visibility(Criterion\Visibility::VISIBLE),
    new Criterion\ParentLocationId($locationId),
]);

/** @var \Ibexa\Contracts\Core\Repository\SearchService $searchService */
$results = $searchService->findLocations($query);
$posts = [];
foreach ($results->searchHits as $searchHit) {
    $posts[] = $searchHit;
}

return $this->render('full/blog.html.twig', [
    'posts' => $posts,
]);
