<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/baseprice_criterion.md:23
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;

$query = new ProductQuery(
    null,
    new \Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion\BasePrice(
        \Money\Money::EUR(12900),
        \Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion\Operator::GTE
    )
);
