<?php declare(strict_types=1);

namespace App\Command;

use Ibexa\Contracts\Core\Repository\SearchService;
use Ibexa\Contracts\Core\Repository\Values\Content\EmbeddingQueryBuilder;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion\ContentTypeIdentifier;
use Ibexa\Contracts\Taxonomy\Search\Query\Value\TaxonomyEmbedding;
use Symfony\Component\Console\Attribute\AsCommand;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

#[AsCommand(
    name: 'doc:find_by_taxonomy_embedding',
    description: 'Finds content using a taxonomy embedding query.'
)]
class FindByTaxonomyEmbeddingCommand extends Command
{
    public function __construct(private readonly SearchService $searchService)
    {
        parent::__construct();
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        // Example embedding vector (normally generated by an embedding provider)
        $vector = [
            0.0123,
            -0.9876,
            0.4567,
            0.1111,
        ];

        $query = EmbeddingQueryBuilder::create()
            ->withEmbedding(new TaxonomyEmbedding($vector))
            ->setFilter(new ContentTypeIdentifier('article'))
            ->setLimit(10)
            ->setOffset(0)
            ->setPerformCount(true)
            ->build();

        $result = $this->searchService->findContent($query);

        $output->writeln('Found ' . $result->totalCount . ' items');

        foreach ($result->searchHits as $searchHit) {
            $output->writeln((string) $searchHit->valueObject->id);
        }

        return self::SUCCESS;
    }
}
