<?php

declare(strict_types=1);
// Source: docs/search/activity_log_search_reference/action_criterion.md:14
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ActivityLog\ActivityLogServiceInterface;
use Ibexa\Contracts\ActivityLog\Values\ActivityLog as ActivityLog;

$query = new ActivityLog\Query([
    new ActivityLog\Criterion\ActionCriterion([
        ActivityLogServiceInterface::ACTION_DELETE,
        ActivityLogServiceInterface::ACTION_TRASH,
    ]),
]);
