config:
  default: false
  heading-style: consistent
  list-indent: true
  no-reversed-links: true
  no-missing-space-atx: true
  heading-start-left: true
  no-multiple-space-blockquote: true
  no-blanks-blockquote: true
  hr-style: true
  no-empty-links: true
  code-fence-style: backtick
  strong-style: asterisk
  table-pipe-style:
    style: leading_and_trailing

  blanks-around-fences: true
  ul-style: dash
  ol-prefix: 
    style: one_or_ordered

ignores:
  - "docs/snippets/**"
  - "docs/index.md"
