version: 2

mkdocs:
  configuration: mkdocs.yml
  fail_on_warning: false

build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: pip_require.txt
    - requirements: requirements.txt
