<?php

declare(strict_types=1);
// Source: docs/administration/back_office/back_office_menus/back_office_menus.md:89
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Knp\Menu\ItemInterface $menu */
$menu->addChild(
    'all_content_list',
    [
        'extras' => [
            'template' => '@ibexadesign/list/all_content_list.html.twig',
            'template_parameters' => [
                'custom_parameter' => 'value',
            ],
        ],
    ]
);
