<?php

declare(strict_types=1);
// Source: docs/administration/back_office/back_office_menus/back_office_menus.md:110
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Knp\Menu\ItemInterface $menu */
$menu->addChild(
    'all_content_list',
    [
        'label' => 'translation.key',
        'extras' => [
            'translation_domain' => 'messages',
        ],
    ]
);
