Symfony\Component\ErrorHandler\Error\FatalError {#22887
  #message: "Error: Class Ibexa\Cdp\Segmentation\UserSegmentsCdpLoadStrategy contains 1 abstract method and must therefore be declared abstract or implement the remaining method (Ibexa\Segmentation\Loader\UserSegmentsLoadStrategyInterface::canUserReadSegment)"
  #code: 0
  #file: "./vendor/ibexa/cdp/src/lib/Segmentation/UserSegmentsCdpLoadStrategy.php"
  #line: 18
  -error: array:5 [
    "type" => 1
    "message" => "Class Ibexa\Cdp\Segmentation\UserSegmentsCdpLoadStrategy contains 1 abstract method and must therefore be declared abstract or implement the remaining method (Ibexa\Segmentation\Loader\UserSegmentsLoadStrategyInterface::canUserReadSegment)"
    "file" => "/tmp/ibexa-dxp-phpdoc/vendor/ibexa/cdp/src/lib/Segmentation/UserSegmentsCdpLoadStrategy.php"
    "line" => 18
    "trace" => array:16 [
      0 => array:3 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/error-handler/DebugClassLoader.php"
        "line" => 322
        "function" => "include"
      ]
      1 => array:3 [
        "function" => "loadClass"
        "class" => "Symfony\Component\ErrorHandler\DebugClassLoader"
        "type" => "->"
      ]
      2 => array:3 [
        "function" => "class_exists"
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/config/Resource/ClassExistenceResource.php"
        "line" => 76
      ]
      3 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/dependency-injection/ContainerBuilder.php"
        "line" => 414
        "function" => "isFresh"
        "class" => "Symfony\Component\Config\Resource\ClassExistenceResource"
        "type" => "->"
      ]
      4 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/dependency-injection/Compiler/ResolveClassPass.php"
        "line" => 33
        "function" => "getReflectionClass"
        "class" => "Symfony\Component\DependencyInjection\ContainerBuilder"
        "type" => "->"
      ]
      5 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/dependency-injection/Compiler/Compiler.php"
        "line" => 73
        "function" => "process"
        "class" => "Symfony\Component\DependencyInjection\Compiler\ResolveClassPass"
        "type" => "->"
      ]
      6 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/dependency-injection/ContainerBuilder.php"
        "line" => 825
        "function" => "compile"
        "class" => "Symfony\Component\DependencyInjection\Compiler\Compiler"
        "type" => "->"
      ]
      7 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/http-kernel/Kernel.php"
        "line" => 516
        "function" => "compile"
        "class" => "Symfony\Component\DependencyInjection\ContainerBuilder"
        "type" => "->"
      ]
      8 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/http-kernel/Kernel.php"
        "line" => 762
        "function" => "initializeContainer"
        "class" => "Symfony\Component\HttpKernel\Kernel"
        "type" => "->"
      ]
      9 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/http-kernel/Kernel.php"
        "line" => 122
        "function" => "preBoot"
        "class" => "Symfony\Component\HttpKernel\Kernel"
        "type" => "->"
      ]
      10 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/framework-bundle/Console/Application.php"
        "line" => 195
        "function" => "boot"
        "class" => "Symfony\Component\HttpKernel\Kernel"
        "type" => "->"
      ]
      11 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/framework-bundle/Console/Application.php"
        "line" => 69
        "function" => "registerCommands"
        "class" => "Symfony\Bundle\FrameworkBundle\Console\Application"
        "type" => "->"
      ]
      12 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/console/Application.php"
        "line" => 195
        "function" => "doRun"
        "class" => "Symfony\Bundle\FrameworkBundle\Console\Application"
        "type" => "->"
      ]
      13 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/symfony/runtime/Runner/Symfony/ConsoleApplicationRunner.php"
        "line" => 49
        "function" => "run"
        "class" => "Symfony\Component\Console\Application"
        "type" => "->"
      ]
      14 => array:5 [
        "file" => "/tmp/ibexa-dxp-phpdoc/vendor/autoload_runtime.php"
        "line" => 32
        "function" => "run"
        "class" => "Symfony\Component\Runtime\Runner\Symfony\ConsoleApplicationRunner"
        "type" => "->"
      ]
      15 => array:4 [
        "file" => "/tmp/ibexa-dxp-phpdoc/bin/console"
        "line" => 15
        "args" => array:1 [
          0 => "/tmp/ibexa-dxp-phpdoc/vendor/autoload_runtime.php"
        ]
        "function" => "require_once"
      ]
    ]
  ]
}
