<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/ancestor_criterion.md:53
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$locationId = 12345;

$query = new LocationQuery();
/** @var \Ibexa\Contracts\Core\Repository\LocationService $locationService */
$query->query = new Criterion\Ancestor([$locationService->loadLocation($locationId)->pathString]);

/** @var \Ibexa\Contracts\Core\Repository\SearchService $searchService */
$results = $searchService->findLocations($query);
$breadcrumbs = [];
foreach ($results->searchHits as $searchHit) {
    $breadcrumbs[] = $searchHit;
}

return $this->render('parts/breadcrumbs.html.twig', [
    'breadcrumbs' => $breadcrumbs,
]);
