<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/isbnfield.md:36
// (auto-generated by tools/extract-inline-php.php — do not edit)

[
    'isISBN13' => true,
];
