ezdesign:
    design_list:
        my_design: [ my_theme ]

ezplatform:
    system:
        site_group:
            design: my_design
            content_view:
                full:
                    folder:
                        controller: ez_query::contentQueryAction
                        template: '@ezdesign/full/folder.html.twig'
                        params:
                            query:
                                query_type: 'Children'
                                parameters:
                                    content: '@=content'
                                assign_results_to: items
                                limit: 3
                        match:
                            Identifier\ContentType: folder
                content_query_field:
                    blog:
                        template: '@ezdesign/content_query/blog_posts.html.twig'
                        match:
                            Identifier\ContentType: blog
                            '@Ibexa\FieldTypeQuery\ContentView\FieldDefinitionIdentifierMatcher': query
