<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/iscontainer_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\IsContainer(); // Finds containers
$query->query = new Criterion\IsContainer(false); // Finds non-containers
