<?php

declare(strict_types=1);
// Source: docs/multisite/languages/automated_translations.md:38
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // ...
    Ibexa\Bundle\AutomatedTranslation\IbexaAutomatedTranslationBundle::class => ['all' => true],
    Ibexa\Bundle\AdminUi\IbexaAdminUiBundle::class => ['all' => true],
    // ...
];
