<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/imagedimensions_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$imageCriteriaData = [
    'width' => [
        'min' => 100, // (default: 0, optional)
        'max' => 1000, // (default: null, optional)
    ],
    'height' => [
        'min' => 500, // (default: 0, optional)
        'max' => 1500, // (default: null, optional)
    ],
];

$query->query = new Criterion\Image\Dimensions('image', $imageCriteriaData);
