<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/richtextfield.md:74
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
/** @var \Ibexa\Contracts\Core\Repository\Values\ContentType\ContentType $contentType */
$contentCreateStruct = $contentService->newContentCreateStruct($contentType, 'eng-GB');

$inputString = <<<DOCBOOK
<?xml version="1.0" encoding="UTF-8"?>
<section xmlns="http://docbook.org/ns/docbook"
         xmlns:xlink="http://www.w3.org/1999/xlink"
         xmlns:ezxhtml="http://ibexa.co/xmlns/dxp/docbook/xhtml"
         xmlns:ezcustom="http://ibexa.co/xmlns/dxp/docbook/custom"
         version="5.0-variant ezpublish-1.0">
    <title ezxhtml:level="2">This is a title.</title>
    <para ezxhtml:class="paraClass">This is a paragraph.</para>
</section>
DOCBOOK;

$contentCreateStruct->setField('description', $inputString);
