<?php

declare(strict_types=1);
// Source: docs/administration/back_office/back_office_elements/formatting_date_and_time.md:23
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\Service;

use Ibexa\User\UserSetting\DateTimeFormat\FormatterInterface;

class MyService
{
    public function __construct(private readonly FormatterInterface $shortDateTimeFormatter)
    {
        // your code
    }

    public function foo(): void
    {
        // your code

        $now = new \DateTimeImmutable();
        $date = $this->shortDateTimeFormatter->format($now);
        $utc = $this->shortDateTimeFormatter->format($now, 'UTC');

        // your code
    }
}
