services:
    App\Query\Criterion\Solr\CameraManufacturerVisitor:
        tags:
            - { name: ezpublish.search.solr.query.content.criterion_visitor }
            - { name: ezpublish.search.solr.query.location.criterion_visitor }
