<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/payment_identifier_sort_clause.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\Payment\PaymentQuery;

$criteria = null;

$paymentQuery = new PaymentQuery(
    $criteria,
    [
        new \Ibexa\Contracts\Payment\Payment\Query\SortClause\Identifier(
            \Ibexa\Contracts\Payment\Payment\Query\SortClause\Identifier::SORT_ASC
        ),
    ]
);
