<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/image_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$imageCriteriaData = [
    'mimeTypes' => [
       'image/png',
    ],
    'orientation' => [
       'image/png',
    ],
    'width' => [
        'min' => 0, // (default: 0, optional)
        'max' => 1000, // (default: null, optional)
    ],
    'height' => [
        'min' => 0, // (default: 0, optional)
        'max' => 1000, // (default: null, optional)
    ],
    'size' => [
        'min' => 0, // (default: 0, optional)
        'max' => 2, // (default: null, optional)
    ],
];

$query = new Query();
$query->query = new Criterion\Image('image', $imageCriteriaData);
