<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/remoteid_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\RemoteId('abab615dcf26699a4291657152da4337');
