<?php

declare(strict_types=1);
// Source: docs/api/php_api/php_api.md:151
// (auto-generated by tools/extract-inline-php.php — do not edit)

try {
    // ...
} catch (\Ibexa\Contracts\Core\Repository\Exceptions\NotFoundException) {
    $output->writeln("<error>No content with id $contentId found</error>");
} catch (\Ibexa\Contracts\Core\Repository\Exceptions\UnauthorizedException) {
    $output->writeln("<error>Permission denied on content with id $contentId</error>");
}
