<?php

declare(strict_types=1);
// Source: docs/api/php_api/php_api.md:111
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Repository;
use Ibexa\Contracts\Core\Repository\Values\Content\Location;

//...

/** @var Repository $repository */
/** @var Location $location */
$hiddenLocation = $repository->sudo(static fn (Repository $repository): Location => $repository->getLocationService()->hideLocation($location));
