ezpublish:
    system:
        site:
            image_editor:
                action_groups:
                    default:
                        id: default
                        label: Default
                        actions:
                            # ...
                            dot:
                                id: dot
                                priority: 50
