<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/custompricestats_aggregation.md:24
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface;
use Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\CustomPriceStatsAggregation;

/** @var CurrencyInterface $currency */
/** @var CustomerGroupInterface $customerGroup */
$query = new ProductQuery();
$query->setAggregations([
    new CustomPriceStatsAggregation('custom_price_stats_aggregation', $currency, $customerGroup),
]);
