#!/usr/bin/env php
<?php

/**
 * Regenerates tests/yaml-validation-baseline.yaml from the current test failures.
 *
 * Usage:
 *   composer phpunit-update-baseline
 *
 * The baseline suppresses EXPECTED failures so that only NEW failures block CI.
 * After fixing a doc error, regenerate the baseline so the fix is tracked.
 *
 * Entries use relative paths from the repo root. The optional 'message' field
 * is a regex pattern matched against the error message.
 */

declare(strict_types=1);

$outFile = __DIR__ . '/yaml-validation-baseline.yaml';
$emptyBaseline = "# Auto-generated by `composer phpunit-update-baseline`. Do not edit manually.\nignoreErrors:\n";

// Temporarily clear baseline so PHPUnit reports ALL failures (not suppressed ones)
$previousBaseline = file_exists($outFile) ? file_get_contents($outFile) : null;
file_put_contents($outFile, $emptyBaseline);

// Run PHPUnit and capture XML output
$phpunitBin = __DIR__ . '/../vendor/bin/phpunit';
$tmpLog = sys_get_temp_dir() . '/phpunit-baseline-' . getmypid() . '.xml';

$cmd = sprintf(
    'php %s --log-junit %s 2>/dev/null',
    escapeshellarg($phpunitBin),
    escapeshellarg($tmpLog),
);

passthru($cmd);

if (!file_exists($tmpLog)) {
    if ($previousBaseline !== null) {
        file_put_contents($outFile, $previousBaseline);
    }
    fwrite(STDERR, "ERROR: PHPUnit did not produce a JUnit log file.\n");
    exit(1);
}

$xml = simplexml_load_file($tmpLog);
unlink($tmpLog);

if ($xml === false) {
    fwrite(STDERR, "ERROR: Could not parse JUnit XML.\n");
    exit(1);
}

$repoRoot = dirname(__DIR__);
$entries = [];

// Collect all failures/errors at any nesting depth using XPath
/** @var \SimpleXMLElement[] $testcases */
$testcases = $xml->xpath('//testcase[failure or error]') ?: [];

foreach ($testcases as $testcase) {
    $failure = $testcase->failure ?? $testcase->error ?? null;
    if ($failure === null) {
        continue;
    }

    $message = (string) $failure;
    // Extract file path and line from failure message
    // Patterns:
    //   "Invalid configuration for "X" in path/to/file.yaml: error"
    //   "Invalid configuration for "X" in path/to/file.md:123 — error"
    //   "YAML parse error in path/to/file.md at line 123: error"
    $path = null;
    $line = null;
    $errorMessage = null;

    if (preg_match('/Invalid configuration for "[^"]*" in ([^\n:]+?):(\d+) — (.+)/s', $message, $m)) {
        $path = trim($m[1]);
        $line = (int) $m[2];
        $errorMessage = trim(explode("\n", $m[3])[0]);
    } elseif (preg_match('/Invalid configuration for "[^"]*" in ([^\n:]+?): (.+)/s', $message, $m)) {
        $path = trim($m[1]);
        $errorMessage = trim(explode("\n", $m[2])[0]);
    } elseif (preg_match('/YAML parse error in ([^\n]+?) at line (\d+): (.+)/s', $message, $m)) {
        $path = trim($m[1]);
        $line = (int) $m[2];
        $errorMessage = trim(explode("\n", $m[3])[0]);
    }

    if ($path === null) {
        continue;
    }

    // Convert absolute path to relative
    if (str_starts_with($path, $repoRoot)) {
        $path = ltrim(substr($path, strlen($repoRoot)), '/');
    }

    $entry = ['path' => $path];
    if ($line !== null) {
        $entry['line'] = $line;
    }
    if ($errorMessage !== null) {
        // Store as a regex: escape special chars, keep it readable
        $entry['message'] = '~' . preg_quote($errorMessage, '~') . '~';
    }

    $key = $path . ':' . ($line ?? '');
    $entries[$key] = $entry;
}

ksort($entries);

// Render as YAML manually (keep it readable without needing a YAML library)
$lines = [];
$lines[] = '# Auto-generated by `composer phpunit-update-baseline`. Do not edit manually.';
$lines[] = '# To suppress a failure: regenerate this file after confirming it is expected.';
$lines[] = '# To fix a suppressed failure: fix the doc error and regenerate.';
$lines[] = 'ignoreErrors:';

foreach ($entries as $entry) {
    $lines[] = '    -';
    $lines[] = sprintf('        path: %s', $entry['path']);
    if (isset($entry['line'])) {
        $lines[] = sprintf('        line: %d', $entry['line']);
    }
    if (isset($entry['message'])) {
        // Wrap message in single quotes, escaping internal single quotes
        $msg = str_replace("'", "''", $entry['message']);
        $lines[] = sprintf("        message: '%s'", $msg);
    }
}

$content = implode("\n", $lines) . "\n";
$outFile = __DIR__ . '/yaml-validation-baseline.yaml';
file_put_contents($outFile, $content);

$count = count($entries);
echo "Baseline written to tests/yaml-validation-baseline.yaml ({$count} entries)\n";
if ($count === 0) {
    echo "No failures found — baseline is empty. All tests pass!\n";
}
