                    transitions:
                        to_legal:
                            from: [draft]
                            to: [legal]
                            label: To legal
                            color: '#8888ba'
                            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#notice'
                            reviewers:
                                required: true
                            validate: true
                            actions:
                                legal_transition_action:
                                    data:
                                        message: "Sent to the legal department"
                        back_to_draft:
                            reverse: to_legal
                            label: Back to draft
                            color: '#cb8888'
                            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#back'
                        done:
                            from: [draft]
                            to: [done]
                            label: Done
                            color: '#88ad88'
                            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#checkbox'
                            validate: true
                            actions:
                                publish: ~