<?php

declare(strict_types=1);
// Source: docs/update_and_migration/from_4.6/update_from_4.6.md:165
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // ...
    Ibexa\Bundle\CoreSearch\IbexaCoreSearchBundle::class => ['all' => true],
];
