<?php

declare(strict_types=1);
// Source: docs/users/oauth_server.md:38
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // A lot of bundles…
    Ibexa\Bundle\OAuth2Server\IbexaOAuth2ServerBundle::class => ['all' => true],
    League\Bundle\OAuth2ServerBundle\LeagueOAuth2ServerBundle::class => ['all' => true],
];
