<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/datemetadata_criterion.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\DateMetadata(
    Criterion\DateMetadata::CREATED,
    Criterion\Operator::BETWEEN,
    [1576800000, 1576972800]
);
