<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/datemetadata_criterion.md:66
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new LocationQuery();
$date = strtotime('-1 week');
$query->query = new Criterion\LogicalAnd(
    [
        new Criterion\ContentTypeIdentifier('blog_post'),
        new Criterion\DateMetadata(Criterion\DateMetadata::CREATED, Criterion\Operator::GTE, $date),
    ]
);
