<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/taxonomy_entry_id.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Taxonomy\Search\Query\Criterion;

$query = new Query();
$query->query = new Criterion\TaxonomyEntryId(1);
