<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/producttypeterm_aggregation.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\ProductTypeTermAggregation;

$query = new ProductQuery();
$query->setAggregations([
    new ProductTypeTermAggregation('product_type'),
]);
