name: Browser tests

on:
    push:
        tags:
            - 'v3*'

jobs:
    regression-commerce-setup1:
        name: "PHP 7.4/PostgreSQL/Varnish/Redis/Multirepository"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "commerce"
            project-version: ${{ github.ref_name }}
            test-suite: "--profile=regression --suite=commerce"
            test-setup-phase-1: "--profile=regression --suite=setup-commerce --tags=~@part2 --mode=standard"
            test-setup-phase-2: "--profile=regression --suite=setup-commerce --tags=@part2 --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/db-postgresql.yml:doc/docker/varnish.yml:doc/docker/redis.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            job-count: 3
            multirepository: true
            timeout: 120
        secrets:
            SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
            SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
            TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-commerce-setup2:
        name: "PHP 7.3/MySQL/Multirepository"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "commerce"
            project-version: ${{ github.ref_name }}
            test-suite: "--profile=regression --suite=commerce"
            test-setup-phase-1: "--profile=regression --suite=setup-commerce --tags=~@part2 --mode=standard"
            test-setup-phase-2: "--profile=regression --suite=setup-commerce --tags=@part2 --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            job-count: 3
            multirepository: true
            php-image: "ezsystems/php:7.3-v2-node14"
            timeout: 120
        secrets:
            SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
            SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
            TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    regression-commerce-setup3:
        name: "PHP 8.1/MySQL/Multirepository"
        uses: ibexa/gh-workflows/.github/workflows/browser-tests.yml@main
        with:
            project-edition: "commerce"
            project-version: ${{ github.ref_name }}
            test-suite: "--profile=regression --suite=commerce"
            test-setup-phase-1: "--profile=regression --suite=setup-commerce --tags=~@part2 --mode=standard"
            test-setup-phase-2: "--profile=regression --suite=setup-commerce --tags=@part2 --mode=standard"
            setup: "doc/docker/base-dev.yml:doc/docker/selenium.yml"
            send-success-notification: ${{ github.event.inputs.send-success-notification != 'false' }}
            job-count: 3
            multirepository: true
            php-image: "ezsystems/php:8.1-v2-node16"
            timeout: 120
        secrets:
            SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
            SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
            TRAVIS_GITHUB_TOKEN: ${{ secrets.TRAVIS_GITHUB_TOKEN }}
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
