name: Call Create Release for tag Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  create_release_for_tag:
    uses: ibexa/gh-workflows/.github/workflows/release.yml@main
    secrets:
      AUTOMATION_CLIENT_ID: ${{ secrets.AUTOMATION_CLIENT_ID }}
      AUTOMATION_CLIENT_INSTALLATION: ${{ secrets.AUTOMATION_CLIENT_INSTALLATION }}
      AUTOMATION_CLIENT_SECRET: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
      JIRA_TOKEN: ${{ secrets.JIRA_TOKEN }}
