ibexa_fieldtype_page:
    layouts:
        sidebar:
            identifier: sidebar
            name: Right sidebar
            description: Main section with sidebar on the right
            thumbnail: /assets/images/layouts/sidebar.png
            template: '@ibexadesign/layouts/sidebar.html.twig'
            zones:
                first:
                    name: First zone
                second:
                    name: Second zone
    blocks:
        contentlist:
            views:
                custom:
                    template: '@ibexadesign/blocks/contentlist.html.twig'
                    name: Custom content list
