<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/order_price_criterion.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\OrderManagement\Value\Order\OrderQuery;

$criteria = new \Ibexa\Contracts\OrderManagement\Value\Order\Query\Criterion\PriceCriterion(
    12900,
    'GTE'
);

$orderQuery = new OrderQuery($criteria);
