<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/order_updated_sort_clause.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\OrderManagement\Value\Order\OrderQuery;

$criteria = null;

$orderQuery = new OrderQuery(
    $criteria,
    [
        new \Ibexa\Contracts\OrderManagement\Value\Order\Query\SortClause\Updated(
            \Ibexa\Contracts\OrderManagement\Value\Order\Query\SortClause\Updated::SORT_ASC
        ),
    ]
);
