ibexa:
    system:
        <scope>:
            connector_raptor:
                enabled:              true
                customer_id:          "12345" # Required
                tracking_type:        client # One of: "client" or "server"

                # Raptor Recommendations API key
                recommendations_api_key: "your_api_key_here" # Required

                # Raptor Recommendations API URI, optional, set by default
                recommendations_api_uri: '%ibexa.connector.raptor.recommendations.api_uri%'
ibexa_connector_raptor:
    # When enabled, tracking exceptions are thrown instead of being silently handled
    strict_exceptions: true
