<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_method_logicalor_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\PaymentMethod\PaymentMethodQuery;
use Ibexa\Contracts\Payment\PaymentMethod\Query\Criterion\CreatedAt;
use Ibexa\Contracts\Payment\PaymentMethod\Query\Criterion\LogicalOr;

$query = new PaymentMethodQuery();
$query->setQuery(new LogicalOr(
    new CreatedAt(new DateTime('2023-03-01')),
    new CreatedAt(new DateTime('2023-05-01')),
));
