<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/payment_method_id_sort_clause.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\PaymentMethod\PaymentMethodQuery;

$criteria = null;

$paymentMethodQuery = new PaymentMethodQuery(
    $criteria,
    [
        new \Ibexa\Contracts\Payment\PaymentMethod\Query\SortClause\Id(
            \Ibexa\Contracts\Payment\PaymentMethod\Query\SortClause\Id::SORT_ASC
        ),
    ]
);
