<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/dateandtimefield.md:92
// (auto-generated by tools/extract-inline-php.php — do not edit)

// DateAndTime FieldType example settings

use Ibexa\Core\FieldType\DateAndTime\Type;

$settings = [
    'useSeconds' => false,
    'defaultType' => Type::DEFAULT_EMPTY,
    'dateInterval' => null,
];
