services:
    App\EventListener\LegalTransitionListener:
        tags:
            - { name: ezplatform.workflow.action_listener }
    App\EventListener\DoneTransitionListener:
        tags:
            - { name: ezplatform.workflow.action_listener }
