services:
    App\EventListener\LegalTransitionListener:
        tags:
            - { name: ezplatform.workflow.action_listener }
    App\EventListener\ApprovedTransitionListener:
        tags:
            - { name: ezplatform.workflow.action_listener }
