services:
    App\Query\Criterion\Solr\CameraManufacturerVisitor:
        tags:
            - { name: ibexa.search.solr.query.content.criterion.visitor }
            - { name: ibexa.search.solr.query.location.criterion.visitor }

    App\Query\Criterion\Elasticsearch\CameraManufacturerVisitor:
        tags:
            - { name: ibexa.search.elasticsearch.query.content.criterion.visitor }
            - { name: ibexa.search.elasticsearch.query.location.criterion.visitor }
