services:
    App\Search\Mapper\WebinarEventTitleFulltextFieldMapper:
        arguments:
            - '@Ibexa\Contracts\Core\Persistence\Content\Handler'
            - '@Ibexa\Contracts\Core\Persistence\Content\Location\Handler'
        tags:
            - {name: ibexa.search.solr.field.mapper.content}
