services:
    App\Query\SortClause\Solr\ScoreVisitor:
        tags:
            - { name: ibexa.search.solr.query.content.sort_clause.visitor }
            - { name: ibexa.search.solr.query.location.sort_clause.visitor }

    App\Query\SortClause\Elasticsearch\ScoreVisitor:
        tags:
            - { name: ibexa.search.elasticsearch.query.content.sort_clause.visitor }
            - { name: ibexa.search.elasticsearch.query.location.sort_clause.visitor }
