<?php

declare(strict_types=1);
// Source: docs/search/search_api.md:109
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Iterator\BatchIterator;
use Ibexa\Contracts\Core\Repository\Iterator\BatchIteratorAdapter;
use Ibexa\Contracts\Core\Repository\SearchService;
use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Symfony\Component\Console\Output\OutputInterface;

$query = new LocationQuery();

/** @var SearchService $searchService */
$iterator = new BatchIterator(new BatchIteratorAdapter\LocationSearchAdapter($searchService, $query));

foreach ($iterator as $result) {
    /** @var OutputInterface $output */
    $output->writeln($result->valueObject->getContentInfo()->name);
}
