<?php

declare(strict_types=1);
// Source: docs/search/search_api.md:400
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Field\IntegerRangeAggregation;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;

$ranges = [
    Range::ofInt(1, 30),
    Range::ofInt(30, 60),
    Range::ofInt(60, null),
];

$query = new LocationQuery();
$query->aggregations[] = new IntegerRangeAggregation('range', 'person', 'age', $ranges);
