<?php

declare(strict_types=1);
// Source: docs/search/search_api.md:46
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\SearchService;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Symfony\Component\Console\Output\OutputInterface;

$contentId = 12345;
$criterion = new Criterion\ContentId($contentId);

/** @var SearchService $searchService */
$result = $searchService->findSingle($criterion);

/** @var OutputInterface $output */
$output->writeln($result->getName() ?? '');
