<?php

declare(strict_types=1);
// Source: docs/search/search_api.md:70
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;

$query = new LocationQuery();
$query->limit = 100;
