<?php

declare(strict_types=1);
// Source: docs/search/search_api.md:319
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion\LocationId;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion\Visibility;

$query = new LocationQuery();
$bLocationId = 12345;
$query->filter = new Criterion\LogicalAnd([
    new LocationId($bLocationId),
    new Visibility(Visibility::VISIBLE),
]);
