<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/baseprice_sort_clause.md:21
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;

/** @var CurrencyInterface $currency */
$sortClauses = [
    new \Ibexa\Contracts\ProductCatalog\Values\Product\Query\SortClause\BasePrice(
        $currency,
        ProductQuery::SORT_ASC
    ),
];
$productQuery = new ProductQuery(null, null, $sortClauses);
