<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/persistence_cache.md:252
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

// Getting the cache service in PHP

/** @var ContainerInterface $container */
$pool = $container->get('ibexa.cache_pool');
/** @var TagAwareAdapterInterface $pool */
