<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/persistence_cache.md:267
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

// Example
/** @var TagAwareAdapterInterface $pool */
/** @var ContainerInterface $container */
/** @var int $id */
$cacheItem = $pool->getItem("myApp-object-{$id}");
if ($cacheItem->isHit()) {
    return $cacheItem->get();
}

$myObject = $container->get('my_app.backend_service')->loadObject($id);
$cacheItem->set($myObject);
$cacheItem->tag(['myApp-category-' . $myObject->categoryId]);
$pool->save($cacheItem);

return $myObject;
