<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/persistence_cache.md:308
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\Cache\Adapter\TagAwareAdapterInterface;

/** @var TagAwareAdapterInterface $pool */
/** @var int $contentId */
// To clear all cache (not recommended without a good reason)
$pool->clear();

// To clear a specific cache item (check source for more examples in Ibexa\Core\Persistence\Cache\*)
$pool->deleteItems(["ibx-ci-$contentId"]);

// Symfony cache is tag-based, so you can clear all cache related to a content item like this:
$pool->invalidateTags(["c-$contentId"]);
