<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/imagefield.md:202
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentCreateStruct $createStruct */
$imageValue = new \Ibexa\Core\FieldType\Image\Value(
    [
        'id' => '/tmp/image.png',
        'fileSize' => 37931,
        'fileName' => 'image.png',
        'alternativeText' => 'My alternative text',
    ]
);

$createStruct->setField('image', $imageValue);
