<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/imagefield.md:153
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Variation\VariationHandler $imageVariationHandler */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Field $imageField */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\VersionInfo $versionInfo */
$variation = $imageVariationHandler->getVariation(
    $imageField,
    $versionInfo,
    'large'
);

echo $variation->uri;
