<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/imagefield.md:173
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
/** @var \Ibexa\Contracts\Core\Repository\ContentTypeService $contentTypeService */
$createStruct = $contentService->newContentCreateStruct(
    $contentTypeService->loadContentTypeByIdentifier('image'),
    'eng-GB'
);

$createStruct->setField('image', '/tmp/image.png');
