framework:
    workflows:
        ibexa_payment:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: method
                property: status
            supports:
                - Ibexa\Contracts\Payment\Payment\Workflow\WorkflowSubjectInterface
            initial_marking: pending
            places:
                pending:
                    metadata:
                        label: ibexa.payment.workflow.place.pending.label
                        primary_color: '#F4B65F'
                        secondary_color: '#FEEED9'
                        translation_domain: ibexa_payment_workflow
                failed:
                    metadata:
                        label: ibexa.payment.workflow.place.failed.label
                        primary_color: '#DB2C54'
                        secondary_color: '#F7CCD6'
                        translation_domain: ibexa_payment_workflow
                paid:
                    metadata:
                        label: ibexa.payment.workflow.place.paid.label
                        primary_color: '#2B6875'
                        secondary_color: '#CCDBDE'
                        translation_domain: ibexa_payment_workflow
                cancelled:
                    metadata:
                        label: ibexa.payment.workflow.place.cancelled.label
                        primary_color: '#5A5A5D'
                        secondary_color: '#E6E6ED'
                        translation_domain: ibexa_payment_workflow
            transitions:
                fail:
                    from:
                        - pending
                    to: failed
                    metadata:
                        exposed: false
                pay:
                    from:
                        - pending
                    to: paid
                    metadata:
                        exposed: false
                cancel:
                    from:
                        - pending
                    to: cancelled
                    metadata:
                        exposed: true
                        label: ibexa.payment.workflow.transition.cancel.label
                        translation_domain: ibexa_payment_workflow