<?php

declare(strict_types=1);
// Source: docs/search/activity_log_search_reference/logged_at_criterion.md:24
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ActivityLog\Values\ActivityLog as ActivityLog;

$query = new ActivityLog\Query([
    new ActivityLog\Criterion\LoggedAtCriterion(new \DateTime('- 1 day'), ActivityLog\Criterion\LoggedAtCriterion::GTE),
]);
