<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/ismainlocation_criterion.md:21
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion\Location\IsMainLocation;

$query = new Query();
$query->query = new Criterion\Location\IsMainLocation(IsMainLocation::MAIN);
