<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/form_and_template.md:72
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\AdminUi\FieldType\FieldDefinitionFormMapperInterface;
use Ibexa\AdminUi\Form\Data\FieldDefinitionData;
use Ibexa\ContentForms\Form\Type\FieldType\CountryFieldType;
use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\FormInterface;

class MyMapper implements FieldDefinitionFormMapperInterface
{
    /** @param FormInterface<mixed> $fieldDefinitionForm */
    public function mapFieldDefinitionForm(FormInterface $fieldDefinitionForm, FieldDefinitionData $data): void
    {
        $fieldDefinitionForm
            ->add(
                'isMultiple',
                CheckboxType::class,
                [
                    'required' => false,
                    'property_path' => 'fieldSettings[isMultiple]',
                    'label' => 'field_definition.ibexa_country.is_multiple',
                ]
            )
            ->add(
                $fieldDefinitionForm->getConfig()->getFormFactory()->createBuilder()
                    ->create(
                        'defaultValue',
                        CountryFieldType::class,
                        [
                            'choices_as_values' => true,
                            'multiple' => true,
                            'expanded' => false,
                            'required' => false,
                            'label' => 'field_definition.ibexa_country.default_value',
                        ]
                    )
                    // Deactivate auto-initialize as you're not on the root form.
                    ->setAutoInitialize(false)->getForm()
            );
    }
}
