<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/form_and_template.md:27
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\ContentForms\Form\Type\FieldType\CheckboxFieldType;
use Ibexa\Contracts\ContentForms\Data\Content\FieldData;
use Ibexa\Contracts\ContentForms\FieldType\FieldValueFormMapperInterface;
use Symfony\Component\Form\FormInterface;

class MyMapper implements FieldValueFormMapperInterface
{
    /** @param FormInterface<mixed> $fieldForm */
    public function mapFieldValueForm(FormInterface $fieldForm, FieldData $data): void
    {
        $fieldDefinition = $data->getFieldDefinition();
        $formConfig = $fieldForm->getConfig();

        $fieldForm
            ->add(
                $formConfig->getFormFactory()->createBuilder()
                    ->create(
                        'value',
                        CheckboxFieldType::class,
                        [
                            'required' => $fieldDefinition->isRequired,
                            'label' => $fieldDefinition->getName(
                                $formConfig->getOption('languageCode')
                            ),
                        ]
                    )
                    ->setAutoInitialize(false)
                    ->getForm()
            );
    }
}
