<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/emailaddressfield.md:39
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example

use Ibexa\Core\FieldType\EmailAddress\Value;

// Instantiates an EmailAddress Value object
$emailaddressValue = new Value('someuser@example.com');
