<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/emailaddressfield.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example

use Ibexa\Core\FieldType\EmailAddress\Value;

// Instantiates an EmailAddress Value object with default value (empty string)
$emailaddressValue = new Value();

// Email definition
$emailaddressValue->email = 'someuser@example.com';
