<?php

declare(strict_types=1);
// Source: docs/templating/urls_and_routes/custom_breadcrumbs.md:50
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;

/** @var \Symfony\Component\HttpFoundation\Request $request */
if ($request->getMethod() != Request::METHOD_POST) {
    throw new NotFoundHttpException();
}
