<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_status_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\Payment\PaymentQuery;

$query = new PaymentQuery(
    new \Ibexa\Contracts\Payment\Payment\Query\Criterion\Status('failed')
);
