services:
    App\EventSubscriber\AuthenticationTokenCreatedSubscriber:
        arguments:
            $userProvider: '@ibexa.security.user_provider.username'
            $userMap:
                from_memory_user: generic_customer
                from_memory_admin: admin
