<?php

declare(strict_types=1);
// Source: docs/content_management/images/configure_image_editor.md:71
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Core\FieldType\Image\Value as FieldValue;

$value = new FieldValue([
     'data' => [
         'width' => '100',
         'height' => '200',
         'alternativeText' => 'test',
         'mime' => 'image/png',
         'id' => 1,
         'fileName' => 'image.png',
         'additionalData' => [
             'focalPointX' => 50,
             'focalPointY' => 100,
             'author' => 'John Smith',
         ],
     ],
 ]);
