<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/matrixfield.md:52
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\FieldTypeMatrix\FieldType;

new FieldType\Value([
    new FieldType\Value\Row(['col1' => 'Row 1, Col 1', 'col2' => 'Row 1, Col 2']),
    new FieldType\Value\Row(['col1' => '', 'col2' => '']),
    new FieldType\Value\Row(['col1' => 'Row 3, Col 1', 'col2' => 'Row 3, Col 2']),
]);
