<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/creating_content.md:107
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\VersionInfo $versionInfo */
$languageCode = 'ger-DE';
/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
$contentService->deleteTranslationFromDraft($versionInfo, $languageCode);
