<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/mediafield.md:75
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of using Media field type validator in PHP

use Ibexa\Core\FieldType\Media\Type;

/** @var \Ibexa\Contracts\Core\Repository\Repository $repository */
$contentTypeService = $repository->getContentTypeService();
$mediaFieldCreateStruct = $contentTypeService->newFieldDefinitionCreateStruct('media', 'ibexa_media');

// Setting maximum file size to 5 megabytes
$mediaFieldCreateStruct->validatorConfiguration = [
    'FileSizeValidator' => [
        'maxFileSize' => 5 * 1024 * 1024,
    ],
];
