<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/mediafield.md:112
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of using Media field type settings in PHP

use Ibexa\Core\FieldType\Media\Type;

/** @var \Ibexa\Contracts\Core\Repository\Repository $repository */
$contentTypeService = $repository->getContentTypeService();
$mediaFieldCreateStruct = $contentTypeService->newFieldDefinitionCreateStruct('media', 'ibexa_media');

// Setting Adobe Flash as the media type
$mediaFieldCreateStruct->fieldSettings = [
    'mediaType' => Type::TYPE_FLASH,
];
