<?php

declare(strict_types=1);
// Source: docs/ai/ai_actions/configure_ai_actions.md:109
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // ...
    Ibexa\Bundle\ConnectorGemini\IbexaConnectorGeminiBundle::class => ['all' => true],
];
