security:
    #…

    firewalls:
        #…

        # Uncomment ibexa_oauth2_connect, ibexa_oauth2_front rules and comment ibexa_front firewall
        # to enable OAuth2 authentication

        ibexa_oauth2_connect:
            pattern: /oauth2/connect/*
            security: false

        ibexa_oauth2_front:
            pattern: ^/
            provider: ibexa
            user_checker: Ibexa\Core\MVC\Symfony\Security\UserChecker
            custom_authenticators:
              - Ibexa\Bundle\OAuth2Client\Security\Authenticator\OAuth2Authenticator
              - Ibexa\PageBuilder\Security\EditorialMode\FragmentAuthenticator
            entry_point: Ibexa\Bundle\OAuth2Client\Security\Authenticator\OAuth2Authenticator
            context: ibexa
            form_login:
                enable_csrf: true
            logout: ~

        # ibexa_front:
        #     pattern: ^/
        #     provider: ibexa
        #     user_checker: Ibexa\Core\MVC\Symfony\Security\UserChecker
        #     context: ibexa
        #     form_login:
        #         enable_csrf: true
        #         login_path: login
        #         check_path: login_check
        #     custom_authenticators:
        #         - Ibexa\PageBuilder\Security\EditorialMode\FragmentAuthenticator
        #     entry_point: form_login
        #     logout:
        #         path: logout
