services:
    app.custom_content_edit_tab:
        parent: Ibexa\AdminUi\Component\TwigComponent
        arguments:
            $template: '@@ibexadesign/content_type/edit/custom_tab.html.twig'
        tags:
            - { name: ibexa.twig.component, group: 'admin-ui-content-edit-sections' }
