<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/userlogin_sort_clause.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\SortClause;

$query = new Query();
$query->sortClauses = [new SortClause\Trash\UserLogin()];
