<?php

declare(strict_types=1);
// Source: docs/update_and_migration/from_4.6/update_to_5.0.md:54
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Rector\Sets\IbexaSetList;
use Rector\Config\RectorConfig;

return RectorConfig::configure()
    ->withPaths(
        [
           __DIR__ . '/src',
        ]
    )
    ->withSets(
        [
           IbexaSetList::IBEXA_46->value,
        ]
    )
    ->withPhpSets(php83: true)
    ->withComposerBased(symfony: true)
;
