<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/managing_content.md:120
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\TrashItem $trashItem */
/** @var \Ibexa\Contracts\Core\Repository\LocationService $locationService */
/** @var \Ibexa\Contracts\Core\Repository\TrashService $trashService */
$locationId = 12345;
$newParent = $locationService->loadLocation($locationId);
$trashService->recover($trashItem, $newParent);
