<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/languagecode_criterion.md:54
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new LocationQuery();
$query->query = new Criterion\LogicalAnd(
    [
    new Criterion\ContentTypeIdentifier('article'),
    new Criterion\LogicalNot(
        new Criterion\LanguageCode('ger-DE', false)
    ),
    ]
);

/** @var \Ibexa\Contracts\Core\Repository\SearchService $searchService */
$results = $searchService->findContent($query);
$articlesToTranslate = [];
foreach ($results->searchHits as $searchHit) {
    $articlesToTranslate[] = $searchHit;
}

return $articlesToTranslate;
