<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/imagemimetype_criterion.md:29
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$mimeTypes = [
    'image/jpeg',
    'image/png',
];

$query->query = new Criterion\Image\MimeType('image', $mimeTypes);
