<?php

declare(strict_types=1);
// Source: docs/tutorials/beginner_tutorial/7_embed_content.md:127
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\Controller;

use Ibexa\Bundle\Core\Controller;
use Ibexa\Contracts\Core\Repository\ContentService;
use Ibexa\Core\MVC\Symfony\View\ContentView;

class RideController extends Controller
{
    public function __construct(private readonly ContentService $contentService)
    {
    }

    public function viewRideWithLandmarksAction(ContentView $view): ContentView
    {
        $currentContent = $view->getContent();
        $landmarksListId = $currentContent->getFieldValue('landmarks');
        $landmarksList = [];

        foreach ($landmarksListId->destinationContentIds as $landmarkId) {
            $landmarksList[$landmarkId] = $this->contentService->loadContent($landmarkId);
        }

        $view->addParameters(['landmarksList' => $landmarksList]);

        return $view;
    }
}
