<?php

declare(strict_types=1);
// Source: docs/commerce/shopping_list/shopping_list_api.md:44
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ShoppingList\ShoppingListServiceInterface;
use Ibexa\Contracts\ShoppingList\Value\ShoppingListQuery;

/** @var ShoppingListServiceInterface $shoppingListService */
$lists = $shoppingListService->findShoppingLists(new ShoppingListQuery());
