<?php

declare(strict_types=1);
// Source: docs/commerce/shopping_list/shopping_list_api.md:64
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ShoppingList\ShoppingListServiceInterface;
use Ibexa\Contracts\ShoppingList\Value\EntryAddStruct;

/** @var ShoppingListServiceInterface $shoppingListService */
/** @var string $productCode */
$list = $shoppingListService->getOrCreateDefaultShoppingList();
dump($list);
$list = $shoppingListService->clearShoppingList($list);
dump($list);
$list = $shoppingListService->addEntries($list, [new EntryAddStruct($productCode)]);
dump($list);
