<?php

declare(strict_types=1);
// Source: docs/search/shopping_list_search_reference/shopping_list_criteria.md:27
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ShoppingList\Value\ShoppingListQuery;

$query = new ShoppingListQuery();
