<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/integerrange_aggregation.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;

$query = new Query();
$query->aggregations[] = new Aggregation\Field\IntegerRangeAggregation(
    'integer',
    'product',
    'amount',
    [
    Range::ofInt(null, 12),
    Range::ofInt(12, 24),
    Range::ofInt(24, null),
]
);
