ezplatform:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags: [factbox]
                    toolbars:
                        ezadd:
                            buttons:
                                factbox:
                                    priority: 5
                        factbox:
                            buttons:
                                ezmoveup:
                                    priority: 40
                                ezmovedown:
                                    priority: 30
                                ezcustomtagedit:
                                    priority: 20
                                ezblockremove:
                                    priority: 10
ezrichtext:
    custom_tags:
        factbox:
            template: '@ezdesign/field_type/ezrichtext/custom_tags/factbox.html.twig'
            icon: '/bundles/ezplatformadminui/img/ez-icons.svg#information'
            attributes:
                name:
                    type: string
                    required: true
                style:
                    type: choice
                    required: true
                    default_value: light
                    choices: [light, dark]
