ibexa_fieldtype_richtext:
    custom_tags:
        factbox:
            template: '@ibexadesign/field_type/ezrichtext/custom_tags/factbox.html.twig'
            icon: '/bundles/ibexaicons/img/all-icons.svg#information' # Optional
            is_inline: false # Optional
            label: 'Factbox custom tag' # Optional
            description: 'Highlight a piece of information in a box' # Optional
            attributes:
                name:
                    type: string
                    required: true # Optional
                    label: 'My name attribute' # Optional
                style:
                    type: choice
                    required: true # Optional
                    default_value: light
                    choices: [light, dark]
                    label: 'My style attribute' # Optional

ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_tags: [factbox]
                    toolbar:
                        custom_tags_group:
                            buttons:
                                factbox:
                                    priority: 5
