<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/taxonomyentryassignmentfield.md:46
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Taxonomy\Value\TaxonomyEntry;

/** @var TaxonomyEntry $taxonomyEntry */
/** @var TaxonomyEntry $taxonomyEntry2 */
return [
    'taxonomy_entries' => [$taxonomyEntry, $taxonomyEntry2], // load entries using TaxonomyService
    'taxonomy' => 'tags',
];
