<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/taxonomyentryassignmentfield.md:28
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Taxonomy\Service\TaxonomyServiceInterface;

/** @var TaxonomyServiceInterface $taxonomyService */
$taxonomyEntry1 = $taxonomyService->loadEntryByIdentifier('example_entry', 'tags');
$taxonomyEntry2 = $taxonomyService->loadEntryByIdentifier('example_entry_2', 'tags');
new \Ibexa\Taxonomy\FieldType\TaxonomyEntryAssignment\Value(
    [
        $taxonomyEntry1,
        $taxonomyEntry2,
        // ...
    ],
    'tags',
);
