<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/customprice_sort_clause.md:23
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface;
use Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;

/** @var CurrencyInterface $currency */
/** @var CustomerGroupInterface $customerGroup */
$sortClauses = [
    new \Ibexa\Contracts\ProductCatalog\Values\Product\Query\SortClause\CustomPrice(
        $currency,
        ProductQuery::SORT_ASC,
        $customerGroup
    ),
];
$productQuery = new ProductQuery(null, null, $sortClauses);
