<?php

declare(strict_types=1);
// Source: docs/search/url_search_reference/id_url_sort_clause.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\URL\Query\SortClause;
use Ibexa\Contracts\Core\Repository\Values\URL\URLQuery;

// ...

$query = new URLQuery();
$query->sortClauses = [new SortClause\Id()];
