<?php

declare(strict_types=1);
// Source: docs/content_management/url_management/url_management.md:228
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Repository $repository */
$source = 'pictures/*/*';
$destination = 'media/images/{1}/{2}';
$redirect = true;

$urlWildcardService = $repository->getURLWildcardService();
$repository->sudo(static function ($repository) use ($urlWildcardService, $source, $destination, $redirect): void {
    $urlWildcardService->create($source, $destination, $redirect);
});
