<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/shipment_updatedat_criterion.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\Shipping\Shipment\ShipmentQuery;

$criteria = new \Ibexa\Contracts\Shipping\Shipment\Query\Criterion\UpdatedAt(
    new DateTime('2023-03-01'),
    'GTE'
);

$query = new ShipmentQuery($criteria);
