<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/timefield.md:74
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Time field type example settings
use Ibexa\Core\FieldType\Time\Type;

$settings = [
    'defaultType' => Type::DEFAULT_EMPTY,
];
