get:
    displayName: List Trash items
    description: Returns a list of all items in the Trash.
    queryParameters:
        limit:
            description: Only limit. Items will be returned, starting with the offset.
        offset:
            description: Offset of the result set.
    headers:
        Accept:
            description: If set, the Trash item list is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.Trash+xml
                application/vnd.ibexa.api.Trash+json
    responses:
        200:
            description: OK - returns the list of items in the Trash.
            body:
                application/vnd.ibexa.api.Trash+xml:
                    type: Trash
                    example: !include examples/content/trash/GET/Trash.xml.example
                application/vnd.ibexa.api.Trash+json:
                    type: Trash
                    example: !include examples/content/trash/GET/Trash.json.example
        401:
            description: Error - The user has no permission to read the Trash.
delete:
    displayName: Empty Trash
    description: Empties the Trash.
    responses:
        204:
            description: No Content - Trash emptied.
        401:
            description: Error - The user is not authorized to empty all items from Trash.
/{trashItemid}:
    get:
        displayName: Get Trash item
        description: Returns the item in Trash with the provided ID.
        headers:
            Accept:
                description: If set, the item in Trash is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.TrashItem+xml
                    application/vnd.ibexa.api.TrashItem+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.TrashItem+xml:
                        type: TrashItem
                        example: !include examples/content/trash/trash_itemid/GET/TrashItem.xml.example
                    application/vnd.ibexa.api.TrashItem+json:
                        type: TrashItem
                        example: !include examples/content/trash/trash_itemid/GET/TrashItem.json.example
            401:
                description: Error - The user has no permission to read the item in Trash.
            404:
                description: Error - An item in Trash with the provided ID does not exist.
    move:
        displayName: Untrash Content item
        description: Restores an item from Trash. MOVE or POST with header X-HTTP-Method-Override MOVE.
        headers:
            Destination:
                description: If the destination Location URI is provided, the item from Trash is restored under this Location, otherwise it is restored under its original parent Location.
        responses:
            201:
                description: Item restored.
            401:
                description: Error - The user is not authorized to restore this item from Trash.
            403:
                description: Error - The provided parent Location does not exist.
            404:
                description: Error - The provided item does not exist in Trash.
    delete:
        displayName: Delete Trash item
        description: Deletes the provided item from Trash.
        responses:
            204:
                description: No Content - item deleted.
            401:
                description: Error - The user is not authorized to delete the provided item.
            404:
                description: Error - The provided item does not exist in Trash.
