displayName: eCommerce API

/basket:
    get:
        displayName: Read list of baskets
        description: |
            Returns baskets for the current user. Only "storedBasket" and "wishList" types are handled. Others will return validation error.
        queryParameters:
            type:
                description: Either "storedBasket" or "wishList". "storedBasket" is assumed if not passed.
        responses:
            200:
                body:
                    application/vnd.ez.api.BasketListResponse+json:
                        type: BasketListResponse
                        example: !include examples/commerce/basket/headers/GET/BasketListResponse.json.example
            400:
                body:
                    application/vnd.ez.api.ValidationResponse:
                        type: ValidationResponse

    /current:
        get:
            displayName: Get current basket
            description: |
                Returns a Basket instance for the current session. If there isn't one, a new one will be created.
            headers:
                Accept:
                    example: application/vnd.ez.api.Basket+json
            responses:
                200:
                    body:
                        application/vnd.ez.api.Basket+json:
                            type: Basket
                            example: !include examples/commerce/basket/Basket.json.example

        /{basketId}:
            copy:
                displayName: Copy basket to user session
                description: |-
                    Adds basket lines into current basket in user session, if any, using basket stored in permanent
                    storage.
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse
                                example: !include examples/commerce/basket/current/copyfrom/_basket_id_/POST/ValidationResponse.json.example

        /referencenumber:
            patch:
                displayName: Save the external reference number in basket

        /remark:
            patch:
                displayName: Save the remark in basket

        /party/{partyType}:
            patch:
                displayName: Update party information in the basket
                description: Updates party (buyer, delivery, invoice) information in the basket.
                body:
                    application/vnd.ez.api.PartyInvoice+json:
                        type: PartyTypeInput
                        example: !include examples/commerce/basket/current/party/invoice/PATCH/PartyInvoice.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse

        /shippingmethod:
            patch:
                displayName: Update shipping information in current basket
                description: Updates shipping information in the current basket.
                body:
                    application/vnd.ez.api.ShippingMethodData+json:
                        type: ShippingMethodData
                        example: !include examples/commerce/basket/current/shippingmethod/PATCH/ShippingMethodData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse

        /paymentmethod:
            patch:
                displayName: Update payment information in current basket
                description: Updates payment information in the current basket.
                body:
                    application/vnd.ez.api.PaymentMethodData.json:
                        type: PaymentMethodData
                        example: !include examples/commerce/basket/current/paymentmethod/PATCH/PaymentMethodData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse

        /voucher:
            patch:
                displayName: Update and check voucher in current basket
                description: Updates and checks voucher in current basket.
                body:
                    application/vnd.ez.api.VoucherData.json:
                        type: VoucherData
                        example: !include examples/commerce/basket/current/voucher/PATCH/VoucherData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse

        /line:
            post:
                displayName: Add products to current basket
                description: Adds products to the current basket.
                body:
                    application/vnd.ez.api.BasketLineData+json:
                        type: BasketLineData
                        example: !include examples/commerce/basket/current/lines/POST/BasketLineData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example
                    400:
                        body:
                            application/vnd.ez.api.ValidationResponse+json:
                                type: ValidationResponse
                                example: !include examples/commerce/basket/current/lines/POST/ValidationResponse.json.example

    /{basketId}:
        get:
            displayName: Get Basket by ID
            description: Gets basket by ID.
            responses:
                200:
                    body:
                        application/vnd.ez.api.Basket+json:
                            type: Basket
                            example: !include examples/commerce/basket/_id_/GET/Basket.json.example

        /name:
            patch:
                displayName: Update the name of the stored basket
                description: |
                    Updates the name of the stored basket.
                body:
                    application/vnd.ez.api.BasketHeaderData+json:
                        type: BasketHeaderData
                        example: !include examples/commerce/basket/_id_/_mode_/POST/BasketHeaderData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example

        /note:
            patch:
                displayName: Update the note of the stored basket
                description: |
                    Updates the note of the stored basket.
                body:
                    application/vnd.ez.api.BasketHeaderData+json:
                        type: BasketHeaderData
                        example: !include examples/commerce/basket/_id_/_mode_/POST/BasketHeaderData.json.example
                responses:
                    200:
                        body:
                            application/vnd.ez.api.Basket+json:
                                type: Basket
                                example: !include examples/commerce/basket/Basket.json.example

        /{basketId}:
            /line:
                post:
                    displayName: Add products to stored basket
                    description: Adds products to the stored basket.
                    body:
                        application/vnd.ez.api.BasketLineData+json:
                            type: BasketLineData
                            example: !include examples/commerce/basket/current/lines/POST/BasketLineData.json.example
                    responses:
                        200:
                            body:
                                application/vnd.ez.api.Basket+json:
                                    type: Basket
                                    example: !include examples/commerce/basket/Basket.json.example
                        400:
                            body:
                                application/vnd.ez.api.ValidationResponse+json:
                                    type: ValidationResponse
                                    example: !include examples/commerce/basket/current/lines/POST/ValidationResponse.json.example

            /line/{lineId}:
                delete:
                    displayName: Delete a line from a stored basket
                    responses:
                        200:
                            body:
                                application/vnd.ez.api.Basket+json:
                                    type: Basket
                                    example: !include examples/commerce/basket/Basket.json.example
                        400:
                            body:
                                application/vnd.ez.api.ValidationResponse+json:
                                    type: ValidationResponse
                                    example: !include examples/commerce/basket/_id_/line/_line_id_/DELETE/ValidationResponse.json.example

    /{basketName}:
        post:
            displayName: Create a new persisted basket
            description: Creates a new persisted basket.
            responses:
                200:
                    body:
                        application/vnd.ez.api.Basket+json:
                            type: Basket
                            example: !include examples/commerce/basket/Basket.json.example
                400:
                    body:
                        application/vnd.ez.api.ValidationResponse+json:
                            type: ValidationResponse
                            example: !include examples/commerce/basket/POST/ValidationResponse.json.example

/checkout:
    /paymentmethods:
        get:
            displayName: Get list of payment methods
            responses:
                200:
                    body:
                        application/vnd.ez.api.PaymentMethodDataResponse+json:
                            type: PaymentMethodDataResponse
                            example: !include examples/commerce/checkout/payment-methods/GET/PaymentMethodDataResponse.json.example

    /shippingmethods:
        get:
            displayName: Get list of shipping methods
            responses:
                200:
                    body:
                        application/vnd.ez.api.ShippingMethodDataResponse+json:
                            type: ShippingMethodDataResponse
                            example: !include examples/commerce/checkout/shipping-methods/GET/ShippingMethodDataResponse.json.example

/customer/addresses/shipping:
    get:
        displayName: Get list of shipping addresses
        responses:
            200:
                body:
                    application/json:
                        type: ShippingAddressesResponse
                        example: !include examples/commerce/customer/addresses/shipping/GET/ShippingAddressesResponse.json.example

/customerprice:
    post:
        displayName: Get customer prices for products
        description: Gets customer prices for the requested products.
        body:
            application/json:
                type: CustomerPriceData
                example: !include examples/commerce/customerprice/POST/CustomerPriceData.json.example
        responses:
            200:
                body:
                    application/json:
                        type: PriceResponse
                        example: !include examples/commerce/customerprice/POST/PriceResponse.json.example


/common/check_sku_file:/{mode}:
    post:
        displayName: Add to basket from CSV or Excel
        description: Adds to basket a line from a CSV or Excel file.

/country:
    get:
        displayName: Gets list of countries.
        responses:
            200:
                body:
                    application/json:
                        type: CountrySelectionResponse
                        example: !include examples/commerce/country-selection/GET/CountrySelectionResponse.json.example
