post:
    displayName: Create Attribute Group
    description: Creates a new Attribute Group.
    headers:
        Accept:
            description: If set, the new Attribute Group is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.AttributeGroupCreate+json
        Content-Type:
            description: The AttributeGroup schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.AttributeGroupCreate+json
    body:
        application/vnd.ibexa.api.AttributeGroupCreate+json:
            type: AttributeGroupCreate
            example: !include examples/product/catalog/attribute_groups/POST/AttributeGroupCreate.json.example
    responses:
        201:
            body:
                application/vnd.ibexa.api.AttributeGroup+json:
                    type: AttributeGroup
                    example: !include examples/product/catalog/attribute_groups/POST/AttributeGroup.json.example
        400:
            description: Error - the input does not match the input schema definition.
        401:
            description: Error - the user is not authorized to create this Attribute Group.
        403:
            description: Error - an Attribute Group.
/{id}:
    patch:
        displayName: Update Attribute Group
        description: Updates Attribute Group.
        headers:
            Accept:
                description: If set, the updated Attribute Group is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeGroupUpdate+json
            Content-Type:
                description: If set, the updated Attribute Group is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeGroupUpdate+json
        body:
            application/vnd.ibexa.api.AttributeGroup+json:
                type: AttributeGroupUpdate
                example: !include examples/product/catalog/attribute_groups/attribute_groups_id/PATCH/AttributeGroupUpdate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.AttributeGroup+json:
                        type: AttributeGroup
                        example: !include examples/product/catalog/attribute_groups/attribute_groups_id/PATCH/AttributeGroup.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to create this AttributeGroup.
            403:
                description: Error - an Attribute Group with the same login already exists.
            404:
                description: Error - the Group with the given ID does not exist.
delete:
    displayName: Delete Attribute Group
    description: The given Attribute Group is deleted.
    responses:
        204:
            description: No content - the given Attribute Group is deleted.
        401:
            description: Error - the user is not authorized to delete this Content Type.
/translation/{id}/{languageCode}:
    delete:
        displayName: Delete Translation
        description: Deletes given Translation from Attribute Group.
        responses:
            200:
                description: No content - the given Attribute Group Translation is deleted.
            401:
                description: Error - the user is not authorized to delete this Attribute Group Translation assignment.
get:
    displayName: Load Attribute Groups
    description: Returns a list of Attribute Groups.
    headers:
        Accept:
            description: AttributeGroupListGet - If set, the Attribue Group List is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.AttributeGroupListGet+json
        Content-Type:
            description: The AttributeGroupList schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.AttributeGroupListGet+json
    responses:
        200:
            body:
                application/vnd.ibexa.api.AttributeGroupList+json:
                    type: AttributeGroupList
                    example: !include examples/product/catalog/attribute_groups/GET/AttributeGroupList.json.example
        401:
            description: Error - the user has no permission to read Attribute Groups.

    /id:
        displayName: Load Attribute Group
        description: Returns a list of given Attribute Group.
        headers:
            Accept:
                description: AttributeGrouptGet - If set, the Attribute Group List is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.AttributeGroupGet+json
            Content-Type:
                description: The AttributeGroup schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeGroupGet+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.AttributeGroupList+json:
                        type: AttributeGroupList
                        example: !include examples/product/catalog/attribute_groups/attribute_groups_id/GET/AttributeGroup.json.example
            401:
                description: Error - the user has no permission to read Attribute Groups.
