/{productTypeIdentifier}:
    post:
        displayName: Create product
        description: Creates a new product.
        headers:
            Accept:
                description: If set, the new product is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductCreate+json
            Content-Type:
                description: The product schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductCreate+json
        body:
            application/vnd.ibexa.api.ProductCreate+json:
                type: ProductCreate
                example: !include examples/product/catalog/product/POST/ProductCreate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.ProductCreate+json:
                        type: Product
                        example: !include examples/product/catalog/product/code/GET/Product.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to update this product.
            403:
                description: Error - a product with the same name already exists.
            404:
                description: Error - no product with the given code exists.
/{identifier}:
    delete:
        displayName: Delete product
        description: Deletes the given product.
        responses:
            204:
                description: No content - the given product is deleted.
            401:
                description: Error - the user is not authorized to delete this product.
/{code}:
    get:
        displayName: Load product
        description: Loads the given product.
        headers:
            Accept:
                description: If set, the products are returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductGet+json
            Content-Type:
                description: The product schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductGet+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.Product+json:
                        type: Product
                        example: !include examples/product/catalog/product/code/GET/Product.json.example
            401:
                description: Error - the user is not authorized to view this product.
            404:
                description: Error - no product with the given code exists.
    patch:
        displayName: Update product
        description: Updates product.
        headers:
            Accept:
                description: If set, the updated product is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductUpdate+json
            Content-Type:
                description: If set, the updated product is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductUpdate+json
        body:
            application/vnd.ibexa.api.ProductUpdate+json:
                type: ProductUpdate
                example: !include examples/product/catalog/product/code/PATCH/ProductUpdate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.Product+json:
                        type: ProductUpdate
                        example: !include examples/product/catalog/product/code/PATCH/Product.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to create this product.
            403:
                description: Error - a product with the same code already exists.
            404:
                description: Error - no product with the given code exists.
get:
    displayName: Load products list
    description: Returns a list of products.
    headers:
        Accept:
            description: If set, the products are returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductListGet+json
        Content-Type:
            description: The product list schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductListGet+json
    body:
        application/vnd.ibexa.api.ProductListGet+json:
            type: ProductListGet
            example: !include examples/product/catalog/product/GET/ProductListGet.json.example
    responses:
        200:
            body:
                application/vnd.ibexa.api.Product+json:
                    type: ProductList
                    example: !include examples/product/catalog/product/GET/ProductList.json.example
        401:
            description: Error - the user has no permission to read product.
/view:
    post:
        displayName: Filter products
        description: Executes a query and returns a View including the results. The View input reflects the criteria model of the public API.
        headers:
            Accept:
                description: The view in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductView+xml
                    application/vnd.ibexa.api.ProductView+json
            Content-Type:
                description: The view input in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductViewInput+xml
                    application/vnd.ibexa.api.ProductViewInput+json
        body:
            application/vnd.ibexa.api.ProductViewInput+json:
                type: ProductViewInput
                example: !include examples/product/catalog/product/POST/ProductViewInput.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ProductView+json;
                        type: ProductView
                        example: !include examples/product/catalog/product/POST/ProductView.json.example
            400:
                description: Error - the input does not match the input schema definition.
