post:
    displayName: Create Product
    description: Creates a new Product.
    headers:
        Accept:
            description: If set, the new Product is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductCreate+json
        Content-Type:
            description: The Product schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductCreate+json
    body:
        application/vnd.ibexa.api.ProductCreate+json:
            type: ProductCreate
            example: !include examples/product/catalog/product/POST/ProductCreate.json.example
    responses:
        201:
            body:
                application/vnd.ibexa.api.ProductC+json:
                    type: Product
                    example: !include examples/product/catalog/product/POST/ProductCreate.json.example
        400:
            description: Error - the input does not match the input schema definition.
        401:
            description: Error - the user is not authorized to update this Product.
        403:
            description: Error - a Prodcut with the same name already exists.
        404:
            description: Error - the Product with the given ID does not exist.
patch:
    displayName: Update Product
    description: Updates Product.
    headers:
        Accept:
            description: If set, the updated Product is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductUpdate+json
        Content-Type:
            description: If set, the updated Product is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductUpdate+json
    body:
        application/vnd.ibexa.api.ProductUpdate+json:
            type: ProductUpdate
            example: !include examples/product/catalog/product/id/PATCH/ProductUpdate.json.example
    responses:
        201:
            body:
                application/vnd.ibexa.api.Product+json:
                    type: ProductUpdate
                    example: !include examples/product/catalog/product/id/PATCH/Product.json.example
        400:
            description: Error - the input does not match the input schema definition.
        401:
            description: Error - the user is not authorized to create this User.
        403:
            description: Error - a User with the same login already exists.
        404:
            description: Error - the Product with the given ID does not exist.
/{id}:
    delete:
        displayName: Delete Product
        description: Deletes the given Product.
        responses:
            204:
                description: No content - the given Product is deleted.
            401:
                description: Error - the user is not authorized to delete this Product.
get:
    displayName: Load Products List
    description: Returns a list of Products.
    headers:
        Accept:
            description: If set, the given Product is returned in XML or JSON format.
                application/vnd.ibexa.api.ProductGet+json
        Content-Type:
            description: The Product schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductGet+json
    responses:
        200:
            body:
                application/vnd.ibexa.api.Product+json:
                    type: ProductList
                    example: !include examples/product/catalog/product/id/GET/Product.json.example
        401:
            description: Error - the user has no permission to read Product.
