get:
    displayName: Load Regions
    description: Loads the list of Regions.
    headers:
        Accept:
            description: RegionList - If set, the Regions list returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.RegionGetList+json
    responses:
        200:
            description: OK - loads Regions.
            body:
                application/vnd.ibexa.api.RegionListGet+json:
                    type: RegionList
                    example: !include examples/product/catalog/regions/GET/RegionList.json.example
        401:
            description: Error - the user has no permission to read Regions.
        404:
            description: Error - the Region does not exist.