displayName: content/binary/name
/binary/images/{imageId}/variations/{variationIdentifier}:
    get:
        displayName: Load an image variation
        description: Loads an image variation.
        headers:
            Accept:
                description: If set, the image is returned in XML or JSON format.
                example:  |
                    application/vnd.ez.api.ImageVariation+xml
                    application/vnd.ez.api.ImageVariation+json
        responses:
            200:
                body:
                    application/vnd.ez.api.ImageVariation+xml:
                        type: ContentImageVariation
                        example: !include examples/content/binary/images/image_id/variations/variation_identifier/GET/ImageVariation.xml.example
            401:
                description: Error - the user is not authorized to read this Content item.
            404:
                description: Error - image ID doesn't match any image or variationIdentifier doesn't match any known variation.
