<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_search.md:25
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Search;

return [
    'url' => new Search\FieldType\StringField(),
    'text' => new Search\FieldType\StringField(),
];
