<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationlistfield.md:100
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of using settings and validators configuration in PHP

use Ibexa\Core\FieldType\RelationList\Type;

$fieldSettings = [
    'selectionMethod' => Type::SELECTION_BROWSE,
    'selectionDefaultLocation' => null,
    'selectionContentTypes' => [],
 ];

$validators = [
    'RelationListValueValidator' => [
        'selectionLimit' => 0,
    ],
];
