<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationlistfield.md:31
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example
/** @var \Ibexa\Core\FieldType\RelationList\Value $relationList */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo1 */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo2 */
$relationList->destinationContentIds = [
    $contentInfo1->id,
    $contentInfo2->id,
    170,
];
