<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/relationlistfield.md:48
// (auto-generated by tools/extract-inline-php.php — do not edit)

//Constructor example
use Ibexa\Core\FieldType\RelationList as RelationList;

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo1 */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo2 */
// Instantiates a RelationList Value object
$relationListValue = new RelationList\Value(
    [
        $contentInfo1->id,
        $contentInfo2->id,
        170,
    ]
);
