<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/rangemeasurementattributemaximum_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;

/** @var \Ibexa\Contracts\Measurement\MeasurementServiceInterface $measurementService */
$value = $measurementService->buildSimpleValue('length', 150, 'centimeter');

$query = new ProductQuery(
    null,
    new \Ibexa\Contracts\Measurement\Product\Query\Criterion\RangeMeasurementAttributeMaximum(
        'length',
        $value
    )
);
