
                        type: ShippingMethodRefList
                        type: ShippingMethodRefListWrapper
                            type: ShippingMethod
                            type: ShippingMethodWrapper

                        type: ShippingMethodTypesList
                        type: ShippingMethodTypesListWrapper

                            type: ShippingMethodType
                            type: ShippingMethodTypeWrapper