
                type: OrderCreateWrapper
                        type: OrderWrapper
                        type: OrderList
                        type: OrderListWrapper
                            type: Order
                            type: OrderWrapper
                                type: ShipmentRefList
                                type: ShipmentRefListWrapper
                        type: ShipmentCreate
                        type: ShipmentCreateWrapper
                                type: Shipment
                                type: ShipmentWrapper

                            type: Order
                            type: OrderWrapper
                    type: OrderUpdateWrapper
                            type: OrderWrapper
