                    type: SegmentGroupList
                    type: SegmentGroupListWrapper
                    type: ErrorMessage
                    type: ErrorMessage
                        type: SegmentGroup
                        type: SegmentGroupWrapper
                            type: SegmentList
                            type: SegmentListWrapper
