
                    type: ShipmentRefList
                    type: ShipmentRefListWrapper

                        type: Shipment
                        type: ShipmentWrapper

                type: ShipmentUpdate
                type: ShipmentUpdateWrapper
                        type: Shipment
                        type: ShipmentWrapper
