<?php

declare(strict_types=1);
// Source: docs/commerce/transactional_emails/extend_transactional_emails.md:135
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\EventSubscriber;

use Ibexa\ConnectorActito\Campaign\Campaign;
use Ibexa\Contracts\ConnectorActito\Event\ResolveCampaignEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

final class ResolveCampaginEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            ResolveCampaignEvent::class => 'onCampaignResolve',
        ];
    }

    public function onCampaignResolve(ResolveCampaignEvent $event): void
    {
        // you can use below data in your logic
        $resolvedCampaign = $event->getCampaign();
        $recipient = $event->getRecipient();
        $notification = $event->getNotification();

        // when new campaign was determined, set it to the event
        $campaign = new Campaign('new_order_created_12-2023_en-US');
        $event->setCampaign($campaign);
    }
}
