<?php

declare(strict_types=1);
// Source: docs/commerce/transactional_emails/extend_transactional_emails.md:80
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\EventSubscriber;

use Ibexa\Contracts\ConnectorActito\Client\TransactionalMail\Attribute;
use Ibexa\Contracts\ConnectorActito\Client\TransactionalMail\Segmentation;
use Ibexa\Contracts\ConnectorActito\Event\TransactionalMailRequest\ProfileFactoryEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

final class TransactionalMailFactoryEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            ProfileFactoryEvent::class => 'onProfileFactoryEvent',
        ];
    }

    public function onProfileFactoryEvent(ProfileFactoryEvent $event): void
    {
        $recipient = $event->getRecipient();
        $profile = $event->getProfile();
        $user = $recipient->getUser();

        // Provide additional data if your profile has more attributes:
        $attributes = $profile->getAttributes();
        $attributes[] = new Attribute('name', $user->getName());
        $profile->setAttributes($attributes);

        // Passing segmentation data to the profile
        $segmentations = [
            new Segmentation(
                'Frequent visitors',
                'storefront_users',
                true,
            ),
        ];
        $profile->setSegmentations($segmentations);

        // Use the same mechanism to pass other profile data
        // $profile->setSubscriptions($subscriptions);
        // $profile->setDataCollection($dataCollection);
    }
}
