<?php

declare(strict_types=1);
// Source: docs/commerce/transactional_emails/extend_transactional_emails.md:34
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\EventSubscriber;

use Ibexa\Contracts\ConnectorActito\Client\TransactionalMail\SimpleParameter;
use Ibexa\Contracts\ConnectorActito\Event\TransactionalMailRequest\ParametersFactoryEvent;
use Symfony\Component\EventDispatcher\EventSubscriberInterface;

final class TransactionalMailFactoryEventSubscriber implements EventSubscriberInterface
{
    public static function getSubscribedEvents(): array
    {
        return [
            ParametersFactoryEvent::class => 'onParametersFactoryEvent',
        ];
    }

    public function onParametersFactoryEvent(ParametersFactoryEvent $event): void
    {
        $event->addParameter(
            new SimpleParameter(
                'newVariable',
                ['value'],
            ),
        );

        $event->addParameter(
            new SimpleParameter(
                'anotherVariable',
                ['multiple', 'values'],
            ),
        );
    }
}
