<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/contenttypegroupid_criterion.md:53
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\SearchService;
use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\ContentTypeGroupId([3]);

/** @var SearchService $searchService */
$results = $searchService->findContent($query);
$media = [];
foreach ($results->searchHits as $searchHit) {
    $media[] = $searchHit;
}
