<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/checkboxfield.md:40
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Checkbox\Value;

// Instantiates a checkbox value with a checked state
$checkboxValue = new Value(true);
