<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/checkboxfield.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

//Value object content examples
use Ibexa\Core\FieldType\Checkbox\Value;

// Instantiates a checkbox value with a default state (false)
$checkboxValue = new Value();

// Checked
$checkboxValue->bool = true;

// Unchecked
$checkboxValue->bool = false;
