<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/logicalnot_criterion.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$contentTypeIdentifier = 'article';

$query = new Query();
$query->filter = new Criterion\LogicalNot(
    new Criterion\ContentTypeIdentifier($contentTypeIdentifier)
);
