<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_payment_method_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\Payment\PaymentQuery;

/** @var \Ibexa\Contracts\Payment\PaymentMethodServiceInterface $paymentMethodService */
$paymentMethod = $paymentMethodService->getPaymentMethod(2);

$query = new PaymentQuery(
    new \Ibexa\Contracts\Payment\Payment\Query\Criterion\PaymentMethod($paymentMethod)
);
