<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/taxonomyentryfield.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Taxonomy\Service\TaxonomyServiceInterface;

/** @var TaxonomyServiceInterface $taxonomyService */
$taxonomyEntry = $taxonomyService->loadEntryByIdentifier('example_entry', 'tags');
$taxonomyEntryField = new \Ibexa\Taxonomy\FieldType\TaxonomyEntry\Value($taxonomyEntry);
