<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/taxonomyentryfield.md:32
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Taxonomy\Value\TaxonomyEntry;

/** @var TaxonomyEntry $taxonomyEntry */
return [
    'taxonomy_entry' => $taxonomyEntry, // load Entry using TaxonomyService
];
