<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/taxonomyentryfield.md:53
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Contracts\Taxonomy\Service\TaxonomyServiceInterface;
use Ibexa\Taxonomy\FieldType\TaxonomyEntry;

// Fetches TaxonomyEntry from TaxonomyService
/** @var TaxonomyServiceInterface $taxonomyService */
$taxonomyEntry = $taxonomyService->loadEntryByIdentifier('example_entry', 'tags');

// Instantiates a taxonomy entry value
$taxonomyEntryFieldTypeValue = new TaxonomyEntry\Value($taxonomyEntry);
