<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_method_identifier_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\PaymentMethod\PaymentMethodQuery;

$query = new PaymentMethodQuery(
    new \Ibexa\Contracts\Payment\PaymentMethod\Query\Criterion\Identifier('f7578972-e7f4-4cae-85dc-a7c74610204e')
);
