<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/floatstats_aggregation.md:23
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation;

$query = new Query();
$query->aggregations[] = new Aggregation\Field\FloatStatsAggregation('float', 'product', 'weight');
