<?php

declare(strict_types=1);
// Source: docs/multisite/siteaccess/injecting_siteaccess.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App;

use Ibexa\Contracts\Core\Repository\ContentService;
use Ibexa\Core\MVC\Symfony\SiteAccess\SiteAccessServiceInterface;

class MyService
{
    public function __construct(private readonly SiteAccessServiceInterface $siteAccessService, private readonly ContentService $contentService)
    {
    }
}
