<?php

declare(strict_types=1);
// Source: docs/commerce/shopping_list/install_shopping_list.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // ...
    Ibexa\Bundle\ShoppingList\IbexaShoppingListBundle::class => ['all' => true],
];
