ezplatform:
    system:
        admin_group:
            user_settings_update_view:
                full:
                    unit:
                        template: User/Setting/update_unit.html.twig
                        match:
                            Identifier: [ unit ]
