<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/authorfield.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Core\FieldType\Author;

$authorList = new Author\Value([
   new Author\Author([
       'id' => 1,
       'name' => 'Boba Fett',
       'email' => 'boba.fett@example.com',
   ]),
   new Author\Author([
       'id' => 2,
       'name' => 'Darth Vader',
       'email' => 'darth.vader@example.com',
   ]),
]);
