<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/authorfield.md:85
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Author field type example settings

use Ibexa\Core\FieldType\Author\Type;

$settings = [
    'defaultAuthor' => Type::DEFAULT_VALUE_EMPTY,
];
