<?php

declare(strict_types=1);
// Source: docs/administration/back_office/notifications.md:29
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\AdminUi\Notification\TranslatableNotificationHandlerInterface $notificationHandler */
$notificationHandler->info(
    /** @Desc("Notification text") */
    'example.notification.text',
    [],
    'domain'
);
