<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/browsing_content.md:175
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var int $contentId */
/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
$content = $contentService->loadContent($contentId, ['ger-DE']);
