<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/browsing_content.md:238
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
/** @var int $versionFromId */
/** @var int $versionToId */
/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
/** @var \Ibexa\Contracts\VersionComparison\Service\VersionComparisonServiceInterface $comparisonService */
$versionFrom = $contentService->loadVersionInfo($contentInfo, $versionFromId);
$versionTo = $contentService->loadVersionInfo($contentInfo, $versionToId);

$nameComparison = $comparisonService->compare($versionFrom, $versionTo)->getFieldValueDiffByIdentifier('name')->getComparisonResult();
