<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/browsing_content.md:214
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
$mainLocation = $contentInfo->getMainLocation();
$parentLocation = $mainLocation?->getParentLocation();
if ($parentLocation !== null) {
    $message = 'Parent Location: ' . $parentLocation->pathString;
}
