<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/browsing_content.md:183
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Language;

/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Content $content */
$contentService->loadContent($content->id, Language::ALL);
