<?php

declare(strict_types=1);
// Source: docs/content_management/content_api/browsing_content.md:107
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
/** @var \Ibexa\Contracts\Core\Repository\ContentService $contentService */
$versionInfo = $contentService->loadVersionInfo($contentInfo, 2);
