<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/currencycode_criterion.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Currency\CurrencyQuery;

$query = new CurrencyQuery(
    new \Ibexa\Contracts\ProductCatalog\Values\Currency\Query\Criterion\CurrencyCodeCriterion('EUR')
);
