<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/shipment_createdat_criterion.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;
use Ibexa\Contracts\Shipping\Shipment\ShipmentQuery;

$criteria = new \Ibexa\Contracts\Shipping\Shipment\Query\Criterion\CreatedAt(
    new DateTime('2023-03-01 14:07:02'),
    'GTE'
);

$query = new ShipmentQuery($criteria);
