<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/customergroupid_criterion.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\ProductCatalog\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\CustomerGroupId(1);
