<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/addressfield.md:31
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\FieldTypeAddress\FieldType;

new FieldType\Value(
    'My home address',
    'PL',
    [
        'city' => 'Warsaw',
        'region' => 'Masovian',
        'postal_code' => '11-123',
    ]
);
