<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/integerfield.md:28
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example
/** @var \Ibexa\Core\FieldType\Integer\Value $integer */
$integer->value = 8;
