<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/integerfield.md:68
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of validator configuration in PHP
$validatorConfiguration = [
    'minIntegerValue' => 1,
    'maxIntegerValue' => 24,
];
