<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/integerfield.md:39
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Integer;

// Instantiates a Integer Value object
$integerValue = new Integer\Value(8);
