<?php

declare(strict_types=1);
// Source: docs/content_management/file_management/file_management.md:12
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Field $field */
/** @var \Ibexa\Core\IO\IOServiceInterface $ioService */
$file = $ioService->loadBinaryFile($field->value->id);
$fileContent = $ioService->getFileContents($file);
