<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/taxonomyentryid_aggregation.md:25
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\Taxonomy\Search\Query\Aggregation\TaxonomyEntryIdAggregation;

$query = new ProductQuery();
$query->setAggregations([new TaxonomyEntryIdAggregation('categories', 'product_categories')]);
