<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/field_criterion.md:29
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
$query->query = new Criterion\Field('name', Criterion\Operator::CONTAINS, 'Platform');
