<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/locationchildrenterm_aggregation.md:16
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\LocationQuery;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation;

$query = new LocationQuery();
$query->aggregations[] = new Aggregation\Location\LocationChildrenTermAggregation('location_children');
