<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/type_and_value.md:172
// (auto-generated by tools/extract-inline-php.php — do not edit)

[
    'backupData' => [
        'type' => 'bool',
        'default' => false,
    ],
    'defaultValue' => [
        'type' => 'string',
        'default' => 'Default Value',
    ],
];
