<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_method_id_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\PaymentMethod\PaymentMethodQuery;

$query = new PaymentMethodQuery(
    new \Ibexa\Contracts\Payment\PaymentMethod\Query\Criterion\Id(2)
);
