<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/sibling_criterion.md:29
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;

$query = new Query();
/** @var \Ibexa\Contracts\Core\Repository\LocationService $locationService */
$location = $locationService->loadLocation(59);
$query->query = Criterion\Sibling::fromLocation($location);
