services:
    App\Migrations\Action\AssignSectionDenormalizer:
        autoconfigure: false
        tags:
            - { name: 'ibexa.migrations.serializer.normalizer' }

    App\Migrations\Action\AssignSectionExecutor:
        tags:
            - { name: 'ibexa.migrations.executor.action.content', key: !php/const App\Migrations\Action\AssignSection::TYPE }

    App\Migrations\Matcher\SectionIdentifierNormalizer:
        tags:
            - { name: 'ibexa.migrations.serializer.normalizer' }
            
    App\Migrations\Matcher\SectionIdentifierGenerator:
        tags:
            - { name: 'ibexa.migrations.generator.criterion_generator.content' }

    App\Migrations\Step\ImATeapotStepNormalizer:
        tags:
            - 'ibexa.migrations.serializer.step_normalizer'
            - { name: 'ibexa.migrations.serializer.normalizer', priority: 9000 }

    App\Migrations\Step\ImATeapotStepExecutor:
        tags:
            - 'ibexa.migrations.step_executor'
