<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/textlinefield.md:39
// (auto-generated by tools/extract-inline-php.php — do not edit)

[
  'StringLengthValidator' => [
    'maxStringLength' => 60,
    'minStringLength' => 1,
  ],
];
