<?php

declare(strict_types=1);
// Source: docs/search/activity_log_search_reference/object_criterion.md:21
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ActivityLog\Values\ActivityLog as ActivityLog;

$query = new ActivityLog\Query([
    new ActivityLog\Criterion\ObjectCriterion(Ibexa\Contracts\ProductCatalog\Values\ProductVariantInterface::class, ['123', '234', '345']),
]);
