displayName: Monitoring activity
/list:
    get:
        displayName: List of activity log entries
        description: Lists last activity log entries. (See `activity_log.pagination.activity_logs_limit` for how-many.)
        headers:
            Accept:
                description: If set, the list is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ActivityLogList+xml
                    application/vnd.ibexa.api.ActivityLogList+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ActivityLogList+xml:
                        type: ActivityLogList
                        example: !include examples/activitylog/GET/ActivityLogList.xml.example
                    application/vnd.ibexa.api.ActivityLogList+json:
                        type: ActivityLogList
                        example: !include examples/activitylog/GET/ActivityLogList.json.example
            401:
                description: Error - the user is not authorized to list activities.
    post:
        displayName: List of filtered activity log entries
        description: Lists activity log entries filtered according to the input payload. List input reflects the criteria model of the PHP API. See Activity Log Search reference.
        headers:
            Accept:
                description: If set, the list is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ActivityLogList+xml
                    application/vnd.ibexa.api.ActivityLogList+json
            Content-Type:
                description: The ActivityLogListInput query schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ActivityLogListInput+xml
                    application/vnd.ibexa.api.ActivityLogListInput+json
        body:
            application/vnd.ibexa.api.ActivityLogListInput+xml:
                type: ActivityLogListInput
                example: !include examples/activitylog/POST/ActivityLogListInput.xml.example
            application/vnd.ibexa.api.ActivityLogListInput+json:
                type: ActivityLogListInput
                example: !include examples/activitylog/POST/ActivityLogListInput.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ActivityLogList+xml:
                        type: ActivityLogList
                        example: !include examples/activitylog/POST/ActivityLogList.xml.example
                    application/vnd.ibexa.api.ActivityLogList+json:
                        type: ActivityLogList
                        example: !include examples/activitylog/POST/ActivityLogList.json.example
            401:
                description: Error - the user is not authorized to list activities.
