displayName: Managing content type groups
get:
    displayName: Get content type groups
    description: Returns a list of all content type groups. If an identifier is provided, loads the content type group for this identifier.
    queryParameters:
        identifier:
            description: The identifier of the content type group. If present, the content type group with this identifier is returned.
            required: false
    headers:
        Accept:
            description: If set, the content type group list is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.ContentTypeGroupList+xml
                application/vnd.ibexa.api.ContentTypeGroupList+json
    responses:
        200:
            description: OK - returns a list of content type groups.
            body:
                application/vnd.ibexa.api.ContentTypeGroupList+xml:
                    type: ContentTypeGroupList
                    example: !include examples/content/typegroups/GET/ContentTypeGroupList.xml.example
                application/vnd.ibexa.api.ContentTypeGroupList+json:
                    type: ContentTypeGroupList
                    example: !include examples/content/typegroups/GET/ContentTypeGroupList.json.example
        307:
            description: Temporary redirect.
        401:
            description: Error - The user has no permission to read content types.
        404:
            description: Error - The content type group with the given identifier does not exist.
post:
    displayName: Create content type group
    description: Creates a new content type group.
    headers:
        Accept:
            description: If set, the new content type group is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.ContentTypeGroup+xml
                application/vnd.ibexa.api.ContentTypeGroup+json
        Content-Type:
            description: The content type group input schema encoded in XML or JSON.
            example: |
                application/vnd.ibexa.api.ContentTypeGroupInput+xml
                application/vnd.ibexa.api.ContentTypeGroupInput+json
    body:
        application/vnd.ibexa.api.ContentTypeGroupInput+xml:
            type: ContentTypeGroupInput
            example: !include examples/content/typegroups/POST/ContentTypeGroupInput.xml.example
        application/vnd.ibexa.api.ContentTypeGroupInput+json:
            type: ContentTypeGroupInput
            example: !include examples/content/typegroups/POST/ContentTypeGroupInput.json.example
    responses:
        201:
            description: content type group created.
            body:
                application/vnd.ibexa.api.ContentTypeGroup+xml:
                    type: ContentTypeGroup
                    example: !include examples/content/typegroups/POST/ContentTypeGroup.xml.example
                application/vnd.ibexa.api.ContentTypeGroup+json:
                    type: ContentTypeGroup
                    example: !include examples/content/typegroups/POST/ContentTypeGroup.json.example
        400:
            description: Error - The input does not match the input schema definition.
        401:
            description: Error - The user is not authorized to create this content type group.
        403:
            description: Error - A content type group with the same identifier already exists.
/{contentTypeGroupId}:
    get:
        displayName: Get content type group
        description: Returns the content type group with provided ID.
        headers:
            Accept:
                description: If set, the content type group is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ContentTypeGroup+xml
                    application/vnd.ibexa.api.ContentTypeGroup+json
            If-None-Match:
                description: ETag
        responses:
            200:
                description: OK - returns the content type group.
                body:
                    application/vnd.ibexa.api.ContentTypeGroup+xml:
                        type: ContentTypeGroup
                        example: !include examples/content/typegroups/content_type_group_id/GET/ContentTypeGroup.xml.example
                    application/vnd.ibexa.api.ContentTypeGroup+json:
                        type: ContentTypeGroup
                        example: !include examples/content/typegroups/content_type_group_id/GET/ContentTypeGroup.json.example
            401:
                description: Error - The user is not authorized to read this content type group.
            404:
                description: Error - The content type group does not exist.
    patch:
        displayName: Update content type group
        description: Updates a content type group. PATCH or POST with header X-HTTP-Method-Override PATCH.
        headers:
            Accept:
                description: If set, the updated content type group is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ContentTypeGroup+xml
                    application/vnd.ibexa.api.ContentTypeGroup+json
            Content-Type:
                description: The content type group input schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.ContentTypeGroupInput+xml
                    application/vnd.ibexa.api.ContentTypeGroupInput+json
            If-Match:
                description: ETag causes patching only if the specified ETag is the current one. Otherwise a 412 is returned.
        body:
            application/vnd.ibexa.api.ContentTypeGroupInput+xml:
                type: ContentTypeGroupInput
                example: !include examples/content/typegroups/content_type_group_id/PATCH/ContentTypeGroupInput.xml.example
            application/vnd.ibexa.api.ContentTypeGroupInput+json:
                type: ContentTypeGroupInput
                example: !include examples/content/typegroups/content_type_group_id/PATCH/ContentTypeGroupInput.json.example
        responses:
            200:
                description: content type group updated.
                body:
                    application/vnd.ibexa.api.ContentTypeGroup+xml:
                        type: ContentTypeGroup
                        example: !include examples/content/typegroups/content_type_group_id/PATCH/ContentTypeGroup.xml.example
                    application/vnd.ibexa.api.ContentTypeGroup+json:
                        type: ContentTypeGroup
                        example: !include examples/content/typegroups/content_type_group_id/PATCH/ContentTypeGroup.json.example
            400:
                description: Error - The input does not match the input schema definition.
            401:
                description: Error - The user is not authorized to create this content type group.
            403:
                description: Error - A content type group with the given identifier already exists.
            412:
                description: Error - The current ETag does not match the one provided in the If-Match header.
    delete:
        displayName: Delete content type group
        description: Deletes the provided content type group.
        responses:
            204:
                description: No Content - content type group deleted.
            401:
                description: Error - The user is not authorized to delete this content type group.
            403:
                description: Error - The content type group is not empty.
            404:
                description: Error - The content type group does not exist.
    /types:
        get:
            displayName: List content types for group
            description: Returns a list of content types in the provided group.
            headers:
                Accept:
                    description: If set, the list of content type info objects or content types (including Field definitions) is returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.ContentTypeInfoList+xml
                        application/vnd.ibexa.api.ContentTypeInfoList+json
                        application/vnd.ibexa.api.ContentTypeList+xml
                        application/vnd.ibexa.api.ContentTypeList+json
            responses:
                200:
                    description: OK - returns a list on content types.
                    body:
                        application/vnd.ibexa.api.ContentTypeInfoList+xml:
                            type: ContentTypeInfoList
                            example: !include examples/content/typegroups/content_type_group_id/types/GET/ContentTypeInfoList.xml.example
                        application/vnd.ibexa.api.ContentTypeInfoList+json:
                            type: ContentTypeInfoList
                            example: !include examples/content/typegroups/content_type_group_id/types/GET/ContentTypeInfoList.json.example
                401:
                    description: Error - The user has no permission to read the content types.
        post:
            displayName: Create content type
            description: Creates a new content type draft in the given content type group.
            queryParameters:
                publish:
                    description: If true, the content type is published after creating (default false).
                    type: boolean
            headers:
                Accept:
                    description: If set, the new content type or draft is returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.ContentType+xml
                        application/vnd.ibexa.api.ContentType+json
                Content-Type:
                    description: The content type Create schema encoded in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.ContentTypeCreate+xml
                        application/vnd.ibexa.api.ContentTypeCreate+json
            body:
                application/vnd.ibexa.api.ContentTypeCreate+xml:
                    type: ContentTypeCreate
                    example: !include examples/content/typegroups/content_type_group_id/types/POST/ContentTypeCreate.xml.example
                application/vnd.ez.api.ContentTypeCreate+json:
                    type: ContentTypeCreate
                    example: !include examples/content/typegroups/content_type_group_id/types/POST/ContentTypeCreate.json.example
            responses:
                201:
                    description: content type created.
                    body:
                        application/vnd.ibexa.api.ContentType+xml:
                            type: ContentType
                            example: !include examples/content/typegroups/content_type_group_id/types/POST/ContentType.xml.example
                400:
                    description: Error - The input does not match the input schema definition. Validation on a Field definition fails. Validation of the content type fails, e.g. multiple Fields of a same singular Field Type are provided. Publish is set to true and the input is not complete e.g. no Field definitions are provided.
                401:
                    description: Error - The user is not authorized to create this content type.
                403:
                    description: Error - A content type with same identifier already exists.
