post:
    displayName: Create Cart
    description: Creates Cart from payload.
/{identifier}:
    get:
        displayName: Get Cart
        description: Gets Cart by its identifier.
    delete:
        displayName: Delete Cart
        description: Deletes Cart by its identifier.
    patch:
        displayName: Update Cart
        description: Updates identified Cart from payload.

