post:
    displayName: Create Cart
    description: Creates Cart from payload.
    headers:
        Content-Type:
            description: The CartCreateStruct schema encoded in XML or JSON format.
            example: |
                application/vnd.ibexa.api.CartCreateStruct+xml
                application/vnd.ibexa.api.CartCreateStruct+json
    #body:
    #    application/vnd.ibexa.api.CartCreateStruct+xml:
    #        type: CartCreateStruct
    #        example: !include examples/cart/POST/CartCreateStruct.json.example
    #responses:
    #    200:
    #        body:
    #            application/vnd.ibexa.api.Cart+json:
    #                type: Cart
    #                example: !include examples/cart/POST/Cart.json.example
    #    400:
    #        description: Error - The input does not match the input schema definition.
/{identifier}:
    get:
        displayName: Get Cart
        description: Gets Cart by its identifier.
        #responses:
        #    200:
        #        body:
        #            application/vnd.ibexa.api.Cart+json:
        #                type: Cart
        #                example: !include examples/cart/POST/Cart.json.example
        #    404:
        #        description: Error - The identifier do not match any Cart.
    delete:
        displayName: Delete Cart
        description: Deletes Cart by its identifier.
    patch:
        displayName: Update Cart's metadata
        description: Updates identified Cart's metadata from payload.
        headers:
            Content-Type:
                description: The CartMetadataUpdateStruct schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.CartMetadataUpdateStruct+xml        
                    application/vnd.ibexa.api.CartMetadataUpdateStruct+json        
    /entry:
        post:
            displayName: Add Entry to Cart
            description: Adds an the posted entry to the cart passed by identifier
            headers:
                Content-Type:
                    description: The EntryAddStruct schema encoded in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.EntryAddStruct+xml
                        application/vnd.ibexa.api.EntryAddStruct+json
            #body:
            #    application/vnd.ibexa.api.EntryAddStruct+xml:
            #        type: EntryAddStruct
            #        example: !include examples/cart/entry/POST/EntryAddStruct.json.example
        /{entryId}:
            delete:
                displayName: Remove Entry from Cart
                description: Removes the given entry from the given cart
            patch:
                displayName: Update Entry from Cart
                description: Updates the given entry from the given cart
                headers:
                    Content-Type:
                        description: The EntryUpdateStruct schema encoded in XML or JSON format.
                        example: |
                            application/vnd.ibexa.api.EntryUpdateStruct+xml
                            application/vnd.ibexa.api.EntryUpdateStruct+json