get:
    displayName: Load regions
    description: Loads the list of regions.
    headers:
        Accept:
            description: RegionList - If set, the regions list returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.RegionGetList+json
    responses:
        200:
            description: OK - loads regions.
            body:
                application/vnd.ibexa.api.RegionListGet+json:
                    type: RegionList
                    example: !include examples/product/catalog/regions/GET/RegionList.json.example
        401:
            description: Error - the user has no permission to read regions.
        404:
            description: Error - the region does not exist.

/view:
    post:
        displayName: Filter regions
        description: Executes a query and returns a View including the results. The View input reflects the criteria model of the public API.
        headers:
            Accept:
                description: The view in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.RegionView+xml
                    application/vnd.ibexa.api.RegionView+json
            Content-Type:
                description: The view input in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.RegionViewInput+xml
                    application/vnd.ibexa.api.RegionViewInput+json
        body:
            application/vnd.ibexa.api.RegionViewInput+json:
                type: RegionViewInput
                example: !include examples/product/catalog/regions/POST/RegionViewInput.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.RegionView+json;
                        type: RegionView
                        example: !include examples/product/catalog/regions/POST/RegionView.json.example
            400:
                description: Error - the input does not match the input schema definition.
