post:
    displayName: Create product type
    description: Creates a new product type.
    headers:
        Accept:
            description: If set, the new product type is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductTypeCreate+json
        Content-Type:
            description: The ProductType schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductTypeCreate+json
    body:
        application/vnd.ibexa.api.ProductTypeCreate+json:
            type: ProductTypeCreate
            example: !include examples/product/catalog/product_types/POST/ProductTypeCreate.json.example
    responses:
        201:
            body:
                application/vnd.ibexa.api.ProductType+json:
                    type: ProductType
                    example: !include examples/product/catalog/product_types/POST/ProductType.json.example
        400:
            description: Error - the input does not match the input schema definition.
        401:
            description: Error - the user is not authorized to create this product type.
        403:
            description: Error - a product type with the same name already exists.
        404:
            description: Error - the product type with the given ID does not exist.
get:
    displayName: Load product types (deprecated, use /view instead)
    description: Returns a list of product types. Deprecated as of Ibexa DXP 4.3, use POST /product/catalog/product_types/view instead.
    headers:
        Accept:
            description: ProductTypeListGet - If set, the product type list is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductTypeListGet+json
        Content-Type:
            description: The ProductTypeList schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.ProductTypeListGet+json
    body:
        application/vnd.ibexa.api.ProductTypeListGet+json:
            type: ProductTypeList
            example: !include examples/product/catalog/product_types/GET/ProductTypeListGet.json.example
    responses:
        200:
            body:
                application/vnd.ibexa.api.ProductTypeList+json:
                    type: ProductTypeList
                    example: !include examples/product/catalog/product_types/GET/ProductTypeList.json.example
        401:
            description: Error - the user has no permission to read product type.
/is_used/{identifier}:
    get:
        displayName: Check product type usage
        description: Checks whether the product type is in use.
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ProductTypeUsage+json:
                        type: ProductTypeUsage
                        example: !include examples/product/catalog/product_types/is_used/GET/ProductTypeUsage.json.example
            404:
                description: Error - product type not found.
/{id}:
    get:
        displayName: Load product type
        description: Returns the given product type.
        headers:
            Accept:
                description: ProductTypeGet - If set, the product type is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeGet+json
            Content-Type:
                description: The ProductType schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeGet+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ProductType+json:
                        type: ProductType
                        example: !include examples/product/catalog/product_types/id/GET/ProductType.json.example
            401:
                description: Error - the user has no permission to read product type.
    patch:
        displayName: Update product type
        description: Updates product type.
        headers:
            Accept:
                description: If set, the updated product type is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeUpdate+json
            Content-Type:
                description: If set, the updated product type is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeUpdate+json
        body:
            application/vnd.ibexa.api.ProductTypeUpdate+json:
                type: ProductTypeUpdate
                example: !include examples/product/catalog/product_types/id/PATCH/ProductTypeUpdate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.ProductType+json:
                        type: ProductTypeUpdate
                        example: !include examples/product/catalog/product_types/id/PATCH/ProductType.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to create this product type.
            404:
                description: Error - the product type with the given ID does not exist.
    delete:
        displayName: Delete product type
        description: Deletes the given product type.
        responses:
            204:
                description: No content - the given product type is deleted.
            401:
                description: Error - the user is not authorized to delete this product type.
/view:
    post:
        displayName: Filter product types
        description: Executes a query and returns a View including the results. The View input reflects the criteria model of the public API.
        headers:
            Accept:
                description: The view in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeView+xml
                    application/vnd.ibexa.api.ProductTypeView+json
            Content-Type:
                description: The view input in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.ProductTypeViewInput+xml
                    application/vnd.ibexa.api.ProductTypeViewInput+json
        body:
            application/vnd.ibexa.api.ProductTypeViewInput+json:
                type: ProductTypeViewInput
                example: !include examples/product/catalog/product_types/POST/ProductTypeViewInput.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.ProductTypeView+json:
                        type: ProductTypeView
                        example: !include examples/product/catalog/product_types/POST/ProductTypeView.json.example
            400:
                description: Error - the input does not match the input schema definition.
