post:
    displayName: Create attribute
    description: Creates a new attribute.
    headers:
        Accept:
            description: If set, the new attribute is returned in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.AttributeCreate+json
        Content-Type:
            description: The attribute schema encoded in XML or JSON format.
            example:  |
                application/vnd.ibexa.api.AttributeCreate+json
    body:
        application/vnd.ibexa.api.AttributeCreate+json:
            type: AttributeCreate
            example: !include examples/product/catalog/attributes/POST/AttributeCreate.json.example
    responses:
        201:
            body:
                application/vnd.ibexa.api.Attribute+json:
                    type: Attribute
                    example: !include examples/product/catalog/attributes/POST/Attribute.json.example
        400:
            description: Error - the input does not match the input schema definition.
        401:
            description: Error - the user is not authorized to create this attribute.
        403:
            description: Error - an attribute with the same name already exists.
/{id}:
    get:
        displayName: Load attribute
        description: Loads given attribute.
        headers:
            Accept:
                description: AttributeGet - If set, the given attribute is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.AttributeGet+json
            Content-Type:
                description: The attribute schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.AttributeGet+json
        body:
            application/vnd.ibexa.api.AttributeGet+json:
                type: AttributeList
                example: !include examples/product/catalog/attributes/id/GET/AttributeGet.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.Attribute+json:
                        type: Attribute
                        example: !include examples/product/catalog/attributes/id/GET/Attribute.json.example
            401:
                description: Error - the user has no permission to read the attribute.
    delete:
        displayName: Delete attribute
        description: The given attribute is removed from the attribute group.
        responses:
            200:
                description: No Content.
            401:
                description: Error - the user is not authorized to delete this attribute.
/{id}/{group_id}:
    patch:
        displayName: Update attribute
        description: Updates an attribute.
        headers:
            Accept:
                description: If set, the updated attribute is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeUpdate+json
            Content-Type:
                description: If set, the updated attribute group is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeUpdate+json
        body:
            application/vnd.ibexa.api.AttributeUpdate+json:
                type: AttributeUpdate
                example: !include examples/product/catalog/attributes/id/group_id/PATCH/AttributeUpdate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.Attribute+json:
                        type: Attribute
                        example: !include examples/product/catalog/attributes/id/group_id/PATCH/Attribute.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to create this attribute.
            403:
                description: Error - an attribute with the same name already exists.
            404:
                description: Error - the attribute with the given ID does not exist.
/translation/{id}/{languageCode}:
    delete:
        displayName: Delete attribute translation
        description: The given translation is removed from the attribute.
        responses:
            200:
                description: No Content.
            401:
                description: Error - the user is not authorized to delete this translation.
get:
    displayName: Load attributes (deprecated, use /view instead)
    description: Loads list of all attributes. Deprecated as of Ibexa DXP 4.3, use POST /product/catalog/attributes/view instead.
    headers:
        Accept:
            description: AttributeList - If set, the attributes list is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.AttributeListGet+json
        Content-Type:
            description: The AttributeList schema encoded in XML or JSON format.
            example: |
                application/vnd.ibexa.api.AttributeListGet+json
    body:
        application/vnd.ibexa.api.AttributeListGet+json:
            type: AttributeList
            example: !include examples/product/catalog/attributes/GET/AttributeListGet.json.example
    responses:
        200:
            body:
                application/vnd.ibexa.api.AttributeList+json:
                    type: AttributeList
                    example: !include examples/product/catalog/attributes/GET/AttributeList.json.example
        401:
            description: Error - the user has no permission to read user groups.
/view:
    post:
        displayName: Filter attributes
        description: Executes a query and returns a View including the results. The View input reflects the criteria model of the public API.
        headers:
            Accept:
                description: The view in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeView+xml
                    application/vnd.ibexa.api.AttributeView+json
            Content-Type:
                description: The view input in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.AttributeViewInput+xml
                    application/vnd.ibexa.api.AttributeViewInput+json
        body:
            application/vnd.ibexa.api.AttributeViewInput+json:
                type: AttributeViewInput
                example: !include examples/product/catalog/attributes/POST/AttributeViewInput.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.AttributeView+json:
                        type: AttributeView
                        example: !include examples/product/catalog/attributes/POST/AttributeView.json.example
            400:
                description: Error - the input does not match the input schema definition.
