/collaboration/session/{sessionID}/participant/list:
    get:
        displayName: Load participant list
        description: Load participant list.
        queryParameters:
            sessionId:
                description: Retrieves the participant list for a given collaboration session ID (e.g. GET /collaboration/session/1234).
        headers:
            Accept:
                description: ParticipantList - If set, the participant list is returned in XML or JSON format.
                    application/vnd.ibexa.api.ParticipantList+xml
                    application/vnd.ibexa.api.ParticipantList+json
        responses:
            200:
                description: OK - Loads participants for a given collaboration session ID.
                body:
                    application/vnd.ibexa.api.ParticipantList+xml:
                        type: ParticipantList
                        example: !include examples/collaborative_editing/participant/list/GET/ParticipantList.xml.example
                    application/vnd.ibexa.api.ParticipantList+json:
                        type: ParticipantList
                        example: !include examples/collaborative_editing/participant/list/GET/ParticipantList.json.example
            404:
                description: If there are no visibile participants matching the filter.

/collaboration/session/{sessionId}/participant/add:
    post:
        displayName: Add participant
        description: Adds new participant.
        headers:
            Accept:
                description: If set, the new participant is returned in XML or JSON format.
                example:
                    application/vnd.ibexa.api.ParticipantList+json
            Content-Type:
                description: The participant schema encoded in XML or JSON format.
                example:
                    application/vnd.ibexa.api.ParticipantListCreate+xml
        body:
            application/vnd.ibexa.api.ParticipantList+json:
                type: ProductList
                example: !include examples/collaborative_editing/participant/add/PATCH/ParticipantListCreate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.ParticipantList+json:
                        type: ProductList
                        example: !include examples/
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to update this product.
            403:
                description: Error - a participant with the same name already exists.
            404:
                description: Error - no participant with the given ID exists.

/collaboration/session/{sessionId}/participant/{participantId}/update
    patch:
        displayName: Update participant
        description: Updates a participant.
        headers:
            Accept:
                description: If set, the updated participant is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.<Discriminator>Participant+json
                    application/vnd.ibexa.api.<Discriminator>Participant+xml
            Content-Type:
                description: The ParticipantUpdate schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.<Discriminator>ParticipantUpdate+json
                    application/vnd.ibexa.api.<Discriminator>ParticipantUpdate+xml
            If-Match:
                description: Performs a PATCH only if the specified ETag is the current one.
                example: ETag
        body:
            application/vnd.ibexa.api.ParticipantUpdate+xml:
                type: ParticipantUpdate
                example: !include examples/
        responses:
            200:
                description: OK - participant updated.
                body:
                    application/vnd.ibexa.api.participant+xml:
                        type: Participant
                        example: !include examples/
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to update the User.
            404:
                description: Error - the User does not exist.
            412:
                description: Error - the current ETag does not match with the provided one in the If-Match header.

/collaboration/session/{sessionId}/participant/{participantId}/remove:
    delete:
        displayName: Delete participant
        description: Deletes the given participant.
        responses:
            204:
                description: No Content.
            401:
                description: Error - the user is not authorized to delete this participant.
            403:
                description: Error - the user is the same as the authenticated participant.
            404:
                description: Error - the participant does not exist.

