get:
    displayName: Load Locations by id/remoteId/urlAlias
    description: Loads the Location for a given ID (x), remote ID or URL alias.
    queryParameters:
        id:
            description: The ID of the Location. If present, the Location with the given ID is returned.
        remoteId:
            description: The remote ID of the Location. If present, the Location with the given remote ID is returned.
        urlAlias:
            description: One of the URL aliases of the Location. If present, the Location with given URL Alias is returned.
    headers:
        Accept:
            example: |
                application/vnd.ibexa.api.LocationList+xml
                application/vnd.ibexa.api.LocationList+json
    responses:
        307:
            description: Temporary redirect to the main resource URL.
        200:
            body:
                application/vnd.ibexa.api.LocationList+xml:
                    type: Location
                    example: !include examples/content/locations/GET/LocationList.xml.example
                application/vnd.ibexa.api.LocationList+json:
                    type: LocationWrapper
                    example: !include examples/content/locations/GET/LocationList.json.example
        404:
            description: Error - the Location with the given ID (remote ID or URL  Alias) does not exist.
/{path}:
    get:
        displayName: Load Location
        description: Loads the Location for the given path e.g. '/content/locations/1/2/61'.
        headers:
            Accept:
                description: If set, the new Location is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.Location+xml
                    application/vnd.ibexa.api.Location+json
            If-None-Match:
                description: ETag
        responses:
            200:
                body:
                    application/vnd.ibexa.api.Location+xml:
                        type: Location
                        example: !include examples/content/locations/path/GET/Location.xml.example
                    application/vnd.ibexa.api.Location+json:
                        type: LocationWrapper
                        example: !include examples/content/locations/path/GET/Location.json.example
            401:
                description: Error - the user is not authorized to read this Location.
            404:
                description: Error - the Location with the given path does not exist.
    delete:
        displayName: Delete subtree
        description: Deletes the complete subtree for the given path. Every content item which does not have any other Location is deleted. Otherwise the deleted Location is removed from the content item. The children are recursively deleted.
        responses:
            204:
                description: No Content - deleted.
            401:
                description: Error - the user is not authorized to delete this subtree.
            404:
                description: Error - the Location with the given ID does not exist.
    patch:
        displayName: Update Location
        description: Updates the Location. This method can also be used to hide/reveal a Location via the hidden field in the LocationUpdate. PATCH or POST with header X-HTTP-Method-Override PATCH.
        headers:
            Accept:
                description: If set, the Location is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.Location+xml
                    application/vnd.ibexa.api.Location+json
            Content-Type:
                description: The LocationUpdate schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.LocationUpdate+xml
                    application/vnd.ibexa.api.LocationUpdate+json
            If-Match:
                description: ETag
        body:
            application/vnd.ibexa.api.LocationUpdate+xml:
                type: LocationUpdate
                example: !include examples/content/locations/location_id/PATCH/LocationUpdate.xml.example
            application/vnd.ibexa.api.LocationUpdate+json:
                type: LocationUpdateWrapper
                example: !include examples/content/locations/location_id/PATCH/LocationUpdate.json.example
        responses:
            200:
                body:
                    application/vnd.ibexa.api.Location+xml:
                        type: Location
                        example: !include examples/content/locations/location_id/PATCH/Location.xml.example
                    application/vnd.ibexa.api.Location+json:
                        type: LocationWrapper
                        example: !include examples/content/locations/location_id/PATCH/Location.json.example
            401:
                description: Error - the user is not authorized to update this Location.
            404:
                description: Error - the Location with the given ID does not exist.
    post:
        displayName: Swap Location / Copy subtree / Move subtree
        description: Swaps the Location of a content item with the given Location of another content item, or copies a subtree or moves a subtree, all depending on request method or Content-Type header. Request method can be POST, SWAP, COPY, or MOVE.
        headers:
            Content-Type:
                description: Required only when using POST request method. Indicates the format of the request body and the action.
                examples: |
                    application/vnd.ibexa.api.SwapLocationInput+json
                    application/vnd.ibexa.api.SwapLocationInput+xml
                    application/vnd.ibexa.api.CopyLocationInput+json
                    application/vnd.ibexa.api.CopyLocationInput+xml
                    application/vnd.ibexa.api.MoveLocationInput+json
                    application/vnd.ibexa.api.MoveLocationInput+xml
            Destination:
                description: Required only when using SWAP, COPY, or MOVE request methods. A location resource to swap with, copy the subtree to, or move the subtree to, e.g. '/api/ibexa/v2/content/locations/1/63'.
        body:
            description: Required only when using POST request method. Indicates the location to swap with or the subtree to copy
            example: |
                application/vnd.ibexa.api.SwapLocationInput+json:
                        type: SwapLocationInputWrapper
                        example: !include examples/content/locations/path/POST/SwapLocationInput.json.example
                application/vnd.ibexa.api.SwapLocationInput+xml:
                        type: SwapLocationInput
                        example: !include examples/content/locations/path/POST/SwapLocationInput.xml.example
                application/vnd.ibexa.api.SwapLocationInput+json:
                        type: CopyLocationInputWrapper
                        example: !include examples/content/locations/path/POST/SwapLocationInput.json.example
                application/vnd.ibexa.api.SwapLocationInput+xml:
                        type: CopyLocationInput
                        example: !include examples/content/locations/path/POST/SwapLocationInput.json.example
        responses:
            201:
                description: Created. Copied or moved the subtree to a different parent.
            204:
                description: No Content. Swapped the Location of a content item with the given Location of another content item.
            401:
                description: Error - the user is not authorized to swap this Location.
            404:
                description: Error - the Location with the given ID does not exist.
    /children:
        get:
            displayName: Get child Locations.
            description: Loads all child Locations for the given parent Location.
            queryParameters:
                offset:
                    description: The offset of the result set.
                    type: integer
                limit:
                    description: The number of Locations returned.
                    type: integer
            headers:
                Accept:
                    description: If set, the new Location list is returned in XML or JSON format.
                    example:  |
                        application/vnd.ibexa.api.LocationList+xml
                        application/vnd.ibexa.api.LocationList+json
            responses:
                200:
                    body:
                        application/vnd.ibexa.api.LocationList+xml:
                            type: LocationList
                            example: !include examples/content/locations/path/children/GET/LocationList.xml.example
                        application/vnd.ibexa.api.LocationList+json:
                            type: LocationList
                401:
                    description: Error - the user is not authorized to read this content item.
                404:
                    description: Error - the content item with the given ID does not exist.
    /urlaliases:
        get:
            displayName: List URL aliases for Location
            description: Returns the list of URL aliases for a Location.
            queryParameters:
                custom:
                    description: Indicates whether autogenerated (false) or manual URL aliases (true) should be returned (default true).
                    type: boolean
            headers:
                Accept:
                    description: If set, the URL alias list contains only references and is returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.UrlAliasRefList+xml
                        application/vnd.ibexa.api.UrlAliasRefList+json
            responses:
                200:
                    description: OK - returns the list of URL aliases.
                    body:
                        application/vnd.ibexa.api.UrlAliasRefList+xml:
                            type: UrlAliasRefList
                            example: !include examples/content/locations/path/urlaliases/GET/UrlAliasRefList.xml.example
                        application/vnd.ibexa.api.UrlAliasRefList+json:
                            type: UrlAliasRefListWrapper
                400:
                    description: Error - The user has no permission to read URL aliases.
                401:
                    description: Error - The Location was not found.
