displayName: Corporate Account
get:
    displayName: Root Resource
    description: |
        Provides basic information about Corporate Account endpoints and configuration.
    headers:
        Accept:
            description: If set, helps to determine response format.
            example: |
                application/vnd.ibexa.api.CorporateAccountRoot+xml
                application/vnd.ibexa.api.CorporateAccountRoot+json
    responses:
        200:
            description: List of Link objects to specific Corporate Account REST resources
            body:
                application/vnd.ibexa.api.CorporateAccountRoot+xml:
                    type: CorporateAccountRoot
                    example: !include examples/corporate/GET/CorporateAccountRoot.xml.example
                application/vnd.ibexa.api.CorporateAccountRoot+json:
                    type: CorporateAccountRootWrapper
                    example: !include examples/corporate/GET/CorporateAccountRoot.json.example

/companies:
    get:
        displayName: Read list of companies
        description: |
            Returns paginated list of available companies.
        queryParameters:
            filter:
                type: string
                description: |
                    An array-shaped string representing filtering Criterion. Supported Criteria:
                    | Criterion | Example |
                    | --------- | ------- |
                    | Creation date | `filter[DateMetadataCriterion][Target]=created&filter[DateMetadataCriterion][Value]=1679493636&filter[DateMetadataCriterion][Operator]=gte` |
                    | Updated date | `filter[DateMetadataCriterion][Target]=modified&filter[DateMetadataCriterion][Value]=1679493636&filter[DateMetadataCriterion][Operator]=gte` |
                    | Company Name | `filter[CompanyNameCriterion][Operator]=contains&filter[CompanyNameCriterion][Value]=Ibexa` |
                    | salesRep (id) | `filter[Field][name]=sales_rep&filter[Field][operator]=eq&filter[Field][value]=122` |
                    | contact (id) | `filter[Field][name]=contact&filter[Field][operator]=eq&filter[Field][value]=74` |
            sort:
                type: string
                description: |
                    An array-shaped string representing sorting clauses. Supported Clauses:
                    | Clause | Example |
                    | ------ | ------- |
                    | By Content (Company) name | `sort[ContentName]=ascending` |
                    | By publication date | `sort[DatePublished]=descending` |
                    | By modification date | `sort[DateModified]=ascending` |
            offset:
                description: The offset of the result set.
                type: integer
                default: 0
            limit:
                description: The number of returned companies.
                type: integer
                default: 25
        headers:
            Accept:
                description: If set, helps to determine response format.
                example: |
                    application/vnd.ibexa.api.CompanyList+xml
                    application/vnd.ibexa.api.CompanyList+json
        responses:
            200:
                description: Company list containing Company objects.
                body:
                    application/vnd.ibexa.api.CompanyList+xml:
                        type: CompanyList
                        example: !include examples/corporate/companies/GET/CompanyList.xml.example
                    application/vnd.ibexa.api.CompanyList+json:
                        type: CompanyListWrapper
                        example: !include examples/corporate/companies/GET/CompanyList.json.example
            400:
                description: Returned when invalid Criterion or Sort clause is used
                body:
                    application/vnd.ibexa.api.ErrorMessage:
                        type: ErrorMessage

    post:
        displayName: Create a company
        headers:
            Accept:
                description: If set, the new company is returned in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.Company+xml
                    application/vnd.ibexa.api.Company+json
            Content-Type:
                description: The CompanyCreate schema encoded in XML or JSON format.
                example:  |
                    application/vnd.ibexa.api.CompanyCreate+json
                    application/vnd.ibexa.api.CompanyCreate+xml
        body:
            application/vnd.ibexa.api.CompanyCreate+xml:
                type: CompanyCreate
                example: !include examples/corporate/companies/POST/CompanyCreate.xml.example
            application/vnd.ibexa.api.CompanyCreate+json:
                type: CompanyCreateWrapper
                example: !include examples/corporate/companies/POST/CompanyCreate.json.example
        responses:
            201:
                body:
                    application/vnd.ibexa.api.Company+xml:
                        type: Company
                        example: !include examples/corporate/companies/company_id/GET/Company.xml.example
                    application/vnd.ibexa.api.Company+json:
                        type: CompanyWrapper
                        example: !include examples/corporate/companies/company_id/GET/Company.json.example
            400:
                description: Error - the input does not match the input schema definition.
            401:
                description: Error - the user is not authorized to create this Company.
    /{companyId}:
        get:
            displayName: Get company
            description: Returns the company by given company ID.
            headers:
                Accept:
                    description: If set, the company is returned in XML or JSON format.
                    example:  |
                        application/vnd.ibexa.api.Company+xml
                        application/vnd.ibexa.api.Company+json
                If-None-match:
                    description: ETag
            responses:
                200:
                    body:
                        application/vnd.ibexa.api.Company+json:
                            type: CompanyWrapper
                            example: !include examples/corporate/companies/company_id/GET/Company.json.example
                        application/vnd.ibexa.api.Company+xml:
                            type: Company
                            example: !include examples/corporate/companies/company_id/GET/Company.xml.example
                401:
                    description: Error - The user is not authorized to read this company.
                404:
                    description: Error - The company does not exist.
        delete:
            displayName: Delete company
            description: The given company is deleted.
            headers:
                Accept:
                    description: If set, in the case of an error the error message is returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.ErrorMessage+xml
                        application/vnd.ibexa.api.ErrorMessage+json
                X-CSRF-Token:
                    description: Only needed for session's checking. The {csrfToken} needed on all unsafe HTTP methods with session.
            responses:
                204:
                    description: No Content - given company is deleted.
                401:
                    description: Error - the user is not authorized to delete this company.
                404:
                    description: Error - the company does not exist.
        patch:
            displayName: Update a company
            description: Updates a company. PATCH or POST with header X-HTTP-Method-Override PATCH.
            headers:
                Accept:
                    description: If set, the updated company is returned in XML or JSON format.
                    example:  |
                        application/vnd.ibexa.api.Company+xml
                        application/vnd.ibexa.api.Company+json
                Content-Type:
                    description: The company input schema encoded in XML or JSON.
                    example:  |
                        application/vnd.ibexa.api.CompanyUpdate+xml
                        application/vnd.ibexa.api.CompanyUpdate+json
                If-Match:
                    description: ETag
            body:
                application/vnd.ibexa.api.CompanyUpdate+xml:
                    type: CompanyUpdate
                    example: !include examples/corporate/companies/company_id/PATCH/CompanyUpdate.xml.example
                application/vnd.ibexa.api.CompanyUpdate+json:
                    type: CompanyUpdateWrapper
                    example: !include examples/corporate/companies/company_id/PATCH/CompanyUpdate.json.example
            responses:
                200:
                    description: OK - company updated.
                    body:
                        application/vnd.ibexa.api.Company+xml:
                            type: Company
                            example: !include examples/corporate/companies/company_id/GET/Company.xml.example
                        application/vnd.ibexa.api.Company+json:
                            type: CompanyWrapper
                            example: !include examples/corporate/companies/company_id/GET/Company.json.example
                400:
                    description: Error - the input does not match the input schema definition.
                401:
                    description: Error - the user is not authorized to create this company.
        /members:
            get:
                displayName: Read list of company members
                description: |
                    Returns paginated list of a given company members.
                queryParameters:
                    filter:
                        description: |
                            An array-shaped string representing filtering Criterion. Supported Criteria:
                            | Criterion | Example |
                            | --------- | ------- |
                            | Creation date | `filter[DateMetadataCriterion][Target]=created&filter[DateMetadataCriterion][Value]=1679493636&filter[DateMetadataCriterion][Operator]=gte` |
                            | Updated date | `filter[DateMetadataCriterion][Target]=modified&filter[DateMetadataCriterion][Value]=1679493636&filter[DateMetadataCriterion][Operator]=gte` |
                        type: array
                    sort:
                        description: |
                            An array-shaped string representing sorting clauses. Supported Clauses:
                            | Clause | Example |
                            | ------ | ------- |
                            | By Content (Member) name | `sort[ContentName]=ascending` |
                            | By Member account creation date | `sort[DatePublished]=descending` |
                            | By Member account modification date | `sort[DateModified]=ascending` |
                    offset:
                        description: The offset of the result set.
                        type: integer
                        default: 0
                    limit:
                        description: The number of returned members.
                        type: integer
                        default: 25
                headers:
                    Accept:
                        description: If set, helps to determine response format.
                        example: |
                            application/vnd.ibexa.api.MemberList+xml
                            application/vnd.ibexa.api.MemberList+json
                responses:
                    200:
                        body:
                            application/vnd.ibexa.api.MemberList+xml:
                                type: MemberList
                                example: !include examples/corporate/companies/company_id/members/GET/MemberList.xml.example
                            application/vnd.ibexa.api.MemberList+json:
                                type: MemberListWrapper
                                example: !include examples/corporate/companies/company_id/members/GET/MemberList.json.example
                    400:
                        description: Returned when invalid Criterion or Sort clause is used.
                        body:
                            application/vnd.ibexa.api.ErrorMessage:
                                type: ErrorMessage
            post:
                displayName: Create a company member
                description: Creates a company member.
                headers:
                    Accept:
                        description: If set, the new member is returned in XML or JSON format.
                        example:  |
                            application/vnd.ibexa.api.Member+xml
                            application/vnd.ibexa.api.Member+json
                    Content-Type:
                        description: The CompanyCreate schema encoded in XML or JSON format.
                        example:  |
                            application/vnd.ibexa.api.MemberCreate+json
                            application/vnd.ibexa.api.MemberCreate+xml
                body:
                    application/vnd.ibexa.api.MemberCreate+xml:
                        type: MemberCreate
                        example: !include examples/corporate/companies/company_id/members/POST/MemberCreate.xml.example
                    application/vnd.ibexa.api.MemberCreate+json:
                        type: MemberCreateWrapper
                        example: !include examples/corporate/companies/company_id/members/POST/MemberCreate.json.example
                responses:
                    201:
                        body:
                            application/vnd.ibexa.api.Member+xml:
                                type: Member
                                example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.xml.example
                            application/vnd.ibexa.api.Member+json:
                                type: MemberWrapper
                                example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.json.example
                    400:
                        description: Error - the input does not match the input schema definition.
                    401:
                        description: Error - the user is not authorized to create a company member.
            /{memberId}:
                get:
                    displayName: Get company member
                    description: Returns the company member by given member ID.
                    headers:
                        Accept:
                            description: If set, the company member is returned in XML or JSON format.
                            example:  |
                                application/vnd.ibexa.api.Member+xml
                                application/vnd.ibexa.api.Member+json
                    responses:
                        200:
                            body:
                                application/vnd.ibexa.api.Member+xml:
                                    type: Member
                                    example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.xml.example
                                application/vnd.ibexa.api.Member+json:
                                    type: MemberWrapper
                                    example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.json.example
                        401:
                            description: Error - The user is not authorized to read this company.
                        404:
                            description: Error - The company does not exist.
                delete:
                    displayName: Delete company member
                    description: The given company member is deleted.
                    headers:
                        Accept:
                            description: If set, in the case of an error the error message is returned in XML or JSON format.
                            example: |
                                application/vnd.ibexa.api.ErrorMessage+xml
                                application/vnd.ibexa.api.ErrorMessage+json
                        X-CSRF-Token:
                            description: Only needed for session's checking. The {csrfToken} needed on all unsafe HTTP methods with session.
                    responses:
                        204:
                            description: No Content - given company member is deleted.
                        401:
                            description: Error - the user is not authorized to delete this company member.
                        404:
                            description: Error - the company member does not exist.
                patch:
                    displayName: Update a company member
                    description: Updates a company member. PATCH or POST with header X-HTTP-Method-Override PATCH.
                    headers:
                        Accept:
                            description: If set, the updated company member is returned in XML or JSON format.
                            example:  |
                                application/vnd.ibexa.api.Member+xml
                                application/vnd.ibexa.api.Member+json
                        Content-Type:
                            description: The company input schema encoded in XML or JSON.
                            example:  |
                                application/vnd.ibexa.api.MemberUpdate+xml
                                application/vnd.ibexa.api.MemberUpdate+json
                        If-Match:
                            description: ETag
                    body:
                        application/vnd.ibexa.api.MemberUpdate+xml:
                            type: MemberUpdate
                            example: !include examples/corporate/companies/company_id/members/member_id/PATCH/MemberUpdate.xml.example
                        application/vnd.ibexa.api.MemberUpdate+json:
                            type: MemberUpdateWrapper
                            example: !include examples/corporate/companies/company_id/members/member_id/PATCH/MemberUpdate.json.example
                    responses:
                        200:
                            description: OK - company member updated.
                            body:
                                application/vnd.ibexa.api.Member+xml:
                                    type: Member
                                    example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.xml.example
                                application/vnd.ibexa.api.Member+json:
                                    type: MemberWrapper
                                    example: !include examples/corporate/companies/company_id/members/member_id/GET/Member.json.example
                        400:
                            description: Error - the input does not match the input schema definition.
                        401:
                            description: Error - the user is not authorized to create this company member.
/sales-representatives:
    get:
        displayName: Read list of sales representatives
        description: |
            Returns paginated list of available sales representatives.
        queryParameters:
            offset:
                description: The offset of the result set.
                type: integer
                default: 0
            limit:
                description: The number of returned representatives.
                type: integer
                default: 25
        headers:
            Accept:
                description: If set, helps to determine response format.
                example: |
                    application/vnd.ibexa.api.SalesRepresentativesList+xml
                    application/vnd.ibexa.api.SalesRepresentativesList+json

        responses:
            200:
                description: Sales representatives list containing Company objects.
                body:
                    application/vnd.ibexa.api.SalesRepresentativesList+xml:
                        type: SalesRepresentativesList
                        example: !include examples/corporate/sales-representatives/GET/SalesRepresentativesList.xml.example
                    application/vnd.ibexa.api.SalesRepresentativesList+json:
                        type: SalesRepresentativesListWrapper
                        example: !include examples/corporate/sales-representatives/GET/SalesRepresentativesList.json.example
            401:
                description: Error - the user is not authorized to read Sales Representatives List.
                body:
                    application/vnd.ibexa.api.ErrorMessage:
                        type: ErrorMessage
