displayName: Managing Commerce carts
post:
    displayName: Create Cart
    description: Creates Cart from payload.
    headers:
        Content-Type:
            description: The CartCreate schema encoded in XML or JSON format.
            example: |
                application/vnd.ibexa.api.CartCreate+xml
                application/vnd.ibexa.api.CartCreate+json
        Accept:
            description: If set, the created Cart is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.Cart+xml
                application/vnd.ibexa.api.Cart+json
    body:
        application/vnd.ibexa.api.CartCreate+xml:
            type: CartCreate
        application/vnd.ibexa.api.CartCreate+json:
            type: CartCreateWrapper
            example: !include examples/cart/POST/CartCreate.json.example
    responses:
        200:
            body:
                application/vnd.ibexa.api.Cart+xml:
                    type: Cart
                application/vnd.ibexa.api.Cart+json:
                    type: CartWrapper
                    example: !include examples/cart/POST/Cart.json.example
        400:
            description: Error - The input does not match the input schema definition.
/view:
    post:
        displayName: Filter carts
        description: Executes a query and returns a View including the results.
        headers:
            Accept:
                description: The CartView schema is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.CartView+xml
                    application/vnd.ibexa.api.CartView+json
            Content-Type:
                description: The CartViewInput schema is posted in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.CartViewInput+xml
                    application/vnd.ibexa.api.CartViewInput+json
        body:
            application/vnd.ibexa.api.CartViewInput+xml:
                type: CartViewInput
            application/vnd.ibexa.api.CartViewInput+json:
                type: CartViewInputWrapper
                example: !include examples/cart/view/CartViewInput.json.example
        responses:
            200:
                description: OK - returns a view and its results
                body:
                    application/vnd.ibexa.api.CartView+xml:
                        type: CartView
                    application/vnd.ibexa.api.CartView+json:
                        type: CartViewWrapper
                        example: !include examples/cart/view/CartView.json.example
/{identifier}:
    get:
        displayName: Get Cart
        description: Gets Cart by its identifier.
        headers:
            Accept:
                description: The Cart is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.Cart+xml
                    application/vnd.ibexa.api.Cart+json
        responses:
            200:
                description: OK - return the cart
                body:
                    application/vnd.ibexa.api.Cart+xml:
                        type: Cart
                    application/vnd.ibexa.api.Cart+json:
                        type: CartWrapper
                        example: !include examples/cart/POST/Cart.json.example
            401:
                description: Error - the user is not authorized to get this cart.
            404:
                description: Error - The identifier do not match any Cart.
    delete:
        displayName: Delete Cart
        description: Deletes Cart by its identifier.
    patch:
        displayName: Update Cart's metadata
        description: Updates identified Cart's metadata from payload.
        headers:
            Content-Type:
                description: The CartMetadataUpdate schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.CartMetadataUpdate+xml
                    application/vnd.ibexa.api.CartMetadataUpdate+json
        body:
            application/vnd.ibexa.api.CartMetadataUpdate+xml:
                type: CartMetadataUpdate
            application/vnd.ibexa.api.CartMetadataUpdate+json:
                type: CartMetadataUpdateWrapper
    /entry:
        post:
            displayName: Add Entry to Cart
            description: Adds an entry to the cart referenced by its identifier
            headers:
                Content-Type:
                    description: The CartEntryAdd schema encoded in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.CartEntryAdd+xml
                        application/vnd.ibexa.api.CartEntryAdd+json
            body:
                application/vnd.ibexa.api.CartEntryAdd+xml:
                    type: CartEntryAdd
                application/vnd.ibexa.api.CartEntryAdd+json:
                    type: CartEntryAddWrapper
                    example: !include examples/cart/entry/POST/CartEntryAdd.json.example
        /{entryId}:
            delete:
                displayName: Remove Entry from Cart
                description: Removes the given entry from the given Cart.
            patch:
                displayName: Update Entry from Cart
                description: Updates the given entry from the given Cart.
                headers:
                    Content-Type:
                        description: The CartEntryUpdate schema encoded in XML or JSON format.
                        example: |
                            application/vnd.ibexa.api.CartEntryUpdate+xml
                            application/vnd.ibexa.api.CartEntryUpdate+json
                body:
                    application/vnd.ibexa.api.CartEntryUpdate+xml:
                        type: CartEntryUpdate
                    application/vnd.ibexa.api.CartEntryUpdate+json:
                        type: CartEntryUpdateWrapper
    /empty:
        post:
            displayName: Empty Cart
            description: Empties the given Cart.
            responses:
                204:
                    description: No Content - Cart emptied.
                401:
                    description: Error - The user is not authorized to empty this Cart.
                404:
                    description: Error - Cart not found.
    /summary:
        get:
            displayName: Cart Summary
            description: Gets a summary of the given Cart.
            headers:
                Accept:
                    description: If set, the Cart Summary is returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.CartSummary+xml
                        application/vnd.ibexa.api.CartSummary+json
            responses:
                200:
                    body:
                        application/vnd.ibexa.api.CartSummary+xml:
                            type: CartSummary
                        application/vnd.ibexa.api.CartSummary+json:
                            type: CartSummaryWrapper
                            example: !include examples/cart/summary/CartSummary.json.example
                401:
                    description: Error - The user is not authorized to read this Cart.
                404:
                    description: Error - Cart not found.
    /validate:
        post:
            displayName: Cart Validation
            description: Validates a Cart against constraints
            headers:
                Accept:
                    description: If set, the Cart Constraint Violations are returned in XML or JSON format.
                    example: |
                        application/vnd.ibexa.api.CartConstraintViolationList+xml
                        application/vnd.ibexa.api.CartConstraintViolationList+json
            responses:
                200:
                    body:
                        application/vnd.ibexa.api.CartConstraintViolationList+xml:
                            type: CartConstraintViolationList
                        application/vnd.ibexa.api.CartConstraintViolationList+json:
                            type: CartConstraintViolationListWrapper
/authorize:
    post:
        displayName: Cart Authorization
        description: Returns the CSRF token required by anonymous user to interact with own cart.
        headers:
            Accept:
                example: |
                    application/vnd.ibexa.api.Token+xml
                    application/vnd.ibexa.api.Token+json
        responses:
            200:
                body:
                    application/vnd.ibexa.api.Token+xml:
                        type: Token
                    application/vnd.ibexa.api.CartConstraintViolationList+json:
                        type: Token
                        example: !include examples/cart/authorize/Token.json.example
