displayName: Discount Codes
/{cartIdentifier}:
    /apply:
        post:
            displayName: Apply discount to cart
            description: Applies a discount associated with given discount code
            headers:
                Accept:
                    description: Specifies the expected response type. Only JSON is supported.
                    example: |
                        application/vnd.ibexa.api.DiscountCode+json
                Content-Type:
                    description: Specifies the input type.
                    example: |
                        application/vnd.ibexa.api.DiscountCode+json
            body:
                application/vnd.ibexa.api.DiscountCode+json:
                    type: DiscountCodeWrapper
                    example: !include examples/discount_codes/apply/POST/DiscountCode.json.example
            responses:
                200:
                    description: Discount applied successfully
                    body:
                        application/vnd.ibexa.api.DiscountCode+json:
                            type: DiscountCodeWrapper
                            example: !include examples/discount_codes/apply/POST/DiscountCodeResponse.json.example
                400:
                    description: Error - the request is invalid.
                404:
                    description: Error - the given cart identifier was not found, or the discount code does not exist.
                429:
                    description: Error - the request was throttled due to too many requests in a short time.

    /drop:
        post:
            displayName: Remove discount from cart
            description: Removes the discount associated with given discount code from the cart
            headers:
                Accept:
                    description: Specifies the expected response type. Only JSON is supported.
                    example: |
                        application/vnd.ibexa.api.DiscountCode+json
                Content-Type:
                    description: Specifies the input type. Only JSON is supported.
                    example: |
                        application/vnd.ibexa.api.DiscountCode+json
            body:
                application/vnd.ibexa.api.DiscountCode+json:
                    type: DiscountCodeWrapper
                    example: !include examples/discount_codes/apply/POST/DiscountCode.json.example
            responses:
                204:
                    description: Discount code with given discount code was removed from the cart.
                400:
                    description: Error - the request is invalid.
                404:
                    description: Error - the given cart identifier was not found
