get:
    displayName: List segment groups
    description: ibexa.segmentation.rest.segment_groups.list
/{identifier}:
    get:
        displayName: Load segment group
        description: ibexa.segmentation.rest.segment_groups.view
    /segments:
        get:
            displayName: List segment group's segments
            description: ibexa.segmentation.rest.segment_groups.list.segments
