displayName: Segments
post:
    displayName: Create a segment
    description: Creates a segment.
    headers:
        Content-Type:
            description: A SegmentCreate schema encoded in XML or JSON format.
            example: |
                application/vnd.ibexa.api.SegmentCreate+xml
                application/vnd.ibexa.api.SegmentCreate+json
        Accept:
            description: A segment is returned in XML or JSON format.
            example: |
                application/vnd.ibexa.api.Segment+xml
                application/vnd.ibexa.api.Segment+json
    body:
        application/vnd.ibexa.api.SegmentCreate+xml:
            type: SegmentCreate
            example: !include examples/segments/POST/SegmentCreate.xml.example
        application/vnd.ibexa.api.SegmentCreate+json:
            type: SegmentCreateWrapper
            example: !include examples/segments/POST/SegmentCreate.json.example
    responses:
        200:
            description: OK - returns new segment's data.
            body:
                application/vnd.ibexa.api.Segment+xml:
                    type: Segment
                    example: !include examples/segments/POST/Segment.xml.example
                application/vnd.ibexa.api.Segment+json:
                    type: SegmentWrapper
                    example: !include examples/segments/POST/Segment.json.example
        400:
            description: Error - input data validation failed.
            body:
                application/vnd.ibexa.api.ErrorMessage+xml:
                    type: ErrorMessage
                application/vnd.ibexa.api.ErrorMessage+json:
                    type: ErrorMessage
        401:
            description: Error - the user is not authorized to create segments.
            body:
                application/vnd.ibexa.api.ErrorMessage+xml:
                    type: ErrorMessage
                application/vnd.ibexa.api.ErrorMessage+json:
                    type: ErrorMessage
        404:
            description: Error - segment group with given identifier does not exist.
            body:
                application/vnd.ibexa.api.ErrorMessage+xml:
                    type: ErrorMessage
                application/vnd.ibexa.api.ErrorMessage+json:
                    type: ErrorMessage
        406:
            description: Error - input data is not acceptable, for example segment identifier is not unique.
            body:
                application/vnd.ibexa.api.ErrorMessage+xml:
                    type: ErrorMessage
                application/vnd.ibexa.api.ErrorMessage+json:
                    type: ErrorMessage
/{identifier}:
    get:
        displayName: Load segment
        description: Loads the identified segment.
        headers:
            Accept:
                description: If set, the segment is returned in XML or JSON
                example: |
                    application/vnd.ibexa.api.Segment+xml
                    application/vnd.ibexa.api.Segment+json
        responses:
            200:
                description: OK - Return the segment.
                body:
                    application/vnd.ibexa.api.Segment+xml:
                        type: Segment
                        example: !include examples/segments/identifier/GET/Segment.xml.example
                    application/vnd.ibexa.api.Segment+json:
                        type: SegmentWrapper
                        example: !include examples/segments/identifier/GET/Segment.json.example
            401:
                description: Error - the user is not authorized to load this segment.
            404:
                description: Error - the identifier doesn't match any segment.
    patch:
        displayName: Update segment data
        description: Updates the segment's data.
        headers:
            Content-Type:
                description: The SegmentUpdate schema encoded in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.SegmentUpdate+xml
                    application/vnd.ibexa.api.SegmentUpdate+json
            Accept:
                description: A segment is returned in XML or JSON format.
                example: |
                    application/vnd.ibexa.api.Segment+xml
                    application/vnd.ibexa.api.Segment+json
        body:
            application/vnd.ibexa.api.SegmentUpdate+xml:
                type: SegmentUpdate
                example: !include examples/segments/identifier/PATCH/SegmentUpdate.xml.example
            application/vnd.ibexa.api.SegmentUpdate+json:
                type: SegmentUpdateWrapper
                example: !include examples/segments/identifier/PATCH/SegmentUpdate.json.example
        responses:
            200:
                description: OK - returns updated segment's data.
                body:
                    application/vnd.ibexa.api.Segment+xml:
                        type: Segment
                        example: !include examples/segments/identifier/PATCH/Segment.xml.example
                    application/vnd.ibexa.api.Segment+json:
                        type: SegmentWrapper
                        example: !include examples/segments/identifier/PATCH/Segment.json.example
            400:
                description: Error - input data validation failed.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage
            401:
                description: Error - the user is not authorized to create segments.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage
            404:
                description: Error - segment or segment group with given identifier does not exist.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage
            406:
                description: Error - input data is not acceptable, for example segment identifier is not unique.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage
    delete:
        displayName: Delete a segment
        description: Deletes the segment.
        responses:
            204:
                description: Segment deleted.
            401:
                description: Error - the user is not authorized to delete segments.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage
            404:
                description: Error - the identifier doesn't match any segment.
                body:
                    application/vnd.ibexa.api.ErrorMessage+xml:
                        type: ErrorMessage
                    application/vnd.ibexa.api.ErrorMessage+json:
                        type: ErrorMessage