<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/datemetadatarange_aggregation.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;

$query = new Query();
$query->aggregations[] = new Aggregation\DateMetadataRangeAggregation(
    'date_metadata',
    Aggregation\DateMetadataRangeAggregation::PUBLISHED,
    [
        Range::ofDateTime(null, new DateTime('2020-06-01')),
        Range::ofDateTime(new DateTime('2020-06-01'), new DateTime('2020-12-31')),
        Range::ofDateTime(new DateTime('2020-12-31'), null),
    ]
);
