<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/productstockrange_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;

$productQuery = new ProductQuery(
    null,
    new Criterion\ProductStockRange(10, 120)
);
