<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/price_logicalor_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Price\PriceQuery;

/** @var \Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface $currencyUSD */
/** @var \Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface $currencyEUR */
$query = new PriceQuery(
    new \Ibexa\Contracts\ProductCatalog\Values\Price\Query\Criterion\LogicalOr(
        new \Ibexa\Contracts\ProductCatalog\Values\Price\Query\Criterion\Currency($currencyUSD),
        new \Ibexa\Contracts\ProductCatalog\Values\Price\Query\Criterion\Currency($currencyEUR)
    )
);
