ibexa:
    repositories:
        default: 
            checkout:
                shipment_workflow: custom_shipment_workflow

// ...

framework:
    workflows:
        custom_shipment_workflow:
            type: state_machine
            audit_trail:
                enabled: "%kernel.debug%"
            marking_store:
                type: method
                property: status
            supports:
                - Ibexa\Contracts\Checkout\Shipment\ShipmentInterface
                - Ibexa\Contracts\Checkout\Shipment\ShipmentCreateStruct
            initial_marking: pending
            places:
                pending:
                    metadata:
                        label: ibexa.shipment.workflow.place.pending.label
                        primary_color: '#F4B65F'
                        secondary_color: '#FEEED9'
                        translation_domain: ibexa_shipment_workflow
                ready_for_clearance:
                    metadata:
                        label: ibexa.shipment.workflow.place.ready_for_clearance.label
                        primary_color: '#DB2C54'
                        secondary_color: '#F7CCD6'
                        translation_domain: ibexa_shipment_workflow
                in_customs:
                    metadata:
                        label: ibexa.shipment.workflow.place.in_customs.label
                        primary_color: '#DB2C54'
                        secondary_color: '#F7CCD6'
                        translation_domain: ibexa_shipment_workflow
                passed_customs_clearance:
                    metadata:
                        label: ibexa.shipment.workflow.place.passed_customs_clearance.label
                        primary_color: '#1beb17'
                        secondary_color: '#c5f2c4'
                        translation_domain: ibexa_shipment_workflow
                shipped:
                    metadata:
                        label: ibexa.shipment.workflow.place.shipped.label
                        primary_color: '#5A5A5D'
                        secondary_color: '#E6E6ED'
                        translation_domain: ibexa_shipment_workflow
                delivered:
                    metadata:
                        label: ibexa.shipment.workflow.place.delivered.label
                        primary_color: '#2B6875'
                        secondary_color: '#CCDBDE'
                        translation_domain: ibexa_shipment_workflow
            transitions:
                prepare:
                    from:
                        - pending
                    to: ready_for_clearance
                    metadata:
                        exposed: false
                sent_to_customs:
                    from:
                        - ready_for_clearance
                    to: in_customs
                    metadata:
                        exposed: false
                clear_at_customs:
                    from:
                        - in_customs
                    to: passed_customs_clearance
                    metadata:
                        exposed: false
                send:
                    from:
                        - passed_customs_clearance
                    to: shipped
                    metadata:
                        exposed: false
                deliver:
                    from:
                        - shipped
                    to: delivered
                    metadata:
                        exposed: false
                        