-   type: action_configuration
    mode: update
    match:
        field: identifier
        value: foo_identifier

    enabled: false
    identifier: bar_identifier
    names:
        'eng-GB': 'bar_name_eng_gb'
        'ger-DE': 'bar_name_ger_de'

    descriptions:
        'ger-DE': 'bar_description_ger_de'

    action_handler_options:
        handler_option: bar

    action_type_options:
        max_length: 120
