<?php

declare(strict_types=1);
// Source: docs/search/sort_clause_reference/shipment_createdat_sort_clause.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Shipping\Shipment\ShipmentQuery;

/** @var \Ibexa\Contracts\Shipping\Shipment\Query\CriterionInterface $criteria */
$shipmentQuery = new ShipmentQuery(
    $criteria,
    [
        new \Ibexa\Contracts\Shipping\Shipment\Query\SortClause\CreatedAt(
            \Ibexa\Contracts\Shipping\Shipment\Query\SortClause\CreatedAt::SORT_ASC
        ),
    ]
);
