<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/basepricestats_aggregation.md:24
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\BasePriceStatsAggregation;

/** @var CurrencyInterface $currency */
$query = new ProductQuery();
$query->setAggregations([
    new BasePriceStatsAggregation('base_price_stats_aggregation', $currency),
]);
