#%RAML 1.0
---
title: eZ Platform (Test)
baseUri: http://localhost/
version: 2.4

/bookmark:
    get:
        queryParameters:
            offset:
                description: the offset of the result set. Default value is 0
                type: integer
            limit:
                description: the number of bookmarks returned. Default value is 25
                type: integer
        headers:
            Accept:
                description: Response format, either application/vnd.ez.api.BookmarkList+xml or application/vnd.ez.api.BookmarkList+json
        responses:
            200:
                body:
                    application/vnd.ez.api.BookmarkList+xml:
                        example: |
                            <?xml version="1.0" encoding="UTF-8"?>
                                <BookmarkList media-type="application/vnd.ez.api.BookmarkList+xml">
                                    <count>1</count>
                                    <Bookmark media-type="application/vnd.ez.api.Bookmark+xml" _href="/api/ezp/v2/bookmark/2">
                                        <Location media-type="application/vnd.ez.api.Location+xml" href="/api/ezp/v2/content/locations/1/2">
                                            <id>2</id>
                                            <priority>0</priority>
                                            <hidden>false</hidden>
                                            <invisible>false</invisible>
                                            <ParentLocation media-type="application/vnd.ez.api.Location+xml" href="/api/ezp/v2/content/locations/1"/>
                                            <pathString>/1/2/</pathString>
                                            <depth>1</depth>
                                            <childCount>4</childCount>
                                            <remoteId>f3e90596361e31d496d4026eb624c983</remoteId>
                                            <Children media-type="application/vnd.ez.api.LocationList+xml" href="/api/ezp/v2/content/locations/1/2/children"/>
                                            <Content media-type="application/vnd.ez.api.Content+xml" href="/api/ezp/v2/content/objects/1"/>
                                            <sortField>PRIORITY</sortField>
                                            <sortOrder>ASC</sortOrder>
                                            <UrlAliases media-type="application/vnd.ez.api.UrlAliasRefList+xml" href="/api/ezp/v2/content/locations/1/2/urlaliases"/>
                                            <ContentInfo media-type="application/vnd.ez.api.ContentInfo+xml" href="/api/ezp/v2/content/objects/1">
                                                <Content media-type="application/vnd.ez.api.ContentInfo+xml" href="/api/ezp/v2/content/objects/1" remoteId="9459d3c29e15006e45197295722c7ade" id="1">
                                                    <ContentType media-type="application/vnd.ez.api.ContentType+xml" href="/api/ezp/v2/content/types/1"/>
                                                    <Name>eZ Platform</Name>
                                                    <Versions media-type="application/vnd.ez.api.VersionList+xml" href="/api/ezp/v2/content/objects/1/versions"/>
                                                    <CurrentVersion media-type="application/vnd.ez.api.Version+xml" href="/api/ezp/v2/content/objects/1/currentversion"/>
                                                    <Section media-type="application/vnd.ez.api.Section+xml" href="/api/ezp/v2/content/sections/1"/>
                                                    <Locations media-type="application/vnd.ez.api.LocationList+xml" href="/api/ezp/v2/content/objects/1/locations"/>
                                                    <Owner media-type="application/vnd.ez.api.User+xml" href="/api/ezp/v2/user/users/14"/>
                                                    <lastModificationDate>2015-11-30T13:10:46+00:00</lastModificationDate>
                                                    <publishedDate>2015-11-30T13:10:46+00:00</publishedDate>
                                                    <mainLanguageCode>eng-GB</mainLanguageCode>
                                                    <currentVersionNo>9</currentVersionNo>
                                                    <alwaysAvailable>true</alwaysAvailable>
                                                    <ObjectStates media-type="application/vnd.ez.api.ContentObjectStates+xml" href="/api/ezp/v2/content/objects/1/objectstates"/>
                                                </Content>
                                            </ContentInfo>
                                        </Location>
                                    </Bookmark>
                                </BookmarkList>
                    application/vnd.ez.api.BookmarkList+json:
                        example: |
                            {
                                "BookmarkList": {
                                    "_media-type": "application/vnd.ez.api.BookmarkList+json",
                                    "count": 1,
                                    "items": [
                                        {
                                            "_media-type": "application/vnd.ez.api.Bookmark+json",
                                            "__href": "/api/ezp/v2/bookmark/2",
                                            "Location": {
                                                "_media-type": "application/vnd.ez.api.Location+json",
                                                "_href": "/api/ezp/v2/content/locations/1/2",
                                                "id": 2,
                                                "priority": 0,
                                                "hidden": false,
                                                "invisible": false,
                                                "ParentLocation": {
                                                    "_media-type": "application/vnd.ez.api.Location+json",
                                                    "_href": "/api/ezp/v2/content/locations/1"
                                                },
                                                "pathString": "/1/2/",
                                                "depth": 1,
                                                "childCount": 4,
                                                "remoteId": "f3e90596361e31d496d4026eb624c983",
                                                "Children": {
                                                    "_media-type": "application/vnd.ez.api.LocationList+json",
                                                    "_href": "/api/ezp/v2/content/locations/1/2/children"
                                                },
                                                "Content": {
                                                    "_media-type": "application/vnd.ez.api.Content+json",
                                                    "_href": "/api/ezp/v2/content/objects/1"
                                                },
                                                "sortField": "PRIORITY",
                                                "sortOrder": "ASC",
                                                "UrlAliases": {
                                                    "_media-type": "application/vnd.ez.api.UrlAliasRefList+json",
                                                    "_href": "/api/ezp/v2/content/locations/1/2/urlaliases"
                                                },
                                                "ContentInfo": {
                                                    "_media-type": "application/vnd.ez.api.ContentInfo+json",
                                                    "_href": "/api/ezp/v2/content/objects/1",
                                                    "Content": {
                                                        "_media-type": "application/vnd.ez.api.ContentInfo+json",
                                                        "_href": "/api/ezp/v2/content/objects/1",
                                                        "_remoteId": "9459d3c29e15006e45197295722c7ade",
                                                        "_id": 1,
                                                        "ContentType": {
                                                            "_media-type": "application/vnd.ez.api.ContentType+json",
                                                            "_href": "/api/ezp/v2/content/types/1"
                                                        },
                                                        "Name": "eZ Platform",
                                                        "Versions": {
                                                            "_media-type": "application/vnd.ez.api.VersionList+json",
                                                            "_href": "/api/ezp/v2/content/objects/1/versions"
                                                        },
                                                        "CurrentVersion": {
                                                            "_media-type": "application/vnd.ez.api.Version+json",
                                                            "_href": "/api/ezp/v2/content/objects/1/currentversion"
                                                        },
                                                        "Section": {
                                                            "_media-type": "application/vnd.ez.api.Section+json",
                                                            "_href": "/api/ezp/v2/content/sections/1"
                                                        },
                                                        "Locations": {
                                                            "_media-type": "application/vnd.ez.api.LocationList+json",
                                                            "_href": "/api/ezp/v2/content/objects/1/locations"
                                                        },
                                                        "Owner": {
                                                            "_media-type": "application/vnd.ez.api.User+json",
                                                            "_href": "/api/ezp/v2/user/users/14"
                                                        },
                                                        "lastModificationDate": "2015-11-30T13:10:46+00:00",
                                                        "publishedDate": "2015-11-30T13:10:46+00:00",
                                                        "mainLanguageCode": "eng-GB",
                                                        "currentVersionNo": 9,
                                                        "alwaysAvailable": true,
                                                        "ObjectStates": {
                                                            "_media-type": "application/vnd.ez.api.ContentObjectStates+json",
                                                            "_href": "/api/ezp/v2/content/objects/1/objectstates"
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    ]
                                }
                            }

            401:
                description: Error - if the user is not authorized to list bookmarks
    /{locationId}:
        post:
            description: Add given location to bookmarks of current user
            responses:
                201:
                    description: Created
                401:
                    description: Error - if the user is not authorized to given location
                404:
                    description: Error - if a given location not exists
                409:
                    description: Error - if location is already bookmarked
        head:
            description: Check if given location is bookmarked by current user
            responses:
                200:
                    description: OK - bookmarked
                401:
                    description: Error - if the user is not authorized to given location
                404:
                    description: Error - if a given location not exists / is not bookmarked
        delete:
            description: Delete given location from bookmarks of current user
            responses:
                204:
                    description: Deleted - no content
                401:
                    description: Error - if the user is not authorized to given location
                404:
                    description: Error - if a given location not exists / is not bookmarked
/content:
    get:
        description: List the root resources of the eZ Platform installation.
        headers:
            Accept:
                description: application/vnd.ez.api.Root+xml or application/vnd.ez.api.Root+json
        responses:
            200:
                body:
                    application/vnd.ez.api.Root+xml:
                        example: |
                            <?xml version="1.0" encoding="UTF-8"?>
                            <Root media-type="application/vnd.ez.api.Root+xml">
                                <content media-type="" href="/api/ezp/v2/content/objects"/>
                                <contentByRemoteId media-type="" href="/api/ezp/v2/content/objects{?remoteId}"/>
                                <contentTypes media-type="application/vnd.ez.api.ContentTypeInfoList+xml" href="/api/ezp/v2/content/types"/>
                                <contentTypeByIdentifier media-type="" href="/api/ezp/v2/content/types{?identifier}"/>
                                <contentTypeGroups media-type="application/vnd.ez.api.ContentTypeGroupList+xml" href="/api/ezp/v2/content/typegroups"/>
                                <contentTypeGroupByIdentifier media-type="" href="/api/ezp/v2/content/typegroups{?identifier}"/>
                                <users media-type="application/vnd.ez.api.UserRefList+xml" href="/api/ezp/v2/user/users"/>
                                <roles media-type="application/vnd.ez.api.RoleList+xml" href="/api/ezp/v2/user/roles"/>
                                <rootLocation media-type="application/vnd.ez.api.Location+xml" href="/api/ezp/v2/content/locations/1/2"/>
                                <rootUserGroup media-type="application/vnd.ez.api.UserGroup+xml" href="/api/ezp/v2/user/groups/1/5"/>
                                <rootMediaFolder media-type="application/vnd.ez.api.Location+xml" href="/api/ezp/v2/content/locations/1/43"/>
                                <locationByRemoteId media-type="" href="/api/ezp/v2/content/locations{?remoteId}"/>
                                <locationByPath media-type="" href="/api/ezp/v2/content/locations{?locationPath}"/>
                                <trash media-type="application/vnd.ez.api.Trash+xml" href="/api/ezp/v2/content/trash"/>
                                <sections media-type="application/vnd.ez.api.SectionList+xml" href="/api/ezp/v2/content/sections"/>
                                <views media-type="application/vnd.ez.api.RefList+xml" href="/api/ezp/v2/views"/>
                                <objectStateGroups media-type="application/vnd.ez.api.ObjectStateGroupList+xml" href="/api/ezp/v2/content/objectstategroups"/>
                                <objectStates media-type="application/vnd.ez.api.ObjectStateList+xml" href="/api/ezp/v2/content/objectstategroups/{objectStateGroupId}/objectstates"/>
                                <globalUrlAliases media-type="application/vnd.ez.api.UrlAliasRefList+xml" href="/api/ezp/v2/content/urlaliases"/>
                                <urlWildcards media-type="application/vnd.ez.api.UrlWildcardList+xml" href="/api/ezp/v2/content/urlwildcards"/>
                                <createSession media-type="application/vnd.ez.api.UserSession+xml" href="/api/ezp/v2/user/sessions"/>
                                <refreshSession media-type="application/vnd.ez.api.UserSession+xml" href="/api/ezp/v2/user/sessions/{sessionId}/refresh"/>
                            </Root>
                    application/vnd.ez.api.Root+json:
                        example: |
                            {
                                "Root": {
                                    "_media-type": "application/vnd.ez.api.Root+json",
                                    "content": {
                                        "_href": "/api/ezp/v2/content/objects",
                                        "_media-type": ""
                                    },
                                    "contentByRemoteId": {
                                        "_href": "/api/ezp/v2/content/objects{?remoteId}",
                                        "_media-type": ""
                                    },
                                    "contentTypeByIdentifier": {
                                        "_href": "/api/ezp/v2/content/types{?identifier}",
                                        "_media-type": ""
                                    },
                                    "contentTypeGroupByIdentifier": {
                                        "_href": "/api/ezp/v2/content/typegroups{?identifier}",
                                        "_media-type": ""
                                    },
                                    "contentTypeGroups": {
                                        "_href": "/api/ezp/v2/content/typegroups",
                                        "_media-type": "application/vnd.ez.api.ContentTypeGroupList+json"
                                    },
                                    "contentTypes": {
                                        "_href": "/api/ezp/v2/content/types",
                                        "_media-type": "application/vnd.ez.api.ContentTypeInfoList+json"
                                    },
                                    "createSession": {
                                        "_href": "/api/ezp/v2/user/sessions",
                                        "_media-type": "application/vnd.ez.api.UserSession+json"
                                    },
                                    "globalUrlAliases": {
                                        "_href": "/api/ezp/v2/content/urlaliases",
                                        "_media-type": "application/vnd.ez.api.UrlAliasRefList+json"
                                    },
                                    "locationByPath": {
                                        "_href": "/api/ezp/v2/content/locations{?locationPath}",
                                        "_media-type": ""
                                    },
                                    "locationByRemoteId": {
                                        "_href": "/api/ezp/v2/content/locations{?remoteId}",
                                        "_media-type": ""
                                    },
                                    "objectStateGroups": {
                                        "_href": "/api/ezp/v2/content/objectstategroups",
                                        "_media-type": "application/vnd.ez.api.ObjectStateGroupList+json"
                                    },
                                    "objectStates": {
                                        "_href": "/api/ezp/v2/content/objectstategroups/{objectStateGroupId}/objectstates",
                                        "_media-type": "application/vnd.ez.api.ObjectStateList+json"
                                    },
                                    "roles": {
                                        "_href": "/api/ezp/v2/user/roles",
                                        "_media-type": "application/vnd.ez.api.RoleList+json"
                                    },
                                    "rootLocation": {
                                        "_href": "/api/ezp/v2/content/locations/1/2",
                                        "_media-type": "application/vnd.ez.api.Location+json"
                                    },
                                    "rootMediaFolder": {
                                        "_href": "/api/ezp/v2/content/locations/1/43",
                                        "_media-type": "application/vnd.ez.api.Location+json"
                                    },
                                    "rootUserGroup": {
                                        "_href": "/api/ezp/v2/user/groups/1/5",
                                        "_media-type": "application/vnd.ez.api.UserGroup+json"
                                    },
                                    "sections": {
                                        "_href": "/api/ezp/v2/content/sections",
                                        "_media-type": "application/vnd.ez.api.SectionList+json"
                                    },
                                    "trash": {
                                        "_href": "/api/ezp/v2/content/trash",
                                        "_media-type": "application/vnd.ez.api.Trash+json"
                                    },
                                    "urlWildcards": {
                                        "_href": "/api/ezp/v2/content/urlwildcards",
                                        "_media-type": "application/vnd.ez.api.UrlWildcardList+json"
                                    },
                                    "users": {
                                        "_href": "/api/ezp/v2/user/users",
                                        "_media-type": "application/vnd.ez.api.UserRefList+json"
                                    },
                                    "views": {
                                        "_href": "/api/ezp/v2/views",
                                        "_media-type": "application/vnd.ez.api.RefList+json"
                                    },
                                    "refreshSession": {
                                        "_media-type": "application\/vnd.ez.api.UserSession+json",
                                        "_href": "\/api\/ezp\/v2\/user\/sessions\/{sessionId}\/refresh"
                                    }
                                }
                            }
    /objects:
        post:
            description: Creates a new content draft assigned to the authenticated user. If a different userId is given in the input it is assigned to the given user but this required special rights for the authenticated user (this is useful for content staging where the transfer process does not have to authenticate with the user which created the content object in the source server). The user has to publish the content if it should be visible.
            headers:
                Accept:
                    description:  application/vnd.ez.api.Content+xml or application/vnd.ez.api.Content+json or application/vnd.ez.api.ContentInfo+xml or application/vnd.ez.api.ContentInfo+json
                Content-Type:
                    description: application/vnd.ez.api.ContentCreate+json or application/vnd.ez.api.ContentCreate+xml
            body:
                application/vnd.ez.api.Content+xml:
                    schema: |
                    example:  |
                        <ContentCreate xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                          <ContentType href="/content/types/10"/>
                          <mainLanguageCode>eng-US</mainLanguageCode>
                          <LocationCreate>
                            <ParentLocation href="/content/locations/1/4/89" />
                            <priority>0</priority>
                            <hidden>false</hidden>
                            <sortField>PATH</sortField>
                            <sortOrder>ASC</sortOrder>
                          </LocationCreate>
                          <Section href="/content/sections/4"/>
                          <alwaysAvailable>true</alwaysAvailable>
                          <remoteId>remoteId12345678</remoteId>
                          <fields>
                            <field>
                              <fieldDefinitionIdentifier>title</fieldDefinitionIdentifier>
                              <languageCode>eng-US</languageCode>
                              <fieldValue>This is a title</fieldValue>
                            </field>
                            <field>
                              <fieldDefinitionIdentifier>summary</fieldDefinitionIdentifier>
                              <languageCode>eng-US</languageCode>
                              <fieldValue>This is a summary</fieldValue>
                            </field>
                            <field>
                              <fieldDefinitionIdentifier>authors</fieldDefinitionIdentifier>
                              <languageCode>eng-US</languageCode>
                              <fieldValue>
                                <value>
                                  <value key="name">John Doe</value>
                                  <value key="email">john.doe@example.net</value>
                                </value>
                                <value>
                                  <value key="name">Bruce Willis</value>
                                  <value key="email">bruce.willis@example.net</value>
                                </value>
                              </fieldValue>
                            </field>
                          </fields>
                        </ContentCreate>
                application/vnd.ez.api.Content+json:
                    schema: |
                    example:  |
                        {
                          "ContentCreate": {
                            "ContentType": {
                              "_href": "/content/types/10"
                            },
                            "mainLanguageCode": "eng-US",
                            "LocationCreate": {
                              "ParentLocation": {
                                "_href": "/content/locations/1/4/89"
                              },
                              "priority": "0",
                              "hidden": false,
                              "sortField": "PATH",
                              "sortOrder": "ASC"
                            },
                            "Section": {
                              "_href": "/content/sections/4"
                            },
                            "alwaysAvailable": true,
                            "remoteId": "remoteId12345678",
                            "fields": {
                              "field": [
                                {
                                  "fieldDefinitionIdentifier": "title",
                                  "languageCode": "eng-US",
                                  "fieldValue": "This is a title"
                                },
                                {
                                  "fieldDefinitionIdentifier": "summary",
                                  "languageCode": "eng-US",
                                  "fieldValue": "This is a summary"
                                },
                                {
                                  "fieldDefinitionIdentifier": "authors",
                                  "languageCode": "eng-US",
                                  "fieldValue": [
                                     {
                                       "name": "John Doe",
                                       "email": "john.doe@example.net"
                                     },
                                     {
                                       "name": "Bruce Willis",
                                       "email": "bruce.willis@example.net"
                                     }
                                  ]
                                }
                              ]
                            }
                          }
                        }
            responses:
                201:
                    body:
                        application/vnd.ez.api.Content+xml:
                            example: |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <Content href="/content/objects/23" id="23"
                                  media-type="application/vnd.ez.api.Content+xml" remoteId="remoteId12345678" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                                  <ContentType href="/content/types/10" media-type="application/vnd.ez.api.ContentType+xml" />
                                  <Name>This is a title</Name>
                                  <Versions href="/content/objects/23/versions" media-type="application/vnd.ez.api.VersionList+xml" />
                                  <CurrentVersion href="/content/objects/23/currentversion"
                                    media-type="application/vnd.ez.api.Version+xml">
                                    <Version href="/content/objects/23/versions/1" media-type="application/vnd.ez.api.Version+xml">
                                      <VersionInfo>
                                        <id>123</id>
                                        <versionNo>1</versionNo>
                                        <status>DRAFT</status>
                                        <modificationDate>2012-02-12T12:30:00</modificationDate>
                                        <Creator href="/user/users/14" media-type="application/vnd.ez.api.User+xml" />
                                        <creationDate>2012-02-12T12:30:00</creationDate>
                                        <initialLanguageCode>eng-US</initialLanguageCode>
                                        <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                      </VersionInfo>
                                      <fields>
                                        <field>
                                          <id>1234</id>
                                          <fieldDefinitionIdentifier>title</fieldDefinitionIdentifier>
                                          <languageCode>eng-UK</languageCode>
                                          <fieldValue>This is a title</fieldValue>
                                        </field>
                                        <field>
                                          <id>1235</id>
                                          <fieldDefinitionIdentifier>summary</fieldDefinitionIdentifier>
                                          <languageCode>eng-UK</languageCode>
                                          <fieldValue>This is a summary</fieldValue>
                                        </field>
                                        <field>
                                          <fieldDefinitionIdentifier>authors</fieldDefinitionIdentifier>
                                          <languageCode>eng-US</languageCode>
                                          <fieldValue>
                                            <value>
                                              <value key="name">John Doe</value>
                                              <value key="email">john.doe@example.net</value>
                                            </value>
                                            <value>
                                              <value key="name">Bruce Willis</value>
                                              <value key="email">bruce.willis@example.net</value>
                                            </value>
                                          </fieldValue>
                                        </field>
                                      </fields>
                                      <Relations href="/content/objects/23/versions/1/relations" media-type="application/vnd.ez.api.RelationList+xml" />
                                    </Version>
                                  </CurrentVersion>
                                  <Section href="/content/sections/4" media-type="application/vnd.ez.api.Section+xml" />
                                  <MainLocation href="/content/locations/1/4/65" media-type="application/vnd.ez.api.Location+xml" />
                                  <Locations href="/content/objects/23/locations" media-type="application/vnd.ez.api.LocationList+xml" />
                                  <Owner href="/user/users/14" media-type="application/vnd.ez.api.User+xml" />
                                  <lastModificationDate>2012-02-12T12:30:00</lastModificationDate>
                                  <mainLanguageCode>eng-US</mainLanguageCode>
                                  <currentVersionNo>1</currentVersionNo>
                                  <alwaysAvailable>true</alwaysAvailable>
                                </Content>
                        application/vnd.ez.api.Content+json:
                            example: |
                                {
                                  "Content": {
                                    "_href": "/content/objects/23",
                                    "_id": "23",
                                    "_media-type": "application/vnd.ez.api.Content+json",
                                    "_remoteId": "qwert123",
                                    "ContentType": {
                                      "_href": "/content/types/10",
                                      "_media-type": "application/vnd.ez.api.ContentType+json"
                                    },
                                    "name": "This is a title",
                                    "Versions": {
                                      "_href": "/content/objects/23/versions",
                                      "_media-type": "application/vnd.ez.api.VersionList+json"
                                    },
                                    "CurrentVersion": {
                                      "_href": "/content/objects/23/currentversion",
                                      "_media-type": "application/vnd.ez.api.Version+json",
                                      "Version": {
                                        "_href": "/content/objects/23/versions/1",
                                        "_media-type": "application/vnd.ez.api.Version+json",
                                        "VersionInfo": {
                                          "id": "123",
                                          "versionNo": "1",
                                          "status": "DRAFT",
                                          "modificationDate": "2012-02-12T12:30:00",
                                          "creator": {
                                            "_href": "/user/users/14",
                                            "_media-type": "application/vnd.ez.api.User+json"
                                          },
                                          "creationDate": "2012-02-12T12:30:00",
                                          "initialLanguageCode": "eng-US",
                                          "Content": {
                                            "_href": "/content/objects/23",
                                            "_media-type": "application/vnd.ez.api.ContentInfo+json"
                                          }
                                        },
                                        "fields": {
                                          "field": [
                                            {
                                              "id": "1234",
                                              "fieldDefinitionIdentifier": "title",
                                              "languageCode": "eng-UK",
                                              "fieldValue": "This is a title"
                                            },
                                            {
                                              "id": "1235",
                                              "fieldDefinitionIdentifier": "summary",
                                              "languageCode": "eng-UK",
                                              "fieldValue": "This is a summary"
                                            },
                                            {
                                              "fieldDefinitionIdentifier": "authors",
                                              "languageCode": "eng-US",
                                              "fieldValue":
                                              [
                                                {
                                                  "name": "John Doe",
                                                  "email": "john.doe@example.net"
                                                },
                                                {
                                                  "name": "Bruce Willis",
                                                  "email": "bruce.willis@example.net"
                                                }
                                              ]
                                            }
                                          ]
                                        }
                                      }
                                    },
                                    "Section": {
                                      "_href": "/content/sections/4",
                                      "_media-type": "application/vnd.ez.api.Section+json"
                                    },
                                    "MainLocation": {
                                      "_href": "/content/locations/1/4/65",
                                      "_media-type": "application/vnd.ez.api.Location+json"
                                    },
                                    "Locations": {
                                      "_href": "/content/objects/23/locations",
                                      "_media-type": "application/vnd.ez.api.LocationList+json"
                                    },
                                    "Owner": {
                                      "_href": "/user/users/14",
                                      "_media-type": "application/vnd.ez.api.User+json"
                                    },
                                    "lastModificationDate": "2012-02-12T12:30:00",
                                    "mainLanguageCode": "eng-US",
                                    "currentVersionNo": "1",
                                    "alwaysAvailable": true
                                  }
                                }
                400:
                    description: Error - if the Input does not match the input schema definition or the validation on a field fails
                401:
                    description: Error - if the user is not authorized to create this object in this location
                404:
                    description: Error - if a parent location is specified in the request body and it does not exist
        get:
            description: Loads the content for a given remote ID
            queryParameters:
                remoteId:
                    description: The remote ID of the content. If present the content with the given remote ID is returned
            responses:
                307:
                    description: Temporary redirect
                404:
                    description: Error - if the content with the given remote ID does not exist
    /objects/{contentId}:
        get:
            description: Loads the content object for the given ID. Depending on the Accept header the current version is embedded (i.e the current published version or if not exists the draft of the authenticated user)
            queryParameters:
                 languages:
                    description: Restricts the output of translatable fields to the given languages
                    type: comma separated list
            headers:
                Accept:
                    description: application/vnd.ez.api.Content+xml or application/vnd.ez.api.Content+json or application/vnd.ez.api.ContentInfo+xml or application/vnd.ez.api.ContentInfo+json
                If-None-Match:
                    description: <etag> If the provided etag matches the current etag then a "304 Not Modified" is returned. The etag changes if the meta data was changed - this happens also if there is a new published version.
            responses:
                200:
                    body:
                        application/vnd.ez.api.Content+xml:
                            example: |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <Content href="/content/objects/23" id="23"
                                  media-type="application/vnd.ez.api.Content+xml" remoteId="qwert123">
                                  <ContentType href="/content/types/10" media-type="application/vnd.ez.api.ContentType+xml" />
                                  <Name>This is a title</Name>
                                  <Versions href="/content/objects/23/versions" media-type="application/vnd.ez.api.VersionList+xml" />
                                  <CurrentVersion href="/content/objects/23/currentversion"
                                    media-type="application/vnd.ez.api.Version+xml"/>
                                  <Section href="/content/sections/4" media-type="application/vnd.ez.api.Section+xml" />
                                  <MainLocation href="/content/locations/1/4/65" media-type="application/vnd.ez.api.Location+xml" />
                                  <Locations href="/content/objects/23/locations" media-type="application/vnd.ez.api.LocationList+xml" />
                                  <Owner href="/user/users/14" media-type="application/vnd.ez.api.User+xml" />
                                  <lastModificationDate>2012-02-12T12:30:00</lastModificationDate>
                                  <publishedDate>2012-02-12T15:30:00</publishedDate>
                                  <mainLanguageCode>eng-US</mainLanguageCode>
                                  <currentVersionNo>1</currentVersionNo>
                                  <alwaysAvailable>true</alwaysAvailable>
                                </Content>
                401:
                    description: Error - if the user is not authorized to read this object. This could also happen if there is no published version yet and another user owns a draft of this content
                404:
                    description: Error - if the ID is not found
        post:
            description: PATCH or POST with header X-HTTP-Method-Override PATCH. This method updates the content metadata which is independent from a version.
            headers:
                 Accept:
                    description: Response format, either application/vnd.ez.api.ContentInfo+xml or application/vnd.ez.api.ContentInfo+json
                 If-match:
                     description: <etag> Causes to patch only if the specified etag is the current one. Otherwise a 412 is returned.
                 Content-Type:
                    description: Response format, either application/vnd.ez.api.ContentUpdate+json or application/vnd.ez.api.ContentUpdate+xml
            body:
                application/vnd.ez.api.ContentInfo+xml:
                    schema: |
                    example: |
                        <?xml version="1.0" encoding="UTF-8"?>
                        <ContentUpdate>
                          <mainLanguageCode>ger-DE</mainLanguageCode>
                          <Section href="/content/sections/3"/>
                          <MainLocation href="/content/locations/1/13/55"/>
                          <Owner href="/user/users/13"/>
                          <alwaysAvailable>false</alwaysAvailable>
                          <remoteId>qwert4321</remoteId>
                        </ContentUpdate>
            responses:
                200:
                    body:
                        application/vnd.ez.api.ContentUpdate+xml:
                            example: |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <Content href="/content/objects/23" id="23"
                                  media-type="application/vnd.ez.api.Content+xml" remoteId="qwert4321">
                                  <ContentType href="/content/types/10" media-type="application/vnd.ez.api.ContentType+xml" />
                                  <Name>This is a title</Name>
                                  <Versions href="/content/objects/23/versions" media-type="application/vnd.ez.api.VersionList+xml" />
                                  <CurrentVersion href="/content/objects/23/currentversion"
                                    media-type="application/vnd.ez.api.Version+xml"/>
                                  <Section href="/content/sections/3" media-type="application/vnd.ez.api.Section+xml" />
                                  <MainLocation href="/content/locations/1/13/55" media-type="application/vnd.ez.api.Location+xml" />
                                  <Locations href="/content/objects/23/locations" media-type="application/vnd.ez.api.LocationList+xml" />
                                  <Owner href="/user/users/13" media-type="application/vnd.ez.api.User+xml" />
                                  <lastModificationDate>2012-02-12T12:30:00</lastModificationDate>
                                  <publishedDate>2012-02-12T15:30:00</publishedDate>
                                  <mainLanguageCode>ger-DE</mainLanguageCode>
                                  <currentVersionNo>1</currentVersionNo>
                                  <alwaysAvailable>false</alwaysAvailable>
                                </Content>
                400:
                    description: Error - if the Input does not match the input schema definition
                401:
                    description: Error - if the user is not authorized to update this object
                404:
                    description: Error - if the content id does not exist
                412:
                    description: Error - if the current ETag does not match with the provided one in the If-Match header
                415:
                    description: Error - if the media-type is not one of those specified in Headers

        patch:
            description: PATCH or POST with header X-HTTP-Method-Override PATCH. This method updates the content metadata which is independent from a version.
            headers:
                 Accept:
                    description: application/vnd.ez.api.ContentInfo+xml or application/vnd.ez.api.ContentInfo+json
                 If-match:
                     description: <etag> Causes to patch only if the specified etag is the current one. Otherwise a 412 is returned.
                 Content-Type:
                    description: Response format, either application/vnd.ez.api.ContentUpdate+json or application/vnd.ez.api.ContentUpdate+xml
            responses:
                description: Same as POST /content/objects/<ID>
        delete:
            description: The content is deleted. If the content has locations (which is required in 4.x) on delete all locations assigned the content object are deleted via delete subtree.
            responses:
                204:
                    description: The content is deleted.
                404:
                    description: Error - content object was not found
                401:
                    description: Error - if the user is not authorized to delete this object
        copy:
            description: COPY or POST with header X-HTTP-Method-Override COPY. Creates a new content object as copy under the given parent location given in the destination header.
            headers:
                destination: A location resource to which the content object should be copied.
            responses:
                201:
                    description: Copy created
                401:
                    description: Error - if the user is not authorized to copy this object to the given location
                404:
                    description: Error - if the source or destination resource do not exist.
    /objects/{id}/translations/{languageCode}:
        delete:
            description: Permanently delete a Translation from all Versions of a Content
            responses:
                204:
                    description: No Content
                401:
                    description: Error - if the user is not authorized to delete Content (content/remove policy)
                404:
                    description: Error - if the Content item was not found
                406:
                    description: Error - if the given Translation does not exist for the Content
                409:
                    description: Error - if the specified Translation is the only one any Version has or is the Main Translation
    /objects/{id}/currentversion:
        get:
            description: Redirects to the current version of the content object
            responses:
                307:
                    description: Temporary redirect
                404:
                    description: Error - if the resource does not exist
    /objects/{id}/versions:
        get:
            description: Returns a list of all versions of the content. This method does not include fields and relations in the Version elements of the response.
            headers:
                Accept:
                    description: application/vnd.ez.api.VersionList+xml or application/vnd.ez.api.VersionList+json
            responses:
                200:
                    body:
                        application/vnd.ez.api.VersionList+xml:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <VersionList href="/content/objects/23/versions" media-type="application/vnd.ez.api.VersionList+xml">
                                  <VersionItem>
                                    <Version href="/content/objects/23/versions/1" media-type="application/vnd.ez.api.Version+xml"/>
                                    <VersionInfo>
                                      <id>12</id>
                                      <versionNo>1</versionNo>
                                      <status>ARCHIVED</status>
                                      <modificationDate>2012-02-15T12:00:00</modificationDate>
                                      <Creator href="/user/users/8" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>22012-02-15T12:00:00</creationDate>
                                      <initialLanguageCode>eng-US</initialLanguageCode>
                                      <names>
                                        <value languageCode="eng-US">Name</value>
                                      </names>
                                      <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                  </VersionItem>
                                  <VersionItem>
                                    <Version href="/content/objects/23/versions/2" media-type="application/vnd.ez.api.Version+xml"/>
                                    <VersionInfo>
                                      <id>22</id>
                                      <versionNo>2</versionNo>
                                      <status>PUBLISHED</status>
                                      <modificationDate>2012-02-17T12:00:00</modificationDate>
                                      <Creator href="/user/users/8" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>22012-02-17T12:00:00</creationDate>
                                      <initialLanguageCode>eng-US</initialLanguageCode>
                                      <names>
                                        <value languageCode="eng-US">Name</value>
                                      </names>
                                      <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                  </VersionItem>
                                  <VersionItem>
                                    <Version href="/content/objects/23/versions/3" media-type="application/vnd.ez.api.Version+xml"/>
                                    <VersionInfo>
                                      <id>44</id>
                                      <versionNo>3</versionNo>
                                      <status>DRAFT</status>
                                      <modificationDate>2012-02-19T12:00:00</modificationDate>
                                      <Creator href="/user/users/65" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>22012-02-19T12:00:00</creationDate>
                                      <initialLanguageCode>fra-FR</initialLanguageCode>
                                      <names>
                                        <value languageCode="eng-US">Name</value>
                                        <value languageCode="fra-FR">Nom</value>
                                      </names>
                                      <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                  </VersionItem>
                                  <VersionItem>
                                    <Version href="/content/objects/23/versions/4" media-type="application/vnd.ez.api.Version+xml"/>
                                    <VersionInfo>
                                      <id>45</id>
                                      <versionNo>4</versionNo>
                                      <status>DRAFT</status>
                                      <modificationDate>2012-02-20T12:00:00</modificationDate>
                                      <Creator href="/user/users/44" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>22012-02-20T12:00:00</creationDate>
                                      <initialLanguageCode>ger-DE</initialLanguageCode>
                                      <names>
                                        <value languageCode="eng-US">Name</value>
                                        <value languageCode="ger-DE">Name</value>
                                      </names>
                                      <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                  </VersionItem>
                                </VersionList>
                401:
                    description: Error - if the user has no permission to read the versions
    /objects/{id}/versions/{versionNo}:
        get:
            description: Loads a specific version of a content object. This method returns fields and relations
            queryParameters:
                fields:
                    description: Fields which should be returned in the response (see Content)
                    type: Comma separated list
                responseGroups:
                    description: Alternative: comma separated lists of predefined field groups (see REST API Spec v1)
                    type: Comma separated lists
                languages:
                    description: Restricts the output of translatable fields to the given languages
                    type: Comma separated list
            headers:
                If-None-Match:
                    description: <etag> Only return the version if the given <etag> is the not current one otherwise a 304 is returned.
                Accept:
                    description: application/vnd.ez.api.Version+xml or application/vnd.ez.api.Version+json
            responses:
                200:
                    body:
                        application/vnd.ez.api.Version+xml:
                            example: |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <Version href="/content/objects/23/versions/4" media-type="application/vnd.ez.api.Version+xml"
                                         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
                                  <VersionInfo>
                                    <id>45</id>
                                    <versionNo>4</versionNo>
                                    <status>DRAFT</status>
                                    <modificationDate>2012-02-20T12:00:00</modificationDate>
                                    <Creator href="/user/users/44" media-type="application/vnd.ez.api.User+xml" />
                                    <creationDate>22012-02-20T12:00:00</creationDate>
                                    <initialLanguageCode>ger-DE</initialLanguageCode>
                                    <names>
                                      <value languageCode="ger-DE">Name</value>
                                    </names>
                                    <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                  </VersionInfo>
                                  <Fields>
                                    <field>
                                      <id>1234</id>
                                      <fieldDefinitionIdentifier>title</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>Titel</fieldValue>
                                    </field>
                                    <field>
                                      <id>1235</id>
                                      <fieldDefinitionIdentifier>summary</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>Dies ist eine Zusammenfassungy</fieldValue>
                                    </field>
                                    <field>
                                      <fieldDefinitionIdentifier>authors</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>
                                        <value>
                                          <value key="name">Karl Mustermann</value>
                                          <value key="email">karl.mustermann@example.net</value>
                                        </value>
                                      </fieldValue>
                                    </field>
                                  </Fields>
                                  <Relations  href="/content/objects/23/relations"  media-type="application/vnd.ez.api.RelationList+xml">>
                                    <Relation href="/content/objects/23/relations/32" media-type="application/vnd.ez.api.Relation+xml">
                                      <SourceContent href="/content/objects/23"
                                        media-type="application/vnd.ez.api.ContentInfo+xml" />
                                      <DestinationContent href="/content/objects/45"
                                        media-type="application/vnd.ez.api.ContentInfo+xml" />
                                      <RelationType>COMMON</RelationType>
                                    </Relation>
                                  </Relations>
                304:
                    description: Error - if the etag does not match the current one
                401:
                    description: Error - if the user is not authorized to read this object
                404:
                    description: Error - if the ID or version is not found
        post:
            description: A specific draft is updated - PATCH or POST with header X-HTTP-Method-Override "PATCH".
            queryParameters:
                languages:
                    description: restricts the output of translatable fields to the given languages
                    type: Comma separated list
            headers:
                Accept:
                    description: application/vnd.ez.api.Version+xml or application/vnd.ez.api.Version+json
                If-match:
                    description: Causes to patch only if the specified etag is the current one
                Content-Type:
                    description: application/vnd.ez.api.VersionUpdate+json or application/vnd.ez.api.VersionUpdate+xml
            body:
              application/vnd.ez.api.Version+xml:
                  schema:
                  example:  |
                      <?xml version="1.0" encoding="UTF-8"?>
                      <VersionUpdate xmlns:p="http://ez.no/API/Values"
                        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                        xsi:schemaLocation="http://ez.no/API/Values ../VersionUpdate.xsd ">
                        <modificationDate>2001-12-31T12:00:00</modificationDate>
                        <initialLanguageCode>ger-DE</initialLanguageCode>
                        <fields>
                          <field>
                            <id>1234</id>
                            <fieldDefinitionIdentifier>title</fieldDefinitionIdentifier>
                            <languageCode>ger-DE</languageCode>
                            <fieldValue>Neuer Titel</fieldValue>
                          </field>
                          <field>
                            <id>1235</id>
                            <fieldDefinitionIdentifier>summary</fieldDefinitionIdentifier>
                            <languageCode>ger-DE</languageCode>
                            <fieldValue>Dies ist eine neue Zusammenfassungy</fieldValue>
                          </field>
                        </fields>
                      </VersionUpdate>
            responses:
                200:
                    body:
                        application/vnd.ez.api.Version+xml:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <Version href="/content/objects/23/versions/4" media-type="application/vnd.ez.api.Version+xml">
                                  <VersionInfo>
                                    <id>45</id>
                                    <versionNo>4</versionNo>
                                    <status>DRAFT</status>
                                    <modificationDate>2012-02-20T12:00:00</modificationDate>
                                    <Creator href="/user/users/44" media-type="application/vnd.ez.api.User+xml" />
                                    <creationDate>22012-02-20T12:00:00</creationDate>
                                    <initialLanguageCode>ger-DE</initialLanguageCode>
                                    <names>
                                      <value languageCode="ger-DE">Neuer Titel</value>
                                    </names>
                                    <Content href="/content/objects/23" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                  </VersionInfo>
                                  <Fields>
                                    <field>
                                      <id>1234</id>
                                      <fieldDefinitionIdentifier>title</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>Neuer Titel</fieldValue>
                                    </field>
                                    <field>
                                      <id>1235</id>
                                      <fieldDefinitionIdentifier>summary</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>Dies ist eine neuse Zusammenfassungy</fieldValue>
                                    </field>
                                    <field>
                                      <fieldDefinitionIdentifier>authors</fieldDefinitionIdentifier>
                                      <languageCode>ger-DE</languageCode>
                                      <fieldValue>
                                        <authors>
                                          <author name="Klaus Mustermann" email="klaus.mustermann@example.net" />
                                        </authors>
                                      </fieldValue>
                                    </field>
                                  </Fields>
                                  <Relations>
                                    <Relation href="/content/object/32/versions/2/relations/43" media-type="application/vnd.ez.api.Relation+xml">
                                      <SourceContent href="/content/objects/23"
                                        media-type="application/vnd.ez.api.ContentInfo+xml" />
                                      <DestinationContent href="/content/objects/45"
                                        media-type="application/vnd.ez.api.ContentInfo+xml" />
                                      <RelationType>COMMON</RelationType>
                                    </Relation>
                                  </Relations>
                                </Version>
                400:
                    description: Error - if the Input does not match the input schema definition, In this case the response contains an ErrorMessage
                401:
                    description: Error - if the user is not authorized to update this version
                403:
                    description: Error - if the version is not allowed to change - i.e is not a DRAFT
                404:
                    description: Error - if the content id or version id does not exist
                412:
                    description: Error - if the current ETag does not match with the provided one in the If-Match header
    /objects/{id}/versions/{no}:
        post:
            description: COPY or POST with header X-HTTP-Method-Override COPY. The system creates a new draft version as a copy from the given version
            headers:
                Accept: application/vnd.ez.api.Version+xml or application/vnd.ez.api.Version+json
            responses:
                201:
                    description: Created
                401:
                    description: Error - if the user is not authorized to update this object
                404:
                    description: Error - if the content object was not found
    /objects/{id}/currentversion:
        post:
            description: COPY or POST with header X-HTTP-Method-Override: COPY. The system creates a new draft version as a copy from the current version
            headers:
              Accept: application/vnd.ez.api.Version+xml or application/vnd.ez.api.Version+json
            responses:
                201:
                    description: Created
                401:
                    description: Error - if the user is not authorized to update this object
                403:
                    description: Error - if the current version is already a draft
                404:
                    description: Error - if the content object was not found
/user:
    /groups:
        get:
            description: Load user groups for either an id or remoteId or role.
            queryParameters:
                roleId:
                    description: lists user groups assigned to the given role
                id:
                    description: retrieves the user group for the given ID
                remoteID:
                    description: retrieves the user group for the given remoteId
            headers:
                Accept: application/vnd.ez.api.UserGroupList+xml or application/vnd.ez.api.UserGroupList+json or application/vnd.ez.api.UserGroupRefList+xml or application/vnd.ez.api.UserGroupRefList+json
            responses:
                200:
                    body:
                        application/vnd.ez.api.UserGroup+xml:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <UserGroup href="/user/groups/1/5" id="5" media-type="application/vnd.ez.api.UserGroup+xml" remoteId="remoteId-qwert001">
                                  <ContentType href="/content/types/5" media-type="application/vnd.ez.api.ContentType+xml" />
                                  <name>Users</name>
                                  <Versions href="/content/objects/4/versions" media-type="application/vnd.ez.api.VersionList+xml" />
                                  <Section href="/content/sections/4" media-type="application/vnd.ez.api.Section+xml" />
                                  <MainLocation href="/content/locations/1/5" media-type="application/vnd.ez.api.Location+xml" />
                                  <Locations href="/content/objects/4/locations" media-type="application/vnd.ez.api.LocationList+xml" />
                                  <Owner href="/user/users/13" media-type="application/vnd.ez.api.User+xml" />
                                  <publishDate>2011-02-31T16:00:00</publishDate>
                                  <lastModificationDate>2011-02-31T16:00:00</lastModificationDate>
                                  <mainLanguageCode>eng-UK</mainLanguageCode>
                                  <alwaysAvailable>true</alwaysAvailable>
                                  <Content>
                                    <VersionInfo>
                                      <id>22</id>
                                      <versionNo>1</versionNo>
                                      <status>PUBLISHED</status>
                                      <modificationDate>2011-02-31T16:00:00</modificationDate>
                                      <Creator href="/user/users/14" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>2011-02-31T16:00:00</creationDate>
                                      <initialLanguageCode>eng-UK</initialLanguageCode>
                                      <Content href="/content/objects/4" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                    <Fields>
                                      <field>
                                        <id>1234</id>
                                        <fieldDefinitionIdentifier>name</fieldDefinitionIdentifier>
                                        <languageCode>eng-UK</languageCode>
                                        <fieldValue>Users</fieldValue>
                                      </field>
                                      <field>
                                        <id>1235</id>
                                        <fieldDefinitionIdentifier>description</fieldDefinitionIdentifier>
                                        <languageCode>eng-UK</languageCode>
                                        <fieldValue>Main Group</fieldValue>
                                      </field>
                                    </Fields>
                                    <Relations />
                                  </Content>
                                  <SubGroups href="/user/groups/1/5/subgroups" media-type="application/vnd.ez.api.UserGroupList+xml"/>
                                  <Users href="/user/groups/1/5/users" media-type="application/vnd.ez.api.UserList+xml"/>
                                  <Roles href="/user/groups/1/5/roles" media-type="application/vnd.ez.api.RoleList+xml"/>
                                </UserGroup>
                401:
                    description: Error - if the user has no permission to read user groups
    /groups/{path}/subgroups:
        post:
            description: Creates a new user group under the given parent. To create a top level group use /user/groups/subgroups
            headers:
                Accept: application/vnd.ez.api.UserGroup+xml or application/vnd.ez.api.UserGroup+json
                Content-Type: application/vnd.ez.api.UserGroupCreate+json or application/vnd.ez.api.UserGroupCreate+xml
            body:
                application/vnd.ez.api.UserGroup+xml:
                    schema:
                    example:  |
                        <?xml version="1.0" encoding="UTF-8"?>
                        <UserGroupCreate>
                          <mainLanguageCode>eng-US</mainLanguageCode>
                          <remoteId>remoteId-qwert098</remoteId>
                          <fields>
                            <field>
                              <fieldDefinitionIdentifier>name</fieldDefinitionIdentifier>
                              <languageCode>eng-US</languageCode>
                              <fieldValue>UserGroup</fieldValue>
                            </field>
                            <field>
                              <fieldDefinitionIdentifier>description</fieldDefinitionIdentifier>
                              <languageCode>eng-US</languageCode>
                              <fieldValue>This is the description of the user group</fieldValue>
                            </field>
                          </fields>
                        </UserGroupCreate>
            responses:
                201:
                    body:
                        application/vnd.ez.api.UserGroup+xml:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <UserGroup href="/user/groups/1/5/65" id="65" media-type="application/vnd.ez.api.UserGroup+xml" remoteId="remoteId-qwert543">
                                  <ContentType href="/content/types/5" media-type="application/vnd.ez.api.ContentType+xml" />
                                  <name>UserGroup</name>
                                  <Versions href="/content/objects/123/versions" media-type="application/vnd.ez.api.VersionList+xml" />
                                  <Section href="/content/sections/4" media-type="application/vnd.ez.api.Section+xml" />
                                  <MainLocation href="/content/locations/1/5/65" media-type="application/vnd.ez.api.Location+xml" />
                                  <Locations href="/content/objects/123/locations" media-type="application/vnd.ez.api.LocationList+xml" />
                                  <Owner href="/user/users/13" media-type="application/vnd.ez.api.User+xml" />
                                  <publishDate>2012-02-31T16:00:00</publishDate>
                                  <lastModificationDate>2012-02-31T16:00:00</lastModificationDate>
                                  <mainLanguageCode>eng-UK</mainLanguageCode>
                                  <alwaysAvailable>true</alwaysAvailable>
                                  <Content>
                                    <VersionInfo>
                                      <id>123</id>
                                      <versionNo>2</versionNo>
                                      <status>PUBLISHED</status>
                                      <modificationDate>2012-02-31T16:00:00</modificationDate>
                                      <Creator href="/user/users/14" media-type="application/vnd.ez.api.User+xml" />
                                      <creationDate>2012-02-31T16:00:00</creationDate>
                                      <initialLanguageCode>eng-UK</initialLanguageCode>
                                      <Content href="/content/objects/123" media-type="application/vnd.ez.api.ContentInfo+xml" />
                                    </VersionInfo>
                                    <Fields>
                                      <field>
                                        <id>1234</id>
                                        <fieldDefinitionIdentifier>name</fieldDefinitionIdentifier>
                                        <languageCode>eng-UK</languageCode>
                                        <fieldValue>UserGroup</fieldValue>
                                      </field>
                                      <field>
                                        <id>1235</id>
                                        <fieldDefinitionIdentifier>description</fieldDefinitionIdentifier>
                                        <languageCode>eng-UK</languageCode>
                                        <fieldValue>This is the description of the user group</fieldValue>
                                      </field>
                                    </Fields>
                                    <Relations />
                                  </Content>
                                  <ParentUserGroup href="/user/groups/1/5" media-type="application/vnd.ez.api.UserGroup+xml" />
                                  <SubGroups href="/user/groups/1/5/65/subgroups" media-type="application/vnd.ez.api.UserGroupList+xml"/>
                                  <Users href="/user/groups/1/5/65/users" media-type="application/vnd.ez.api.UserList+xml"/>
                                  <Roles href="/user/groups/1/5/65/roles" media-type="application/vnd.ez.api.RoleList+xml"/>
                                </UserGroup>
                400:
                    description: Error - if the Input does not match the input schema definition, In this case the response contains an ErrorMessage
                401:
                    description: Error - if the user is not authorized to create this user group
    /users:
        get:
            description: Load users either for a given remoteId or role
            queryParameters:
                roleId:
                    description: lists users assigned to the given role (ex: GET /user/users?roleId=/user/roles/1)
                remoteId:
                    description: retrieves the user for the given remoteId (ex: GET /user/users?remoteId=55dd9713db75145f374bbd0b4f60ad29)
                login:
                    description: retrieves the user for the given login (ex: GET /user/users?login=editor)
                email:
                    description: lists users with the given email (ex: GET /user/users?email=editor@example.com)
            headers:
                Accept: application/vnd.ez.api.UserList+xml or application/vnd.ez.api.UserList+json or application/vnd.ez.api.UserRefList+xml or application/vnd.ez.api.UserRefList+json
            responses:
                200:
                    description: OK - Loads users either for a given remoteId or role
                404:
                    description: If there are no visibile users matching the filter
        head:
            description: Verifies if there are users matching the given filter.
            queryParameters:
                roleId:
                    description: lists users assigned to the given role (ex: GET /user/users?roleId=/user/roles/1)
                remoteId:
                    description: retrieves the user for the given remoteId (ex: GET /user/users?remoteId=55dd9713db75145f374bbd0b4f60ad29)
                login:
                    description: retrieves the user for the given login (ex: GET /user/users?login=editor)
                email:
                    description: lists users with the given email (ex: GET /user/users?email=editor@example.com)
            responses:
                200:
                    description: OK
                404:
                    description: Error - if there are no visibile users matching the filter
    /users/{ID}/groups:
        get:
            description: Returns a list of user groups the user belongs to. The returned list includes the resources for unassigning a user group if the user is in multiple groups.
            queryParameters:
               offset:
                    description: the offset of the result set
                    type: integer
               limit:
                    description: the number of bookmarks returned
                    type: integer
            headers:
                Accept:
                    description: application/vnd.ez.api.UserGroupRefList+xml or application/vnd.ez.api.UserGroupRefList+json
            responses:
                200:
                    body:
                        application/vnd.ez.api.UserGroupRefList:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <UserGroupRefList href="/user/users/45/groups"
                                  media-type="application/vnd.ez.api.UserGroupRefList">
                                  <UserGroup href="/user/groups/1/5/34" media-type="application/vnd.ez.api.UserGroup">
                                    <unassign href="/user/users/45/groups/34" method="DELETE" />
                                  </UserGroup>
                                  <UserGroup href="/user/groups/1/5/78" media-type="application/vnd.ez.api.UserGroup">
                                    <unassign href="/user/users/45/groups/78" method="DELETE" />
                                  </UserGroup>
                                </UserGroupRefList>
                401:
                    description: Error - if the user has no permission to read user groups
                404:
                  description: Error -if the user does not exist
        post:
            description: Returns a list of user groups the user belongs to. The returned list includes the resources for unassigning a user group if the user is in multiple groups.
            queryParameters:
                group:
                    description: the new parent group resource of the user
            headers:
                Accept:
                    description: application/vnd.ez.api.UserGroupRefList+xml or application/vnd.ez.api.UserGroupRefList+json
            body:
                application/vnd.ez.api.UserGroupRefList+xml:
                    example:  |
                        POST /user/users/45/groups?/user/groups/1/5/88 HTTP/1.1
                        Accept: application/vnd.ez.api.UserGroupRefList+xml
            responses:
                200:
                    body:
                        application/vnd.ez.api.UserGroupRefList:
                            example:  |
                                <?xml version="1.0" encoding="UTF-8"?>
                                <UserGroupRefList href="/user/users/45/groups"
                                  media-type="application/vnd.ez.api.UserGroupRefList">
                                  <UserGroup href="/user/groups/1/5/34" media-type="application/vnd.ez.api.UserGroup">
                                    <unassign href="/user/users/45/groups/34" method="DELETE" />
                                  </UserGroup>
                                  <UserGroup href="/user/groups/1/5/78" media-type="application/vnd.ez.api.UserGroup">
                                    <unassign href="/user/users/45/groups/78" method="DELETE" />
                                  </UserGroup>
                                  <UserGroup href="/user/groups/1/5/88" media-type="application/vnd.ez.api.UserGroup">
                                    <unassign href="/user/users/45/groups/88" method="DELETE" />
                                  </UserGroup>
                                </UserGroupRefList>
                401:
                    description: Error -if the user is not authorized to assign user groups
                403:
                    description: Error -if the new user group does not exist or the user is already in this group
                404:
                    description: Error -if the user does not exist
