<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/urlfield.md:59
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of the hash value in PHP
$hash = [
    'link' => 'https://www.ibexa.co/',
    'text' => 'Ibexa',
];
