<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/urlfield.md:31
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example

/** @var \Ibexa\Core\FieldType\Url\Value $url */
$url->link = 'https://www.ibexa.co';
$url->text = 'Ibexa';
