<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/urlfield.md:44
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Url as Url;

// Instantiates an Url Value object
$UrlValue = new Url\Value('https://www.ibexa.co/', 'Ibexa');
