ibexa.admin_ui:
    resource: '@IbexaAdminUiBundle/Resources/config/routing.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

ibexa.admin_ui.rest:
    resource: '@IbexaAdminUiBundle/Resources/config/routing_rest.yaml'
    prefix: '%ibexa.rest.path_prefix%'
