ibexa.calendar:
    resource: '@IbexaCalendarBundle/Resources/config/routing.yaml'
    defaults:
        siteaccess_group_whitelist: '%admin_group_name%'

ibexa.calendar.rest:
    resource: '@IbexaCalendarBundle/Resources/config/routing_rest.yaml'
    prefix: '%ibexa.rest.path_prefix%'
