<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/selectionfield.md:80
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Selection field type example settings

use Ibexa\Core\FieldType\Selection\Type;

$settings = [
    'isMultiple' => true,
    'options' => [1 => 'One', 2 => 'Two', 3 => 'Three'],
];
