<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/selectionfield.md:43
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Selection as Selection;

// Instanciates a selection value with items #1 and #2 selected
$selectionValue = new Selection\Value([1, 2]);
