<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/selectionfield.md:61
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of value in hash format

$hash = [1, 2];
