<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/selectionfield.md:28
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content examples

/** @var \Ibexa\Core\FieldType\Selection\Value $value */
// Single selection
$value->selection = [1];

// Multiple selection
$value->selection = [1, 4, 5];
