<?php

declare(strict_types=1);
// Source: docs/content_management/taxonomy/taxonomy_api.md:24
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var array<int, \Ibexa\Contracts\Taxonomy\Value\TaxonomyEntry> $springs */
/** @var \Ibexa\Contracts\Taxonomy\Service\TaxonomyServiceInterface $taxonomyService */
$springs[] = $taxonomyService->loadEntryByIdentifier('spring', 'tags');
$springs[] = $taxonomyService->loadEntryByIdentifier('spring', 'events');
$springs[] = $taxonomyService->loadEntryByIdentifier('spring', 'devices');
