<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/order_owner_criterion.md:17
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\OrderManagement\Value\Order\OrderQuery;

/** @var \Ibexa\Contracts\Core\Repository\UserService $userService */
$user = $userService->loadUserByLogin('user');

$query = new OrderQuery(
    new \Ibexa\Contracts\OrderManagement\Value\Order\Query\Criterion\OwnerCriterion(
        $user
    )
);
