<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/customprice_criterion.md:25
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;

/** @var \Ibexa\Contracts\ProductCatalog\Values\CustomerGroupInterface $customerGroup */
$query = new ProductQuery(
    null,
    new \Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion\CustomPrice(
        \Money\Money::EUR(13800),
        \Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion\Operator::GTE,
        $customerGroup
    )
);
