<?php

declare(strict_types=1);
// Source: docs/api/rest_api/extending_rest_api/creating_new_rest_resource.md:72
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Rest\Server\Values\CachedValue;

$locationId = 12345;

return new CachedValue(
    new MyValue($args),
    ['locationId' => $locationId]
);
