<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/datefield.md:65
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Example of the hash value in PHP
$hash = [
    'timestamp' => 1400856992,
    'rfc850' => 'Friday, 23-May-14 14:56:14 GMT+0000',
];
