<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/datefield.md:92
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Date field type example settings

use Ibexa\Core\FieldType\Date\Type;

$settings = [
    'defaultType' => Type::DEFAULT_EMPTY,
];
