<?php

declare(strict_types=1);
// Source: docs/administration/configuration/dynamic_configuration.md:81
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App;

use Ibexa\Contracts\Core\SiteAccess\ConfigResolverInterface;

class Service
{
    public function __construct(private readonly ConfigResolverInterface $configResolver)
    {
    }

    public function someMethodThatNeedConfig(): void
    {
        $configValue = $this->configResolver->getParameter('my_param', 'myapp');
    }
}
