<?php

declare(strict_types=1);
// Source: docs/administration/configuration/repository_configuration.md:349
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Container\ApiLoader\RepositoryConfigurationProviderInterface $repositoryConfigProvider */
$acmeConfig = $repositoryConfigProvider->getRepositoryConfig()['acme'];
