<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/imageassetfield.md:33
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example

/** @var \Ibexa\Core\FieldType\ImageAsset\Value $imageAssetValue */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
$imageAssetValue->destinationContentId = $contentInfo->id;
$imageAssetValue->alternativeText = 'Picture of an apple.';
