<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/imageassetfield.md:47
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example

use Ibexa\Core\FieldType\ImageAsset as ImageAsset;

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentInfo $contentInfo */
// Instantiates a ImageAsset Value object
$imageAssetValue = new ImageAsset\Value($contentInfo->id, 'Picture of an apple.');
