<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/product_attribute_aggregations.md:41
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;
use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\AttributeIntegerRangeAggregation;

$query = new ProductQuery();
$query->setAggregations([
    new AttributeIntegerRangeAggregation('buttons', 'number_of_buttons', [
        Range::ofInt(null, 5),
        Range::ofInt(5, 10),
        Range::ofInt(10, null),
    ]),
]);
