<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/product_attribute_aggregations.md:31
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\ProductCatalog\Values\Product\ProductQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Aggregation\AttributeSelectionTermAggregation;

$query = new ProductQuery();
$query->setAggregations([
    new AttributeSelectionTermAggregation('skin', 'skin_type'),
]);
