ibexa_design_engine:
    design_list:
        my_design: [ my_theme ]

ibexa:
    system:
        site_group:
            design: my_design
            content_view:
                full:
                    latest:
                        controller: ibexa_query::locationQueryAction
                        template: '@ibexadesign/full/latest.html.twig'
                        match:
                            Identifier\ContentType: "latest"
                        params:
                            query:
                                query_type: LatestContent
                                parameters:
                                    contentType: [article, blog_post]
                                assign_results_to: latest
                                
