ezdesign:
    design_list:
        my_design: [ my_theme ]

ezplatform:
    system:
        site_group:
            design: my_design
            content_view:
                full:
                    latest:
                        controller: ez_query::locationQueryAction
                        template: '@ezdesign/full/latest.html.twig'
                        match:
                            Identifier\ContentType: "latest"
                        params:
                            query:
                                query_type: LatestContent
                                parameters:
                                    contentType: [article, blog_post]
                                assign_results_to: latest
                                
