<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/maplocationfield.md:40
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\MapLocation as MapLocation;

// Instantiates a MapLocation Value object
$MapLocationValue = new MapLocation\Value(
    [
        'latitude' => 59.928732,
        'longitude' => 10.777888,
        'address' => 'Ibexa Nordics',
    ]
);
