<?php

declare(strict_types=1);
// Source: docs/multisite/languages/back_office_translations.md:63
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Contracts\Translation\TranslatorInterface;

final readonly class MyService
{
    public function __construct(private TranslatorInterface $translator)
    {
    }

    public function getTranslatedDescription(): string
    {
        return $this->translator->trans(
            'custom.extension.description',
            [],
            'custom_extension'
        );
    }
}
