<?php

declare(strict_types=1);
// Source: docs/search/aggregation_reference/floatrange_aggregation.md:18
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Aggregation\Range;

$query = new Query();
$query->aggregations[] = new Aggregation\Field\FloatRangeAggregation(
    'float',
    'product',
    'weight',
    [
    Range::ofFloat(null, 0.25),
    Range::ofFloat(0.25, 0.75),
    Range::ofFloat(0.75, null),
]
);
