#!/usr/bin/env php
<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */

/**
 * Syncs PHP-CS-Fixer-formatted inline snippets back to their source Markdown files.
 *
 * The extraction pipeline (tools/extract-inline-php.php) writes each inline PHP block
 * to code_samples/_inline_php/<path>/{sha256(body)}.php, prepending an auto-generated header.
 *
 *   <?php
 *   // Source: docs/path/to/file.md:N
 *   // (auto-generated by tools/extract-inline-php.php — do not edit)
 *   <blank line>
 *   <original snippet body>
 *
 * After php-cs-fixer reformats the files, this script:
 *   1. Groups all _inline_php files by their source Markdown path.
 *   2. Processes each group in descending line order so that patching a later block
 *      never shifts the line numbers of earlier blocks that are still to be processed.
 *   3. For each file, delegates the sync logic to InlinePhpSyncer and writes the result.
 *
 * Run automatically after php-cs-fixer via `composer fix-cs`.
 */

declare(strict_types=1);

require_once __DIR__ . '/../vendor/autoload.php';

use Ibexa\Tests\Documentation\InlineSamples\InlinePhpSyncer;

const INLINE_PHP_DIR = __DIR__ . '/../code_samples/_inline_php';
const REPO_ROOT = __DIR__ . '/..';

$syncer = new InlinePhpSyncer();

// --- Pass 1: collect all _inline_php files grouped by their source Markdown path. ---

/** @var array<string, list<array{phpPath: string, line: int}>> $byMdPath */
$byMdPath = [];

$iterator = new RecursiveIteratorIterator(
    new RecursiveDirectoryIterator(INLINE_PHP_DIR, RecursiveDirectoryIterator::SKIP_DOTS),
);

/** @var SplFileInfo $file */
foreach ($iterator as $file) {
    if (!$file->isFile() || $file->getExtension() !== 'php') {
        continue;
    }

    $content = file_get_contents($file->getRealPath());
    if ($content === false) {
        continue;
    }

    $location = $syncer->parseSourceLocation($content);
    if ($location === null) {
        fwrite(STDERR, "WARNING: No '// Source:' comment found in {$file->getRealPath()}, skipping.\n");
        continue;
    }

    $mdPath = REPO_ROOT . '/' . $location['path'];
    $byMdPath[$mdPath][] = ['phpPath' => $file->getRealPath(), 'line' => $location['line']];
}

// --- Pass 2: for each Markdown file, apply patches in descending line order. ---
// This ensures that modifying a block at line N does not shift the line numbers
// of blocks at lines < N that are yet to be processed.

$patchCount = 0;

foreach ($byMdPath as $mdPath => $entries) {
    if (!is_file($mdPath)) {
        fwrite(STDERR, "WARNING: Source file not found: $mdPath, skipping.\n");
        continue;
    }

    $mdContent = file_get_contents($mdPath);
    if ($mdContent === false) {
        fwrite(STDERR, "WARNING: Cannot read $mdPath, skipping.\n");
        continue;
    }

    // Sort highest body line first so earlier patches do not invalidate later line numbers.
    usort($entries, static fn (array $a, array $b): int => $b['line'] <=> $a['line']);

    $mdChanged = false;

    foreach ($entries as ['phpPath' => $phpPath, 'line' => $line]) {
        $phpContent = file_get_contents($phpPath);
        if ($phpContent === false) {
            continue;
        }

        $updated = $syncer->sync($phpContent, $mdContent);
        if ($updated === null) {
            continue;
        }

        $mdContent = $updated;
        $mdChanged = true;

        echo "Updated: " . substr($mdPath, strlen(REPO_ROOT) + 1) . " (block at line $line)\n";
        ++$patchCount;
    }

    if ($mdChanged) {
        file_put_contents($mdPath, $mdContent);
    }
}

echo sprintf(
    "Synced %d block%s back to Markdown files.\n",
    $patchCount,
    $patchCount !== 1 ? 's' : '',
);

