<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/imageorientation_criterion.md:22
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Core\Repository\Values\Content\Query;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion;
use Ibexa\Contracts\Core\Repository\Values\Content\Query\Criterion\Image\Orientation;

$query = new Query();
$query->query = new Orientation('image', 'landscape');
