<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md:211
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Symfony\Component\HttpFoundation\Response $response */
$response->headers->set('X-Location-Id', '123');

// Alternatively using several Location ID values
$response->headers->set('X-Location-Id', '123,212,42');
