<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md:175
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\HttpCache\Handler\ContentTagInterface $tagHandler */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Content $content */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Location $location */

// Example for tagging everything needed for Content:
$tagHandler->addContentTags([$content->id]);
$tagHandler->addLocationTags([$location->id]);
$tagHandler->addParentLocationTags([$location->parentLocationId]);
$tagHandler->addPathTags($location->path);
$tagHandler->addContentTypeTags([$content->getContentType()->id]);

// Example when using ESI as also shown below using FOS tag handler (there is also a method for relation locations):
$tagHandler->addRelationTags([33, 44]);
