<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md:197
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\HttpCache\Handler\ContentTagInterface;

/** @var \FOS\HttpCacheBundle\Http\SymfonyResponseTagger $responseTagger */
$responseTagger->addTags([ContentTagInterface::RELATION_PREFIX . '33', ContentTagInterface::RELATION_PREFIX . '34']);
