<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/content_aware_cache.md:330
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\HttpCache\Handler\ContentTagInterface;

/** @var \Ibexa\Contracts\HttpCache\PurgeClient\PurgeClientInterface $purgeClient */
/** @var \Ibexa\Contracts\Core\Repository\Values\Content\Location $location */

// Example for purging by Location ID:
$purgeClient->purge([ContentTagInterface::LOCATION_PREFIX . $location->id]);

// Example for purging all cache for instance for full re-deploy cases, usually this triggers an expiry (soft purge):
$purgeClient->purgeAll();
