<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/payment_order_criterion.md:19
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Payment\Payment\PaymentQuery;

/** @var \Ibexa\Contracts\OrderManagement\OrderServiceInterface $orderService */
$order = $orderService->getOrder(4);

$query = new PaymentQuery(
    new \Ibexa\Contracts\Payment\Payment\Query\Criterion\Order($order)
);
