<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Tests\Documentation\InlineSamples;

/**
 * Builds the file content for an _inline_php/ snippet file.
 *
 * Mirrors the logic in tools/extract-inline-php.php: given a snippet body as returned
 * by MarkdownExtractor (with admonition indentation already stripped, but potentially
 * starting with a <?php opening tag), produces a standalone PHP file with a fixed header:
 *
 *   <?php
 *   declare(strict_types=1);
 *   // Source: docs/path/to/file.md:LINE
 *   // (auto-generated by tools/extract-inline-php.php — do not edit)
 *   <blank line>
 *   <body without <?php tag and without declare(strict_types=1)>
 *
 * Important: the <?php opening tag is removed from the body and normalised into the
 * mandatory file-level tag.  Any blank line that immediately followed <?php in the
 * original snippet is also consumed by ltrim() at this stage; InlinePhpSyncer is
 * responsible for detecting and restoring it when syncing changes back to Markdown.
 *
 * @see tools/extract-inline-php.php   The script that drives this class.
 * @see InlinePhpSyncer                Complementary class for syncing changes back.
 */
final class InlinePhpWriter
{
    public const string FILE_TEMPLATE =
        "<?php\n\ndeclare(strict_types=1);\n// Source: %s:%d\n// (auto-generated by tools/extract-inline-php.php — do not edit)\n\n%s\n";

    /**
     * Builds the file content for a single _inline_php snippet file.
     *
     * @param string $sourcePath  Relative path stored in the // Source comment,
     *                            e.g. "docs/api/example.md".
     * @param int    $bodyLine    1-based line number of the first body line in the source
     *                            Markdown file (as returned by MarkdownExtractor::extract()).
     * @param string $body        Snippet body as returned by MarkdownExtractor::extract():
     *                            admonition indentation already stripped, may start with <?php.
     */
    public function build(string $sourcePath, int $bodyLine, string $body): string
    {
        $hasOpenTag = str_starts_with(ltrim($body), '<?php');
        $bodyWithoutTag = $hasOpenTag
            ? ltrim(substr($body, strpos($body, '<?php') + 5))
            : $body;

        // Strip a declare(strict_types=1) that the snippet already contains — the
        // template always emits one, so keeping both would produce a duplicate.
        // Also consume the optional blank line that follows it: the template already
        // adds \n\n before the body, so leaving an extra leading \n would produce
        // two blank lines before the first real statement (e.g. namespace).
        // No /m flag: only strip at the start of the string (after ltrim).
        $bodyWithoutTag = preg_replace(
            '/^declare\s*\(\s*strict_types\s*=\s*1\s*\)[ \t]*;[ \t]*\n\n?/',
            '',
            ltrim($bodyWithoutTag),
        );

        return sprintf(self::FILE_TEMPLATE, $sourcePath, $bodyLine, $bodyWithoutTag);
    }
}
