<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Tests\Documentation\InlineSamples;

/**
 * Syncs reformatted PHP snippets back to their source Markdown files.
 *
 * The extraction pipeline (tools/extract-inline-php.php) writes each inline PHP block to an
 * _inline_php/ file with a fixed header format:
 *
 *   <?php
 *   // Source: docs/path/to/file.md:LINE
 *   // (auto-generated by tools/extract-inline-php.php — do not edit)
 *   <blank line>
 *   <snippet body without the <?php opening tag>
 *
 * After php-cs-fixer has reformatted the file, this class maps the changes back:
 *   1. Locates the "// Source:" comment to find the original line number.
 *   2. Strips the header to recover the reformatted body.
 *   3. Restores the <?php opening tag when the original snippet had one.
 *   4. Restores the blank line between <?php and the first code line when the original had one
 *      (the extraction script drops it via ltrim()).
 *   5. Re-applies admonition indentation that was stripped during extraction.
 *   6. Returns the updated Markdown content, or null when nothing changed.
 *
 * @see tools/extract-inline-php.php   Complementary extraction logic.
 * @see tools/sync-inline-php-to-markdown.php   Script that drives this class over the filesystem.
 */
final class InlinePhpSyncer
{
    /**
     * Parses the source location embedded in a _inline_php file.
     *
     * @return array{path: string, line: int}|null
     */
    public function parseSourceLocation(string $phpFileContent): ?array
    {
        foreach (explode("\n", $phpFileContent) as $line) {
            if (preg_match('/^\/\/ Source: (.+):(\d+)$/', $line, $m)) {
                return ['path' => $m[1], 'line' => (int) $m[2]];
            }
        }

        return null;
    }

    /**
     * Applies changes from a reformatted _inline_php file back to its source Markdown content.
     *
     * @return string|null Updated Markdown content, or null if nothing changed or the source
     *                     location cannot be mapped.
     */
    public function sync(string $phpFileContent, string $mdContent): ?string
    {
        $location = $this->parseSourceLocation($phpFileContent);
        if ($location === null) {
            return null;
        }

        $fixedBody = $this->extractBody($phpFileContent);

        return $this->applyToMarkdown($fixedBody, $location['line'], $mdContent);
    }

    /**
     * Extracts the snippet body from a _inline_php file by stripping the auto-generated header.
     *
     * Uses the "// (auto-generated ...)" line as the end-of-header anchor so that the
     * body is located correctly even when a refactoring tool (e.g. Rector) removes the
     * blank separator line between the header and the body.
     * The <?php opening tag is NOT included (it is managed separately in applyToMarkdown).
     */
    private function extractBody(string $phpFileContent): string
    {
        $lines = explode("\n", $phpFileContent);

        // Find the closing header line: the auto-generated marker.
        $autoGenIdx = null;
        foreach ($lines as $i => $line) {
            if (str_starts_with($line, '// (auto-generated by tools/extract-inline-php.php')) {
                $autoGenIdx = $i;
                break;
            }
        }

        if ($autoGenIdx === null) {
            return '';
        }

        // Body starts right after the marker; skip one optional blank separator.
        // The blank may be absent when a refactoring tool (e.g. Rector) collapses it.
        $cursor = $autoGenIdx + 1;
        if (isset($lines[$cursor]) && $lines[$cursor] === '') {
            ++$cursor;
        }

        $bodyLines = array_slice($lines, $cursor);

        // cs-fixer ensures a single trailing newline; drop the resulting empty last element.
        if (end($bodyLines) === '') {
            array_pop($bodyLines);
        }

        return implode("\n", $bodyLines);
    }

    /**
     * Replaces the body of the fenced code block at $bodyLine in $mdContent with $fixedBody.
     *
     * @param string $fixedBody  Reformatted body as stored in the _inline_php file:
     *                           without the <?php tag and without admonition indentation.
     * @param int    $bodyLine   1-based line number of the first body line in the Markdown.
     */
    private function applyToMarkdown(string $fixedBody, int $bodyLine, string $mdContent): ?string
    {
        $mdLines = explode("\n", $mdContent);

        // $bodyLine (1-based) is the first body line; the opening fence is one line above it.
        $fenceIdx = $bodyLine - 2;
        $bodyStartIdx = $bodyLine - 1;

        if ($fenceIdx < 0 || $fenceIdx >= count($mdLines)) {
            return null;
        }

        // Detect admonition indentation from the opening fence line.
        preg_match('/^(?P<indent> *)```/', $mdLines[$fenceIdx], $indentMatch);
        $indent = $indentMatch['indent'] ?? '';

        // Locate the closing fence (same indentation prefix + ```).
        $closingFence = $indent . '```';
        $closingIdx = null;
        for ($i = $bodyStartIdx; $i < count($mdLines); ++$i) {
            if ($mdLines[$i] === $closingFence) {
                $closingIdx = $i;
                break;
            }
        }

        if ($closingIdx === null) {
            return null;
        }

        $originalBodyLines = array_slice($mdLines, $bodyStartIdx, $closingIdx - $bodyStartIdx);

        // Detect whether the original snippet opened with <?php.
        $firstLine = $originalBodyLines[0] ?? '';
        $firstLineStripped = $indent !== '' && str_starts_with($firstLine, $indent)
            ? substr($firstLine, strlen($indent))
            : $firstLine;
        $hadOpenTag = str_starts_with(ltrim($firstLineStripped), '<?php');

        if ($hadOpenTag) {
            // Detect whether there was a blank line between <?php and the first code line.
            // The extraction script uses ltrim() which drops it; we restore it here.
            $secondLine = $originalBodyLines[1] ?? null;
            $secondLineStripped = $secondLine !== null && $indent !== '' && str_starts_with((string) $secondLine, $indent)
                ? substr((string) $secondLine, strlen($indent))
                : $secondLine;
            $hadBlankAfterOpenTag = $secondLineStripped === '';

            // Detect declare(strict_types=1) anywhere in the original snippet.
            // The extractor strips it from the body; we restore it right after <?php
            // per CS-Fixer convention (no blank between <?php and declare).
            $hadDeclareStrictTypes = false;
            foreach ($originalBodyLines as $originalLine) {
                $strippedLine = $indent !== '' && str_starts_with($originalLine, $indent)
                    ? substr($originalLine, strlen($indent))
                    : $originalLine;
                if (preg_match('/^declare\s*\(\s*strict_types\s*=\s*1\s*\)\s*;$/', $strippedLine)) {
                    $hadDeclareStrictTypes = true;
                    break;
                }
            }

            $prefix = '<?php' . "\n";
            if ($hadDeclareStrictTypes) {
                // CS-Fixer convention: blank after <?php, declare, then blank before body.
                $prefix .= "\ndeclare(strict_types=1);\n\n";
            } elseif ($hadBlankAfterOpenTag) {
                $prefix .= "\n";
            }
            $fixedBody = $prefix . $fixedBody;
        }

        $fixedBodyLines = explode("\n", $fixedBody);

        // Re-apply admonition indentation to every non-empty line.
        if ($indent !== '') {
            $fixedBodyLines = array_map(
                static fn (string $line): string => $line !== '' ? $indent . $line : $line,
                $fixedBodyLines,
            );
            $fixedBody = implode("\n", $fixedBodyLines);
        }

        if (implode("\n", $originalBodyLines) === $fixedBody) {
            return null;
        }

        array_splice($mdLines, $bodyStartIdx, $closingIdx - $bodyStartIdx, $fixedBodyLines);

        return implode("\n", $mdLines);
    }
}
