<?php

/**
 * @copyright Copyright (C) Ibexa AS. All rights reserved.
 * @license For full copyright and license information view LICENSE file distributed with this source code.
 */
declare(strict_types=1);

namespace Ibexa\Tests\Documentation\InlineSamples;

use PHPUnit\Framework\Attributes\DataProvider;
use PHPUnit\Framework\TestCase;

/**
 * Unit tests for InlinePhpWriter::build().
 *
 * Each test verifies a specific aspect of the file format produced for _inline_php/ files.
 */
final class InlinePhpWriterTest extends TestCase
{
    private InlinePhpWriter $writer;

    protected function setUp(): void
    {
        $this->writer = new InlinePhpWriter();
    }

    // -------------------------------------------------------------------------
    // Header structure
    // -------------------------------------------------------------------------

    public function testFileAlwaysStartsWithPhpOpeningTag(): void
    {
        $content = $this->writer->build('docs/example.md', 5, '$x = 1;');
        self::assertStringStartsWith("<?php\n", $content);
    }

    public function testDeclareStrictTypesFollowsOpeningTag(): void
    {
        $content = $this->writer->build('docs/example.md', 5, '$x = 1;');
        self::assertStringStartsWith("<?php\n\ndeclare(strict_types=1);\n", $content);
    }

    public function testSourceCommentContainsPathAndLine(): void
    {
        $content = $this->writer->build('docs/api/example.md', 42, '$x = 1;');
        self::assertStringContainsString('// Source: docs/api/example.md:42', $content);
    }

    public function testAutoGeneratedCommentIsPresent(): void
    {
        $content = $this->writer->build('docs/example.md', 1, '$x = 1;');
        self::assertStringContainsString(
            '// (auto-generated by tools/extract-inline-php.php — do not edit)',
            $content,
        );
    }

    public function testBlankLineSeparatesHeaderFromBody(): void
    {
        $content = $this->writer->build('docs/example.md', 1, '$x = 1;');
        // The blank line sits between the auto-generated comment and the body.
        self::assertStringContainsString(
            "// (auto-generated by tools/extract-inline-php.php — do not edit)\n\n\$x = 1;",
            $content,
        );
    }

    public function testFileEndsWithSingleTrailingNewline(): void
    {
        $content = $this->writer->build('docs/example.md', 1, '$x = 1;');
        self::assertStringEndsWith("\$x = 1;\n", $content);
        // Not two newlines
        self::assertStringNotContainsString("\$x = 1;\n\n", $content);
    }

    // -------------------------------------------------------------------------
    // Body without <?php tag
    // -------------------------------------------------------------------------

    public function testPlainBodyIsWrittenAsIs(): void
    {
        $content = $this->writer->build('docs/example.md', 10, '$foo = bar();');
        self::assertStringContainsString('$foo = bar();', $content);
    }

    public function testMultiLineBodyIsPreserved(): void
    {
        $body = "\$a = 1;\n\$b = 2;\nreturn \$a + \$b;";
        $content = $this->writer->build('docs/example.md', 5, $body);
        self::assertStringContainsString($body, $content);
    }

    // -------------------------------------------------------------------------
    // Body with <?php tag
    // -------------------------------------------------------------------------

    public function testPhpTagIsStrippedFromBody(): void
    {
        $content = $this->writer->build('docs/example.md', 3, "<?php\n\$x = 1;");
        // Only the header <?php must appear (once); the body must NOT contain a second one.
        self::assertSame(1, substr_count($content, '<?php'));
        self::assertStringContainsString('$x = 1;', $content);
    }

    public function testPhpTagWithBlankLineAfterItIsStripped(): void
    {
        // The blank line between <?php and the first code line is consumed by ltrim().
        // This is intentional — InlinePhpSyncer restores it when syncing back.
        $content = $this->writer->build('docs/example.md', 4, "<?php\n\n\$x = 1;");
        self::assertSame(1, substr_count($content, '<?php'));
        // The blank line after <?php must NOT appear between header and body.
        self::assertStringContainsString(
            "// (auto-generated by tools/extract-inline-php.php — do not edit)\n\n\$x = 1;",
            $content,
        );
    }

    public function testPhpTagWithLeadingWhitespaceIsStripped(): void
    {
        // MarkdownExtractor strips admonition indentation, but leading whitespace
        // before <?php is still handled via ltrim in the detection check.
        $content = $this->writer->build('docs/example.md', 7, "  <?php\n\$x = 1;");
        self::assertSame(1, substr_count($content, '<?php'));
        self::assertStringContainsString('$x = 1;', $content);
    }

    public function testBodyAfterPhpTagContainsNamespace(): void
    {
        $body = "<?php\n\nnamespace App\\Foo;\n\n\$x = 1;";
        $content = $this->writer->build('docs/example.md', 3, $body);
        // Namespace must be in the file body (after the header blank line).
        self::assertStringContainsString('namespace App\\Foo;', $content);
        self::assertSame(1, substr_count($content, '<?php'));
    }

    // -------------------------------------------------------------------------
    // Data-provider: exact full-file content for selected cases
    // -------------------------------------------------------------------------

    /**
     * @param string $body         Input body (from MarkdownExtractor)
     * @param string $expectedBody Expected body section after the blank separator
     */
    #[DataProvider('provideExactContent')]
    public function testExactFileContent(string $sourcePath, int $line, string $body, string $expectedBody): void
    {
        $expected = sprintf(InlinePhpWriter::FILE_TEMPLATE, $sourcePath, $line, $expectedBody);
        self::assertSame($expected, $this->writer->build($sourcePath, $line, $body));
    }

    /**
     * @return iterable<string, array{string, int, string, string}>
     */
    public static function provideExactContent(): iterable
    {
        yield 'plain body' => [
            'docs/api/example.md', 5, '$x = 1;', '$x = 1;',
        ];

        yield 'multiline plain body' => [
            'docs/api/example.md', 10, "\$a = 1;\n\$b = 2;", "\$a = 1;\n\$b = 2;",
        ];

        yield 'body with php tag, no blank line' => [
            'docs/foo.md', 3, "<?php\n\$x = 1;", '$x = 1;',
        ];

        yield 'body with php tag and blank line after' => [
            'docs/foo.md', 4, "<?php\n\n\$x = 1;", '$x = 1;',
        ];

        yield 'body with php tag, namespace, uses' => [
            'docs/bar.md', 7,
            "<?php\n\nnamespace App;\n\nuse Foo\\Bar;\n\n\$x = 1;",
            "namespace App;\n\nuse Foo\\Bar;\n\n\$x = 1;",
        ];

        yield 'body with declare strict_types stripped' => [
            'docs/foo.md', 10,
            "<?php\ndeclare(strict_types=1);\n\nnamespace App;\n\n\$x = 1;",
            "namespace App;\n\n\$x = 1;",
        ];

        yield 'plain body with declare strict_types stripped' => [
            'docs/foo.md', 5,
            "declare(strict_types=1);\n\$x = 1;",
            '$x = 1;',
        ];
    }
}
