<?php

declare(strict_types=1);
// Source: docs/permissions/custom_policies.md:24
// (auto-generated by tools/extract-inline-php.php — do not edit)

$config = [
    'content' => [
        'read' => ['Class', 'ParentClass', 'Node', 'Language'],
        'edit' => ['Class', 'ParentClass', 'Language'],
    ],
    'custom_module' => [
        'custom_function_1' => null,
        'custom_function_2' => ['CustomLimitation'],
    ],
];
