<?php

declare(strict_types=1);
// Source: docs/permissions/custom_policies.md:42
// (auto-generated by tools/extract-inline-php.php — do not edit)

namespace App\Security;

use Ibexa\Bundle\Core\DependencyInjection\Configuration\ConfigBuilderInterface;
use Ibexa\Bundle\Core\DependencyInjection\Security\PolicyProvider\PolicyProviderInterface;

class MyPolicyProvider implements PolicyProviderInterface
{
    public function addPolicies(ConfigBuilderInterface $configBuilder): void
    {
        $configBuilder->addConfig([
             'custom_module' => [
                 'custom_function_1' => null,
                 'custom_function_2' => ['CustomLimitation'],
             ],
         ]);
    }
}
