<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/binaryfilefield.md:50
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var \Ibexa\Contracts\Core\Repository\Values\Content\ContentCreateStruct $fileContentCreateStruct */
$fileContentCreateStruct->setField('file', new Ibexa\Core\FieldType\BinaryFile\Value([
    'fileName' => 'example.pdf',
    'inputUri' => '/tmp/example_for_website.pdf',
]));
