<?php

declare(strict_types=1);
// Source: docs/search/criteria_reference/order_created_criterion.md:20
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\OrderManagement\Value\Order\OrderQuery;
use Ibexa\Contracts\ProductCatalog\Values\Product\Query\Criterion;

$criteria = new \Ibexa\Contracts\OrderManagement\Value\Order\Query\Criterion\CreatedAtCriterion(
    new DateTime('2023-03-01'),
    'GTE'
);

$orderQuery = new OrderQuery($criteria);
