<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/keywordfield.md:30
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example
use Ibexa\Core\FieldType\Keyword\Value;

// Instantiates a Value object
$keywordValue = new Value();

// Sets an array of keywords as a value
$keywordValue->values = ['php', 'css3', 'html5', 'Ibexa Platform'];
