<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/keywordfield.md:47
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Constructor example
use Ibexa\Core\FieldType\Keyword\Value;

// Instantiates a Value object with an array of keywords
$keywordValue = new Value(['php5', 'css3', 'html5']);

// Instantiates a Value object with a list of keywords in a string
// This is equivalent to the example above
$keywordValue = new Value('php5,css3,html5');
