<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/measurementfield.md:46
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Simple input (single value) example

use Ibexa\Measurement\FieldType\MeasurementValue;

/** @var \Ibexa\Contracts\Measurement\MeasurementServiceInterface $measurementService */

// Instantiates a Measurement Value object
$measurementValue = new MeasurementValue(
    $measurementService->buildSimpleValue(
        'length',
        13.5,
        'centimeter'
    )
);
