<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/measurementfield.md:63
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Range input value example

use Ibexa\Measurement\FieldType\MeasurementValue;

/** @var \Ibexa\Contracts\Measurement\MeasurementServiceInterface $measurementService */

// Instantiates a Measurement Value object
$measurementValue = new MeasurementValue(
    $measurementService->buildRangeValue(
        'volume',
        0.5,
        0.7,
        'liter'
    )
);
