<?php

declare(strict_types=1);
// Source: docs/content_management/workflow/add_custom_workflow_action.md:84
// (auto-generated by tools/extract-inline-php.php — do not edit)

/** @var array<string, mixed> $context */
/** @var \Symfony\Component\Workflow\Event\TransitionEvent $event */
$new_context = $context;
$new_context['message'] = 'This article went through proofreading';
$event->setContext($new_context);
