<?php

declare(strict_types=1);
// Source: docs/administration/configuration/configuration.md:76
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Usage inside a controller
/** @var \Symfony\Component\DependencyInjection\ContainerInterface $container */
$myParameter = $container->getParameter('myapp.parameter.name');
