<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/floatfield.md:65
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Validator configuration example in PHP

/** @var \Ibexa\Contracts\Core\Repository\Repository $repository */
$contentTypeService = $repository->getContentTypeService();
$floatFieldCreateStruct = $contentTypeService->newFieldDefinitionCreateStruct('float', 'ibexa_float');

// Accept only numbers between 0.1 and 203.99
$floatFieldCreateStruct->validatorConfiguration = [
    'FileSizeValidator' => [
        'minFloatValue' => 0.1,
        'maxFloatValue' => 203.99,
    ],
];
