<?php

declare(strict_types=1);
// Source: docs/content_management/field_types/field_type_reference/floatfield.md:31
// (auto-generated by tools/extract-inline-php.php — do not edit)

// Value object content example

use Ibexa\Core\FieldType\Float\Value as FloatValue;

// Instantiates a Float Value object
$floatValue = new FloatValue();

$floatValue->value = 284.773;
