<?php

declare(strict_types=1);
// Source: docs/commerce/cart/cart_api.md:68
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Cart\Value\CartMetadataUpdateStruct;

// ...

/** @var \Ibexa\Contracts\Core\Repository\UserService $userService */
/** @var \Ibexa\Contracts\Cart\CartServiceInterface $cartService */
/** @var \Ibexa\Contracts\Cart\Value\CartInterface $cart */
$updateMetadataStruct = new CartMetadataUpdateStruct();
$updateMetadataStruct->setOwner($userService->loadUserByLogin('user'));

$cart = $cartService->updateCartMetadata($cart, $updateMetadataStruct);
