<?php

declare(strict_types=1);
// Source: docs/commerce/cart/cart_api.md:157
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Cart\Value\CartCreateStruct;
use Ibexa\Contracts\Core\Collection\ArrayMap;
use Ibexa\Contracts\ProductCatalog\Values\CurrencyInterface;

/** @var \Ibexa\Contracts\Cart\CartServiceInterface $cartService */
/** @var CurrencyInterface $currency */
$createStruct = new CartCreateStruct('My Cart', $currency);
$createStruct->setContext(new ArrayMap([
    'coupon_code' => 'X1MF7699',
]));

$cart = $cartService->createCart($createStruct);
