<?php

declare(strict_types=1);
// Source: docs/commerce/cart/cart_api.md:179
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Ibexa\Contracts\Cart\Value\EntryAddStruct;
use Ibexa\Contracts\Core\Collection\ArrayMap;
use Ibexa\ProductCatalog\Local\Repository\Values\Product;

/** @var \Ibexa\Contracts\Cart\CartServiceInterface $cartService */
/** @var \Ibexa\Contracts\Cart\Value\CartInterface $cart */
/** @var Product $product */
$entryAddStruct = new EntryAddStruct($product);
$entryAddStruct->setContext(new ArrayMap([
    'tshirt_text' => 'EqEqEqEq',
]));

 $cartService->addEntry($cart, $entryAddStruct);
