<?php

declare(strict_types=1);
// Source: docs/administration/back_office/customize_calendar.md:84
// (auto-generated by tools/extract-inline-php.php — do not edit)

use App\Calendar\Holidays\Event;
use Ibexa\Contracts\Calendar\EventCollection;

/** @var \App\Calendar\Holidays\EventType $eventType */
$collection = new EventCollection([
    new Event('Event 1', new DateTime('2024-01-01'), $eventType),
    new Event('Event 2', new DateTime('2024-01-02'), $eventType),
    // ...
]);
