ibexa:
    system:
        default:
            field_templates:
                - { template: '@ibexadesign/field_types/field_type.html.twig', priority: 0 }
            field_comparison_templates:
                - { template: '@ibexadesign/field_types/field_type_comparison.html.twig', priority: 10 }
