name: "Check code samples"

on:
    pull_request: ~

jobs:
    code-samples-validation:
        name: Validate code samples
        runs-on: "ubuntu-22.04"
        strategy:
            matrix:
                php:
                    - "7.4"
        steps:
            - uses: actions/checkout@v4

            - name: Setup PHP Action
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  extensions: "pdo_sqlite, gd"
                  tools: cs2pr

            - name: Generate token
              id: generate_token
              uses: actions/create-github-app-token@v2
              with:
                  app-id: ${{ secrets.AUTOMATION_CLIENT_ID }}
                  private-key: ${{ secrets.AUTOMATION_CLIENT_SECRET }}
                  owner: ${{ github.repository_owner }}

            - name: Add composer keys for private packagist
              run: |
                  composer config --global http-basic.updates.ibexa.co $SATIS_NETWORK_KEY $SATIS_NETWORK_TOKEN
                  composer config --global github-oauth.github.com $GITHUB_TOKEN
              env:
                  SATIS_NETWORK_KEY: ${{ secrets.SATIS_NETWORK_KEY }}
                  SATIS_NETWORK_TOKEN: ${{ secrets.SATIS_NETWORK_TOKEN }}
                  GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}

            - uses: ramsey/composer-install@v3
              with:
                  dependency-versions: highest

            - name: Run PHPStan analysis
              run: composer phpstan
