<?php

declare(strict_types=1);
// Source: docs/infrastructure_and_maintenance/cache/http_cache/reverse_proxy.md:94
// (auto-generated by tools/extract-inline-php.php — do not edit)

use Symfony\Component\HttpFoundation\Request;

/** @var \Symfony\Component\HttpFoundation\Request $request */
Request::setTrustedProxies([$request->server->get('REMOTE_ADDR')], Request::HEADER_X_FORWARDED_FOR | Request::HEADER_X_FORWARDED_HOST | Request::HEADER_X_FORWARDED_PROTO | Request::HEADER_X_FORWARDED_PORT);
