<?php

declare(strict_types=1);
// Source: docs/content_management/collaborative_editing/configure_collaborative_editing.md:28
// (auto-generated by tools/extract-inline-php.php — do not edit)

return [
    // A lot of bundles…
    Ibexa\Bundle\FieldTypeRichTextRTE\IbexaFieldTypeRichTextRTEBundle::class => ['all' => true],
    Ibexa\Bundle\CkeditorPremium\IbexaCkeditorPremiumBundle::class => ['all' => true],
];
