ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_styles: [note_box]
ibexa_fieldtype_richtext:
    custom_styles:
        note_box:
            template: field_type/ibexa_richtext/custom_styles/note_box.html.twig
