ezplatform:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    toolbars:
                        heading:
                            buttons:
                                ezanchor:
                                    priority: 100
                                ezembedinline:
                                    visible: false
