ibexa:
    system:
        admin_group:
            fieldtypes:
                ezrichtext:
                    custom_tags: [ezfactbox]
                    toolbar:
                        custom_tags_group:
                            buttons:
                                ezfactbox:
                                    priority: 5
                    custom_tags: [linktag]
                    custom_tags: [acronym]
ibexa_fieldtype_richtext:
    custom_tags:
        ezfactbox:
            template: field_type/ibexa_fieldtype_richtext/custom_tags/ezfactbox.html.twig
            icon: '/assets/field_type/ibexa_fieldtype_richtext/custom_tags/icon/factbox.svg#factbox'
            attributes:
                name:
                    type: string
                    required: true
                style:
                    type: choice
                    required: true
                    default_value: light
                    choices: [light, dark]
        linktag:
            template: '@ibexadesign/custom_tags/vcustom.html.twig'
            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#link'
            attributes:
                attrTitle:
                    type: string
                    required: false
                attrDesc:
                    type: string
                    required: false
                attrColor:
                    type: choice
                    required: false
                    choices: [Red, Blue, Green]
                attrUrl:
                    type: link
                    required: false
        badge:
            template: field_type/ibexa_fieldtype_richtext/custom_tags/badge.html.twig
            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#bookmark'
            is_inline: true
            attributes:
                # ...
        acronym:
            template: field_type/ibexa_fieldtype_richtext/custom_tags/acronym.html.twig
            icon: '/bundles/ibexaplatformicons/img/all-icons.svg#information'
            is_inline: true
            attributes:
                explanation:
                    type: 'string'
