ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    custom_styles: [highlight]
ibexa_fieldtype_richtext:
    custom_styles:
        highlight:
            template: field_type/ibexa_richtext/custom_styles/highlight.html.twig
            inline: true
