ibexa:
    system:
        admin_group:
            fieldtypes:
                ibexa_richtext:
                    toolbars:
                        paragraph:
                            buttons:
                                date:
                                    priority: 0
ibexa_fieldtype_richtext:
    alloy_editor:
        extra_plugins: [date]
